feat: implement auth page on refine cloud
refinedev/refine pull request #2582
Opened 2022-09-26 12:48 UTC by yildirayunlu

Support new [AuthPage](https://refine.dev/docs/api-reference/antd/components/antd-auth-page/) (login/register, etc) on refine cloud.

2022-09-28 11:38 UTC, omeraplak requested changes

2022-09-28 11:38 UTC, omeraplak commented on packages/cloud/src/hooks/useAuthProviderWithCloudConfig/index.ts
> +                    return await sdk.auth
we don't need `then` and `catch` blocks

2022-10-20 20:15 UTC, sevkioruc commented on packages/sdk/src/services/auth.ts
> +        return false;
Hey @yildirayunlu, could it like that as well?
```suggestion
   return !!accessToken;
```

2022-10-21 08:44 UTC, yildirayunlu commented on packages/sdk/src/services/auth.ts
> +        return false;
Thank you for the suggestion @sevkioruc. It can be used. 🚀

2022-10-24 12:46 UTC, closed without merging