WIP: breadcrumb in Refine options
refinedev/refine pull request #2872
Opened 2022-10-21 11:32 UTC by TDP17

As discussed in the issue #2816 - added breadcrumb to Refine options that ends up in RefineContext. Accessed this context in each individual CRUD component. 
**Option passed in individual CRUD component takes priority over the option in RefineContext**

### Test plan (required)

- [x] Automated tests 
![image](https://user-images.githubusercontent.com/71214045/197185414-bee5832e-5a6e-4bfa-b399-d82659d3e16c.png)
- [ ] Manually tested via live-examples - option precedence of crud over refine, edge cases like undefined and component

### Closing issues
Closes #2816

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed

To be done
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2022-10-21 12:29 UTC, aliemir commented
Hey @TDP17, thank you for your effort! I know this is WIP but wanted to give a quick feedback for the lines;

```jsx
const breadcrumb = breadcrumbFromProps ?? options?.breadcrumb;
```

This will be breaking change for users hiding breadcrumb component in the current versions (by passing `breadcrumb={null}`, instead of `??` I think we need to do `typeof` and check for `undefined` 🤔 

We missed this check in our tests 🤦 What do you think? If you come up with a different way, I'll be happy to hear 🚀

2022-10-21 13:46 UTC, omeraplak commented
> const breadcrumb: ReactNode =
>   typeof breadcrumbFromProps === "undefined"
>       ? options?.breadcrumb
>       : breadcrumbFromProps;

I agree. Ternary LGTM! 🎃 
![Ternary](https://miro.medium.com/max/524/1*ERmxDYw_394HjG78S7Ikgg.jpeg)

2022-10-24 06:11 UTC, omeraplak commented
> * 3

Hey @TDP17 ,
Thank you so much for your great contribution and hard work! looks great at first glance. We'll probably merge it today.

As a suggestion, a [`tip`](https://docusaurus.io/docs/next/markdown-features/admonitions) can be added to the `breadcrumb` [*](https://refine.dev/docs/api-reference/mui/components/basic-views/create/#breadcrumb) [**](https://refine.dev/docs/api-reference/mantine/components/basic-views/create/#breadcrumb) [***](https://refine.dev/docs/api-reference/antd/components/breadcrumb/) section of CRUD components. that this feature can be managed globally

You can have a look at the past releases for the changeset, https://github.com/refinedev/refine/releases

As an example of this feature,

---
Added ability to manage breadcrumb component globally via `options`
## Usage

```tsx
<Refine
options= {{
   breadcrumb: false, // hide globally
}}
```
or
```tsx
<Refine
options= {{
   breadcrumb: <MyCustomBreadcrumbComponent /> // custom component
}}
```
---

2022-10-24 08:47 UTC, salihozdemir commented on packages/mantine/src/components/crud/create/index.tsx
> +            <>{breadcrumb}</> ?? undefined
```suggestion
            {breadcrumb}
```

Isn't the undefined check already done above?

2022-10-24 08:48 UTC, salihozdemir commented on packages/mantine/src/components/crud/edit/index.tsx
> +            <>{breadcrumb}</> ?? undefined
```suggestion
            {breadcrumb}
```

2022-10-24 08:48 UTC, salihozdemir commented on packages/mantine/src/components/crud/list/index.tsx
> +            <>{breadcrumb}</> ?? undefined
```suggestion
            {breadcrumb}
```

2022-10-24 08:48 UTC, salihozdemir commented on packages/mantine/src/components/crud/show/index.tsx
> +            <>{breadcrumb}</> ?? undefined
```suggestion
            {breadcrumb}
```

2022-10-24 09:04 UTC, salihozdemir requested changes
Thank you four your effort 🙏🏻.
I leave some review comments if you can fix them, I'll merge this great PR 🚀

In addition, since the reviews I added are the same as the other parts you made changes, I did not write them one by one. 🤙🏻

2022-10-25 08:36 UTC, aliemir commented
Hey @TDP17 thanks for the PR and the latest changes. @salihozdemir dropped some minor change requests, can you check those? Looks like we can infer the type from the definition rather than stating it there. 

For the changesets, you can just run `npm run changeset` command to create one with the selected packages. We prefer separate changesets for every package but in this case we can just create two; one for the `refine-core` and the other is for UI packages. (You can mark those changes as `minor`) 

For more info on how to write descriptions for the changesets, you can check out previous PRs or the changelog for the releases 🚀 

(I prefer writing them inside the code editor by editing the markdown file created by the command rather than using command line) 

After these are done, we're ready for the merge and release 🚀 🚀

2022-10-25 11:21 UTC, omeraplak commented
> One small bug I ran into, running `npm run changeset` gives me the following error
> 
> ```
> 🦋  error Error: Failed to find where HEAD diverged from master. Does master exist?
> ```
> 
> I fixed this by changing `.changeset/config.json` > `"baseBranch": "master",` to ` "baseBranch": "next",` Should I add this fix in this PR itself? Or is it supposed to be this way?

You may be getting this error because the master branch is not in your local. You can ignore it

2022-10-25 11:46 UTC, aliemir commented on .changeset/afraid-dolphins-sing.md
> +```
```suggestion
```jsx
<Refine
    options= {{
        breadcrumb: false, // hide globally
    }}
/>
```
```

2022-10-25 11:46 UTC, aliemir commented on .changeset/afraid-dolphins-sing.md
> +}}
```suggestion
<Refine
    options= {{
        breadcrumb: <MyCustomBreadcrumbComponent /> // custom component
    }}
/>
```

2022-10-25 11:48 UTC, aliemir approved these changes
Thank you!

2022-10-25 12:05 UTC, omeraplak approved these changes

2022-10-25 12:21 UTC, merged