Add smooth scroll effect on icons
refinedev/refine pull request #2915
Opened 2022-10-27 17:48 UTC by AnshuPathak-88825

Pr for issue #2803

2022-10-28 07:15 UTC, alicanerdurmaz requested changes

2022-10-28 07:15 UTC, alicanerdurmaz commented on documentation/src/theme/Footer/Layout/index.js
> +                                        <GithubIcon className="w-[22px] h-[22px] hover:fill-[#171515] transition ease-in-out duration-500" />
```suggestion
                                        <GithubIcon className="w-[22px] h-[22px] hover:fill-[#171515] transition-colors ease-in-out duration-500" />
```

2022-10-28 07:24 UTC, alicanerdurmaz commented
Hi @AnshuPathak-88825 Thanks for the PR 🙏 

Commit message does not conform to semantic commit standards.
Can you change commit message according to [Semantic Commit Messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716).

For example:
feat(docs): add smooth scroll effect on icons

2022-10-28 16:07 UTC, AnshuPathak-88825 commented
done require changes

2022-10-29 11:45 UTC, alicanerdurmaz requested changes

2022-10-29 11:45 UTC, alicanerdurmaz commented on documentation/src/theme/Footer/Layout/index.js
> +                                        <LinkedinIcon className="w-[22px] h-[22px] hover:fill-[#0077B5] hover:fill-[#171515] transition-colors ease-in-out duration-500" />
```suggestion
                                        <LinkedinIcon className="w-[22px] h-[22px] hover:fill-[#0077B5]  transition-colors ease-in-out duration-500" />
```
Do we need this ?
It doesn't cause any problems on hover effect, but it is confusing

2022-10-29 14:38 UTC, AnshuPathak-88825 commented on documentation/src/theme/Footer/Layout/index.js
> +                                        <LinkedinIcon className="w-[22px] h-[22px] hover:fill-[#0077B5] hover:fill-[#171515] transition-colors ease-in-out duration-500" />
hover effect on icon isn't smooth that's why I made it smooth

2022-10-29 18:40 UTC, alicanerdurmaz commented on documentation/src/theme/Footer/Layout/index.js
> +                                        <LinkedinIcon className="w-[22px] h-[22px] hover:fill-[#0077B5] hover:fill-[#171515] transition-colors ease-in-out duration-500" />
Transitions are okay, Thank you. 🙏 

But icons have 2 hover class right now and one is ovveriding another. This is confusing.
We should use 1 hover class on html elements.

2022-10-29 18:50 UTC, AnshuPathak-88825 commented on documentation/src/theme/Footer/Layout/index.js
> +                                        <LinkedinIcon className="w-[22px] h-[22px] hover:fill-[#0077B5] hover:fill-[#171515] transition-colors ease-in-out duration-500" />
ok I'm doing it now

2022-10-29 19:01 UTC, AnshuPathak-88825 commented
@alicanerdurmaz pls review it again

2022-10-31 07:59 UTC, alicanerdurmaz approved these changes

2022-10-31 08:00 UTC, merged