[FEAT]: prepopulate initialValues in searchFormProps when syncWithLocation is true
refinedev/refine pull request #2988
Opened 2022-11-11 03:22 UTC by leapful

**Explain the details for making this change. What existing problem does the pull request solve?**

When setting syncWithLocation to true for useTable from Antd, the initialValues in searchFormProps is empty.

initialValues in searchFormProps should be automatically populated when syncWithLocation is true

### Test plan (required)

1. Access Fine Foods example url at:

`https://example.admin.refine.dev/orders?pageSize=10&current=1&filters[0][field]=q&filters[0][operator]=eq&filters[0][value]=test&filters[1][field]=store.id&filters[1][operator]=eq&filters[1][value]=1&filters[2][field]=user.id&filters[2][operator]=eq&filters[2][value]=7&filters[3][field]=status.text&filters[3][operator]=in&filters[3][value][0]=Pending&filters[4][field]=createdAt&filters[4][operator]=gte&filters[4][value]=2022-11-29T17:00:00.000Z&filters[5][field]=createdAt&filters[5][operator]=lte&filters[5][value]=2022-12-27T16:59:59.999Z`

2. Check that all query parameters are filled on "Filters" menu

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2022-11-11 09:38 UTC, alicanerdurmaz requested changes

2022-11-11 09:38 UTC, alicanerdurmaz commented on examples/fineFoods/admin/antd/src/pages/orders/list.tsx
> +                        name="status.text"
```suggestion
                        name="status"
```
This is not working because `onSearch()` still uses `status`

```
export interface IOrderFilterVariables {
    q?: string;
    store?: string;
    user?: string;
    createdAt?: [Dayjs, Dayjs];
    status?: string;
}
```

```
filters.push({
                field: "status.text",
                operator: "in",
                value: status,
});
```

2022-11-12 04:08 UTC, leapful commented on examples/fineFoods/admin/antd/src/pages/orders/list.tsx
> +                        name="status.text"
@alicanerdurmaz

Is there any reason of using field name like "store", "user", "status" instead of the real name "store.id", "user.id", "status.text" beside just alias for easy name usage ?

The purpose of this PR is to avoid mapping for initial values when using form like the previous code handling here:

<img width="1072" alt="Screenshot 2022-11-12 at 10 57 49" src="https://user-images.githubusercontent.com/18494222/201456085-1c0d0b41-8bb1-4182-980a-f6be09d41fdc.png">

Reverting to field name "store", "user", "status" will bring back the mapping again and in terms of an example, it would be great to avoid confusion for developers by keep the default initial values (I've seen many cases that keep copy and paste the initial values mapping even that the field name is not nested field property).

In conclusion, just update "onSearch" callback is good enough:

```
onSearch: (params) => {

  filters.push({ field: 'status.text', value: params['status.text']  })
}

```

2022-11-14 11:21 UTC, alicanerdurmaz commented on examples/fineFoods/admin/antd/src/pages/orders/list.tsx
> +                        name="status.text"
Hi again @leapful, Sorry for late response.
Did you test the app with these code ? It's not filtering.

Because incoming params values are these.
`{
    "status.text": [
        "Ready"
    ],
    "store.id": 2,
    "user.id": 1
}`

But you are are trying to push with value `user` not `user.id`;
```
filters.push({
                field: "user.id",
                operator: "eq",
                value: user,
            });
```

by the way, if you wan to change variable name, you need to update [interface IOrderFilterVariables](https://github.com/refinedev/refine/blob/next/examples/fineFoods/admin/antd/src/interfaces/index.d.ts) too.

2022-11-14 11:33 UTC, alicanerdurmaz commented on examples/fineFoods/admin/antd/src/pages/orders/list.tsx
> +                        name="status.text"
yes this works. but you need to update the interface as well.

`onSearch: (params) => {
  filters.push({ field: 'status.text', value: params['status.text']  })
}
`

2022-11-14 13:14 UTC, leapful commented on examples/fineFoods/admin/antd/src/pages/orders/list.tsx
> +                        name="status.text"
@alicanerdurmaz 

Thanks for your review. I've pushed the change and already tested successfully in local development. Please help to review it again.

2022-11-14 13:16 UTC, leapful commented on examples/fineFoods/admin/antd/src/pages/orders/list.tsx
> +                        name="user.id"
Resolved as it was updated after discussion.

2022-11-14 13:16 UTC, leapful commented on examples/fineFoods/admin/antd/src/pages/orders/list.tsx
> +                        name="store.id"
Resolved as it was updated after discussion.

2022-11-15 07:37 UTC, alicanerdurmaz commented
Hi @leapful Thank you for your great work.

We discuss with the core team and we noticed this feature can cause breaking changes.
And supporting this feature from `core` can cause too many edge cases.

Thank you again.

2022-11-15 07:37 UTC, closed without merging