docs: new tutorials
refinedev/refine pull request #3292
Opened 2022-12-21 12:51 UTC by aliemir

We're updating our documentation and the tutorials to have a better flow about **refine** and want our users to construct a solid foundation with following the tutorials. 

The new tutorial will consist of multiple units, each teaching beginner to advanced concepts about the topics they cover and won't be UI framework specific as much as possible.

_This is the base branch for the new tutorials._

2022-12-21 17:59 UTC, necatiozmen requested changes

2022-12-21 17:59 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +**refine** is React-based framework. So, if you have some preliminary knowledge of React, then this tutorial is perfect for you! Just by following the directions provided, you'll be able to finish it
We can mentioned that something like refine coded using Typescript @salihozdemir 
I think we can also remove "**refine** is for everyone! 🎉" since it's a very identical phrase with the Astro docs..

2022-12-21 17:59 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +You can leave feedback about this tutorial by clicking the `Give us feedback` button at the bottom of the tutorial tracker. You can also find us on [Discord](#).
You can also reach us on [Discord](discord.gg/refine)

2022-12-21 17:59 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +A clickable task checklist awaits you at the end of each page to measure your understanding of the content. Check these items off to see your progress in the Tutorial Tracker.
this can be deleted since it's duplicated

2022-12-21 17:59 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
>  In order to publish and deploy your project, you'll also need a GitHub (or a similar platform) account.
We can just say GitHub.

2022-12-22 06:43 UTC, salihozdemir commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +**refine** is React-based framework. So, if you have some preliminary knowledge of React, then this tutorial is perfect for you! Just by following the directions provided, you'll be able to finish it
Yes refine coded with Typescript but it is not required for the refine apps. At this section, mentioned for the using refine prerequisites. So I thought that just React knowledge was enough. @necatiozmen

2022-12-22 07:09 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/2-select-framework.md
> +**refine** is a headless framework. It means you can build your app without any UI frameworks or something else. However, **refine** provides ready-to-use UI framework packages for you. You can use t
```suggestion
**refine** is a headless framework. It means you can build your app without any UI frameworks. However, **refine** has built-in support for the most popular UI frameworks like Material UI, Ant Design, Mantine, and Chakra UI. You can speed up your app UI development with these powerful frameworks.
```

2022-12-22 07:09 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/2-select-framework.md
> +After this step, the tutorial will proceed according to your choice. You can choose one of the following UI frameworks:
```suggestion
After this step, the tutorial will proceed according to your UI framework choice. You can choose one of the following UI frameworks or just go with the headless UI option:
```

2022-12-22 07:13 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/0-intro.md
> +
Here we can add something like with different words
Want a preview of what you’re going to build? You can view the final project on [GitHub] or [StackBlitz]

2022-12-22 07:16 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +**refine** is React-based framework. So, if you have some preliminary knowledge of React, then this tutorial is perfect for you! Just by following the directions provided, you'll be able to finish it
You are write we don't need to say "refine coded with Typescript" but we'll adding and using interfaces  during the tutorial. So it will be good say something like "basic Typescript knowledge is good have."

2022-12-22 13:56 UTC, necatiozmen approved these changes

2023-01-04 19:38 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +
In the context of a CRUD  application, a resource typically refers to a data entity that can be created, read, updated, or deleted. For example, a resource could be a user account, a blog post, a product in an online store, or any other piece of data that can be managed by the CRUD app.  
Maybe its better if we put general explanation of what does "resource" mean. @salihozdemir

2023-01-04 19:45 UTC, necatiozmen requested changes

2023-01-04 19:45 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +To add `resource` to our app, we must use `resources` prop of `<Refine />` component. This prop accepts an array of objects. Each object represents a resource.
```suggestion
To add  a `resource` to our app, we need use `resources` prop of `<Refine />` component. This prop accepts an array of objects. Each object represents a resource.
```

2023-01-04 19:45 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +In the above example, we have added a `resource` with name `posts`. This resource has 5 pages. `list`, `show`, `create`, `clone` and `edit` pages and **refine** link the pages with routes for us. We
```suggestion
In the above example, we have added a `resource` with name `posts`. This resource will have 5 pages that assigned to `list`, `show`, `create`, `clone` and `edit`  properties. **refine** link the pages with routes for us. We can access these pages by visiting the following routes:
```

2023-01-09 14:03 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +
I think in the resources unit, it would be nice if we can talk about <Refine> component in thr App.tsx a little bit. Maybe something like, it's heart of the refine apps, dataproviders, router providers and other important features need to register here.
Maybe giving link to the <Refine> property docs..
@salihozdemir

2023-01-09 14:03 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +
Dİd we put general explanation for "resource" term? @salihozdemir

2023-01-10 11:03 UTC, omeraplak requested changes

2023-01-10 11:03 UTC, omeraplak commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +-   Intercom – if you have any questions, you can ask them directly from the page you are on.
```suggestion
```

2023-01-10 11:03 UTC, omeraplak commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +(This data is only saved to your browser’s local storage, and is not available elsewhere. No data is sent to, nor stored by **refine**.)
```suggestion
(This data is only saved to your browser’s local storage, and is not available elsewhere. No data is sent to, not stored by **refine**.)
```

2023-01-10 11:03 UTC, omeraplak commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +You can leave feedback about this tutorial by clicking the `Give us feedback` button at the bottom of the tutorial tracker.
```
import { FeedbackFish } from '@feedback-fish/react'

const App = () => {
  // Get your projectId from your dashboard at feedback.fish/app
  return (
    <FeedbackFish projectId="866e0ba7ed4f2e">
      <NavButton>Send feedback</NavButton>
    </FeedbackFish>
  )
}
```

2023-01-12 14:33 UTC, necatiozmen requested changes

2023-01-12 14:33 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +Bulk actions are actions that can be performed on multiple items at once. Performing bulk actions is a common pattern in admin panels. If your api supports bulk actions, you can implement them in you
```suggestion
Bulk actions are actions that can be performed on multiple items at once. Performing bulk actions is a common pattern in admin panels. If your API supports bulk actions, you can implement them in your data provider.
```

2023-01-12 14:33 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +The `getMany` method gets the records with the `resource` and `ids` methods. Implementation of this method is optional. If you don't implement it, refine will use `getOne` method to handle multiple r
```suggestion
The `getMany` method gets the records with the `resource` and `ids` parameters. Implementation of this method is optional. If you don't implement it, refine will use `getOne` method to handle multiple requests.
```

2023-01-12 14:33 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +The `getMany` method gets the records with the `resource` and `ids` methods. Implementation of this method is optional. If you don't implement it, refine will use `getOne` method to handle multiple r
You give internal link to `getOne` keyword in this doc. Please implement it to other bulk actions methods @yildirayunlu

2023-01-12 14:33 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +In the above example, we have added a `resource` with name `products`. This resource will have 5 pages that assigned to `list`, `show`, `create`, and `edit` properties. **refine** link the pages with
```suggestion
In the above example, we have added a `resource` with name `products`. This resource will have 5 pages that assigned to `list`, `show`, `create`, and `edit` properties. **refine** link the pages with routes for us.  

When we define `create`, clone page will be generated automatically. We can access these pages by visiting the following routes:
```

2023-01-12 14:33 UTC, necatiozmen commented on documentation/docs/tutorial/4-adding-crud-pages/antd/add-create-page.md
> +
`<br/>`
`<br/>`

2023-01-12 14:33 UTC, necatiozmen commented on documentation/docs/tutorial/4-adding-crud-pages/antd/add-edit-page.md
> +In the edit page, we may need to select a record from another resource. For example, we may need to select a category from the `categories` resource to assign the product to the category. In this cas
```suggestion

In the edit page, we may need to select a record from another resource.  

For example, we may need to select a category from the `categories` resource to assign the product to the category. In this case, we can use the `useSelect` hook provided by **refine**. This hook fetches the data by passing the params to the `dataProvider`'s `getList` method. Then, it returns the necessary props for the `<Select/>` component.
```

2023-01-12 14:33 UTC, necatiozmen commented on documentation/docs/tutorial/4-adding-crud-pages/antd/add-show-page.md
> +In the show page, we have a single record. The record may have relationships with other resources. For example, the `products` resource has a relationship with the `categories` resource. In this case
```suggestion
In the show page, we have a single record. The record may have relationships with other resources.  

For example, the `products` resource has a relationship with the `categories` resource. In this case, we can use the `useOne` hook provided by **refine**. This hook allows us to fetch single record data by using the `id` and `resource` parameters.
```

2023-01-12 14:33 UTC, necatiozmen commented on documentation/docs/tutorial/4-adding-crud-pages/chakra-ui/add-create-page.md
> +
adding create page de Next diyince tekrar adding show page e gidiyor @salihozdemir

2023-01-12 14:35 UTC, necatiozmen commented
![Screen Shot 2023-01-12 at 15 33 57](https://user-images.githubusercontent.com/18739364/212094415-549200f9-a844-46e4-8106-61814d5c9f69.png)

Headless buttonların arası mesafe da bu şekilde gözüküyor. @aliemir

2023-01-13 09:03 UTC, salihozdemir commented on documentation/docs/tutorial/1-getting-started/0-intro.md
> +If you’d like to deploy to Netlify, skip to [Deploy your app to the web](/docs/tutorial/getting-started/deploy-project/). Otherwise, skip to [Generate CRUD pages automatically with Inferencer](/docs/
Above the "Create a GitHub Repository" title, we mentioned about publish your Stackblitz project on Github. After, in this section we explained user can deploy their projects by using the Github.  So, yes user can deploy the boilerplate.

2023-01-13 11:47 UTC, merged

2023-01-13 11:47 UTC, necatiozmen approved these changes