docs: add new tutorial unit one
refinedev/refine pull request #3298
Opened 2022-12-21 14:58 UTC by salihozdemir

Added new tutorial page's unit one

2022-12-22 07:12 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/0-intro.md
> +Now that you know what you’re going to build, let’s set up all the tools you’ll need!
Let's change the sentence a little bit to make it have different looking from astr doc..

2022-12-22 07:52 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/0-intro.md
> +
At this point we can add something like this:
https://docs.astro.build/en/tutorial/1-setup/#where-are-we-going

2022-12-22 13:55 UTC, necatiozmen approved these changes

2022-12-23 09:38 UTC, necatiozmen requested changes

2022-12-23 09:38 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/0-intro.md
> +As you work on your project, you will periodically commit your changes to GitHub. Netlify will use the files in your GitHub repository to build and publish your website on the internet at a unique ad
This sentence almost same with the ast. doc. Need to refactor..

2022-12-23 09:38 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/0-intro.md
> +Netlify will continuously monitor your GitHub repository for any committed changes, and will automatically rebuild and republish your site to reflect those changes. This allows you to easily update a
This sentence almost same with the ast. doc. Need to refactor..

2022-12-23 09:38 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/2-create-project.md
> +3- The `-o refine-antd` flag in the command above tells the CLI to install the project with the `refine-antd` preset. This preset selects some options for you in accordance with this tutorial.
```suggestion
3- We are using `-o refine-antd` flag to bootstrap the app with pre-selected CLI options. The tutorial will proceed according to these selections. 
```

2022-12-23 09:38 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/2-create-project.md
> +4- The CLI will ask if you agree to share your selection anonymously with the **refine** team. You can choose whatever you prefer.
```suggestion
4-The CLI will ask if you agree to share your choices anonymously with the **refine** team. This is for measuring community preferences. You are free to share or not.
```

2022-12-23 09:38 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/2-create-project.md
> +Your project files contain all the code you need to run your website. To see a preview of your website in the browser:
```suggestion
Your project files contain all the code you need to run your app. To see a preview of your app in the browser:
```

2022-12-23 09:38 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/2-create-project.md
> +Your project files contain all the code you need to run your website. To see a preview of your website in the browser:
Maybe it's better to use "app" instead of website?

2022-12-23 11:50 UTC, omeraplak approved these changes

2022-12-23 11:50 UTC, omeraplak commented on documentation/docs/tutorial/1-getting-started/antd/2-create-project.md
> +# create a new project with npm
```suggestion
```
We can delete this comment

2022-12-25 09:25 UTC, necatiozmen requested changes

2022-12-25 09:25 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +
It'll be nice if you can mention that the app consumes https://api.fake-rest.refine.dev and so by using inferencer generated code you can now list, edit, create the records on the api. Also mention we'll see how refine communicates with the API in the data provider section..

2022-12-25 09:25 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/2-create-project.md
> +
Here you can explain something like, why is the welcome page is rendered and what we'll do in the next section to make app interactive.

2022-12-25 09:41 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +
Here we can add section like 
### How to activate(use) Inferencer
Here you show registering Inferencer components to the `<Refine>` component like we did in [how to use Inferencer with Ant Design](/docs/api-reference/antd/components/inferencer/)

2022-12-26 06:43 UTC, salihozdemir commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +
@omeraplak said the inferencer will come directly added. What do @omeraplak think about?

2022-12-26 06:45 UTC, omeraplak commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +
ahh my fault :( Necati is right ⚡️

2022-12-27 08:43 UTC, necatiozmen requested changes

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +The `@pankod/refine-inferencer` package includes the `<AntdInferencer />` component, which can be imported from `@pankod/refine-inferencer/antd` and used to generate CRUD pages with Ant Design compon
```suggestion
The `@pankod/refine-inferencer` package provides the `<AntdInferencer />` component, which can be imported from `@pankod/refine-inferencer/antd` and used to generate CRUD pages based on your API response with Ant Design components.
```

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +In [Unit 4](/docs/tutorial/understanding-resources/index), resource concepts will be explained in detail. For now, you can think of a resource as a collection of data that you want to manage in your
```suggestion
In [Unit 4](/docs/tutorial/understanding-resources/index), the resources concept will be explained in detail. For now, you can assume that the resource is a collection of data from your API used in the app.
```

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +The component can be used directly in the `resources` prop of the `<Refine />` component in `App.tsx` as shown below:
```suggestion
The `<AntdInferencer />` component is used by passing to appropriate values in the `resources` prop of the `<Refine />` component in `App.tsx` as shown below:
```

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +The component can be used directly in the `resources` prop of the `<Refine />` component in `App.tsx` as shown below:
```suggestion
The `<AntdInferencer />` component is used by passing to appropriate values in the `resources` prop of the `<Refine />` component in `App.tsx` as shown below:
```

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +
```suggestion
At this point, refine will auto-generate the CRUD pages based on the API response on the fly
```

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +Now that you have created your project, let's take a look at the CRUD pages that Inferencer has generated for us.
```suggestion
So far we have added complete CRUD pages by utilizing Inferencer feature to the project. Let's take a look at the auto-generated CRUD pages that Inferencer handles for us.
```

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +## Preview the generated pages
```suggestion
## Preview the auto-generated pages
```

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +Before we start, let's understand the API that we will be using in this tutorial. We will be using the [JSONPlaceholder](https://jsonplaceholder.typicode.com/) API, which is a created by **refine** t
```suggestion
Before we start, let's understand the API that we will be using in this tutorial. We will be using the [JSONPlaceholder](https://jsonplaceholder.typicode.com/) API, which is created by **refine** team to provide a fake REST API for testing purposes. 
 
 You can check out the **refine** fake REST API: https://api.fake-rest.refine.dev
```

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +
By clicking to "Show Code" button in the live previews below, you can view the auto-generated codes by Inferencer.

2022-12-27 08:43 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +```
At the end of the Inferencer section, you can say something like, we'll implement the auto generated page codes to our app in the next sections..

2022-12-27 08:52 UTC, necatiozmen requested changes

2022-12-27 08:52 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/5-deploy-project.md
> +3- At the final step, Netlify will display your app's site settings. The defaults should be correct for your Astro project, so you can scroll down and click "Deploy site".
```suggestion
3- At the final step, Netlify will display your app's site settings. The defaults should be correct for your refine project, so you can scroll down and click "Deploy site".
```

2022-12-27 08:52 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/5-deploy-project.md
>  https://docs.astro.build/en/tutorial/1-setup/5/
```suggestion

```

2022-12-27 08:52 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/5-deploy-project.md
>  https://docs.astro.build/en/tutorial/1-setup/5/
```suggestion

```

2022-12-27 08:52 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/5-deploy-project.md
> +3- At the final step, Netlify will display your app's site settings. The defaults should be correct for your Astro project, so you can scroll down and click "Deploy site".
Be careful when taking inspiration sentences from ast. docs. Make it different as much as you can. Google can take it as duplicate content and it's bad for SEO performance

2022-12-28 08:40 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +When using the **refine** hooks and components in the created pages, the `name` property of the `resource` will be passed to the `dataProvider` functions, by default.
What is happening when the resource is passed to dataProvider functions? Maybe you can give an explanation like In that way...

2022-12-28 08:40 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +In the above example, we have added a `resource` with name `posts`. This resource has 5 pages. `list`, `show`, `create`, `clone` and `edit` pages and **refine** creates these pages for us. We can acc
Should we say "**refine** creates these pages for us." or something like  "**refine** link the pages with routes for us.". 
I'm not sure..

2022-12-28 08:47 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +When using the **refine** hooks and components in the created pages, the `name` property of the `resource` will be passed to the `dataProvider` functions, by default.
Also you can mention, we ll discuss dataprovider concepts in the nexts section and give a link

2022-12-28 08:49 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +
Maybe we can give an explanation of like "What does resource mean in development terms"

2022-12-29 10:12 UTC, salihozdemir commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +When using the **refine** hooks and components in the created pages, the `name` property of the `resource` will be passed to the `dataProvider` functions, by default.
Actually, the previous section describes the `dataProvider` so still I should the explanation for that? Because, I'm not sure. @necatiozmen

2022-12-29 10:42 UTC, salihozdemir commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +
I've replaced the sentence with `Let's see what's going on under the hood when we add a `resources` to our app and learn `resources` term for who are new to **refine**.`

Is it good? @necatiozmen

2022-12-29 17:09 UTC, necatiozmen commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +When using the **refine** hooks and components in the created pages, the `name` property of the `resource` will be passed to the `dataProvider` functions, by default.
Yes you are right. No we don't need

2022-12-29 17:10 UTC, necatiozmen approved these changes

2023-01-02 11:49 UTC, merged