docs: add `dataProvider` section on new tutorial
refinedev/refine pull request #3305
Opened 2022-12-22 12:24 UTC by yildirayunlu

Add `dataProvider` section on new tutorial.

2022-12-23 12:33 UTC, necatiozmen requested changes

2022-12-23 12:33 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +When it needs to communicate with the *refine* API, it does so using the `dataProvider` object. All API requests are processed through this object.
```suggestion
The data provider concept comes into play whenever your refine app needs to communicate with an external API. Thanks to refine's `dataProvider` object property,  all API requests are processed through this object.
```

2022-12-23 12:33 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +
You need to connect this section to the previous one.Readers have seen the App.tsx and the `dataProvider` property in the previous section. This is where we need to explain   <Refine> components(in App.tsx)  `dataProvider` property to the users.

2022-12-25 08:54 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +## Using with DataProvider
This section should explain the What is swizzle, why we need it and why we are we using very clearly.

2022-12-27 10:08 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +The [`swizzle`](../../packages/documentation/cli.md#swizzle) that comes with [`refine-cli`](../../packages/documentation/cli.md) allows you to customize the supported components and use them as your
```suggestion
The [`swizzle`](../../packages/documentation/cli.md#swizzle) that comes with [`refine-cli`](../../packages/documentation/cli.md) allows you to customize the supported components and use them as your own. For data providers, this is a very useful tool.
```

2022-12-27 10:27 UTC, necatiozmen requested changes

2022-12-27 10:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +The [`swizzle`](../../packages/documentation/cli.md#swizzle) that comes with [`refine-cli`](../../packages/documentation/cli.md) allows you to customize the supported components and use them as your
The swizzle is a "refine-cli" command used for customizing some of the supported built-in "refine" packages and components. Thanks to the swizzle feature you don't have to stick to what "refine" offers by default, you have the freedom to customize "refine" packages and components according to our development needs.


In this section, we'll take advantage of "swizzle" feature to inspect "refine's built-in rest data provider" files and how to customize..

2022-12-27 10:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +Let's swizzle `dataProvider` as an example.
Since this step is continuation of the app we built in the previous section, we need to navigate user on that manner.
So, navigate them with something like, remember we use rest api data provider on <Refine> component in "App.tsx".  Now we'll inspect how the dataprovider look like..

2022-12-27 10:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
At this point we have the data provider files. So what's then?  
You need to tell where this files exported , how can they view.. Navigate them.
You can mention like, now you free to customize existing rest data provider according to your need or just leave it as is

2022-12-27 10:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +Let's swizzle `dataProvider` as an example.
You can tell more about swizzle

2022-12-27 10:35 UTC, necatiozmen commented
Before create your own data provider, we'll have additonal section 
3.2 refine's supported data providers. I forgot the add unit files.

2022-12-27 10:39 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +In some cases, data providers do not fully comply with our API and it is necessary to change it. The [`swizzle`](../../packages/documentation/cli.md#swizzle) in [`refine-cli`](../../packages/document
```suggestion
In some cases, refine's built-in data providers are not fully complying with our API needs and you may want to edit the existing data provider logic.. The [`swizzle`](../../packages/documentation/cli.md#swizzle) command feature in [`refine-cli`](../../packages/documentation/cli.md) can be use for that. It can quickly eject and update all data provider files.
```

2023-01-04 09:46 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +The data provider concept comes into play whenever your refine app needs to communicate with an external API. Thanks to refine's `dataProvider` object property, all API requests are processed through
We can move this sentence to line 18

2023-01-04 09:46 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +
You need to say something like: In ht background refine's useList hook uses getList from dataProvider..

2023-01-04 09:46 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +**refine** data hooks are used to fetch data from the data provider. It passed paramters to the data provider and returns the result.
```suggestion
**refine** data hooks are used to fetch data from the API using the data provider methods. It passes parameters to the data provider and returns the result.
```

2023-01-04 09:50 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +import { DataProvider } from "@pankod/refine-core";
Where do you use this import?

2023-01-04 09:50 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +
You can add something like: refine uses this method internally to perform CRUD operations..

2023-01-04 10:17 UTC, necatiozmen requested changes

2023-01-04 10:17 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +API usage and standards are very different, so data providers may not be suitable for you.
```suggestion
The standards and usage of APIs can vary significantly, so it is possible that refine's built-in data providers may not be suitable for your needs.
```

2023-01-04 10:17 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +Now let's prepare a data provider that communicates with a REST API. We preferred `axios` as a client.
```suggestion
Let's now create a data provider that communicates with a REST API. We preferred `axios` as a client.
```

2023-01-04 10:17 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +Let's start by creating a file like the one below. We will add other methods step by step.
```suggestion
We will begin by creating a file, as shown below, and we will add additional methods to it as we proceed.
```

2023-01-04 10:17 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +We create an `axiosInstance`, define an `interceptors` to handle an error and export it. Write this in a `utility` file.
```suggestion
In a `utility` file, create an `axiosInstance` and define an `interceptor` to handle errors. Then export it.
```

2023-01-04 10:39 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +## Methods
Under the Methods heading explain that What are you going to implement in this section.

Now we'll add....

2023-01-04 10:39 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +1. `resource` params implements the resource name. In our case, it is `posts`.
So what does this method do? It's gets the data and return json you shown above? Give an explanation please

2023-01-04 10:44 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +The `create` method creates a new record with the `resource` and `variables` methods.
```suggestion
The `create` method creates a new record with the `resource` and `variables` parameters.
```

2023-01-04 10:44 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +The `update` method updates the record with the `resource`, `id` and `variables` methods.
```suggestion
The `update` method updates the record with the `resource`, `id` and `variables` parameters.
```

2023-01-04 13:22 UTC, yildirayunlu commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +import { DataProvider } from "@pankod/refine-core";
Use `dataProvider` return type. `const dataProvider: DataProvider = {`

2023-01-04 13:37 UTC, omeraplak approved these changes

2023-01-04 13:37 UTC, omeraplak commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +| Name      | Type         | Default |
Can we use docgen for the properties table? @aliemir @alicanerdurmaz

2023-01-05 06:39 UTC, necatiozmen requested changes

2023-01-05 07:50 UTC, necatiozmen requested changes

2023-01-05 07:50 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +The DataProvider unit is optional for the tutorial and can be skipped if desired.
```suggestion
The DataProvider unit is optional for the tutorial and can be skipped to next unit [Adding CRUD Pages](#) if desired.
```

2023-01-05 07:50 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +Go to the next unit [Adding CRUD Pages](#) to continue.
```suggestion

```

2023-01-05 09:29 UTC, necatiozmen requested changes

2023-01-05 09:29 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +Data Provider must have the following methods:
```suggestion
The typical data provider has following methods:
```

2023-01-05 09:29 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +
You don't need worry about creating data providers from scratch . refine offers built-in data provider support for the most popular API providers(link to supported data providers). So you can use one of them or you can create your own data provider according to your needs. We 'll see how to create data provider in the next sections.

2023-01-05 09:29 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +
You can explain that how to use these data providers. like you can install afterwards or selecting when bootstrapping a project with cli...

2023-01-05 14:03 UTC, yildirayunlu commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +The dataProvider acts as a data layer for your app that makes the HTTP requests and encapsulates how the data is retrieved. **refine** consumes these methods via data hooks.
Data Provider methods

2023-01-09 08:39 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +You can review the[list of supported providers](#supported-data-providers) to find the one that is compatible with your API.
```suggestion
You can review the [list of supported providers](#supported-data-providers) to find the one that is compatible with your API. 
```

2023-01-09 08:39 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +As we can see, the parameters passed to useList hook are forwarded to the data providers getList method internally. In the background, refine connects all data provider methods to appropriate data ho
```suggestion
As we can see, the parameters passed to the `useList` hook are forwarded to the data provider's `getList` method internally. In the background, **refine** connects all data provider methods to appropriate data hooks.
```

2023-01-09 08:39 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +We use refine's data hooks whenever we need to fetch data from the API. These data hooks are connected to data provider methods internally. The required parameters passes to the data provider methods
```suggestion
We use **refine's** data hooks whenever we need to fetch data from the API. These data hooks are connected to data provider methods internally. The required parameters passes to the data provider methods and response from API returning back.
```

2023-01-09 08:39 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +The [`swizzle`](../../packages/documentation/cli.md#swizzle) is command in [`refine-cli`](../../packages/documentation/cli.md) that allows you to customize the supported components and dataProviders.
```suggestion
The [`swizzle`](../../packages/documentation/cli.md#swizzle) is a command in [`refine-cli`](../../packages/documentation/cli.md) that allows you to customize the supported components and data providers. It allows you to eject selected files from the package. Instead of starting from scratch, you can use the file as a starting point and make changes to fit your specific needs.
```

2023-01-09 08:39 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +The standards and usage of APIs can vary significantly, so it is possible that refine's built-in data providers may not be suitable for your needs.
```suggestion
The standards and usage of APIs can vary significantly, so it is possible that **refine's** built-in data providers may not be suitable for your needs.
```

2023-01-09 13:27 UTC, necatiozmen requested changes

2023-01-09 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +We use **refine's** data hooks whenever we need to fetch data from the API. These data hooks are connected to data provider methods internally. The required parameters passes to the data provider met
```suggestion
We use **refine's** data hooks whenever we need to fetch data from the API. These data hooks are connected to data provider methods internally. The required parameters passes to the data provider methods and response from API returning back.  

```

2023-01-09 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +To illustrate this internal connection, imagine we want to get all records from the "post" resource using refine's `useList` data hook.
```suggestion
To illustrate this internal connection, imagine we want to get all records from the `post` resource using refine's `useList` data hook.
```

2023-01-09 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +**refine** comes with many pre-loaded data providers. To include them in your project, you can use `npm install [packageName]` or you can use the `npm create refine-app@latest projectName` to configu
```suggestion
**refine** comes with many pre-loaded data providers. To include them in your project, you can use `npm install [packageName]` or you can select preferred data provider with the `npm create refine-app@latest projectName` during the project creation phase with CLI.  
 This will allow you to easily use these data providers in your project.
```

2023-01-09 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +The [`swizzle`](../../packages/documentation/cli.md#swizzle) is a command in [`refine-cli`](../../packages/documentation/cli.md) that allows you to customize the supported components and data provide
```suggestion
The [`swizzle`](../../packages/documentation/cli.md#swizzle) is a command in [`refine-cli`](../../packages/documentation/cli.md) that allows you to customize the supported components and data providers. It allows you to eject selected files from the refine packages. Instead of starting from scratch, you can use the file as a starting point and make changes to fit your specific needs.
```

2023-01-09 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +Using `axios` as our HTTP client will allow us to make efficient and reliable HTTP requests to our server. Interceptors provide several benefits, such as centralized error handling, the ability to mo
```suggestion
Using `axios` as our HTTP client will allow us to make efficient and reliable HTTP requests to our server. Interceptors provide several benefits, such as centralized error handling, the ability to modify request or response data, and the ability to show global loading indicators.  
To get started, let's go ahead and install `axios` in our project.
```

2023-01-09 13:58 UTC, yildirayunlu commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +## Using Data Providers in refine
`You can refer to the refine component [dataProvider](http://localhost:3000/docs/api-reference/core/components/refine-config/#dataprovider) prop documentation for more detailed information.` We've added this, any idea what else we can do? @necatiozmen

2023-01-10 09:03 UTC, necatiozmen requested changes

2023-01-10 09:03 UTC, necatiozmen commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +Sometimes you may want to send a custom parameter to APIs, for example a custom header parameter. You can use `metaData` for this. The sent parameter can be accessed directly from the data provider.
```suggestion
When using APIs, you may wish to include custom parameters, such as a custom header. To accomplish this, you can utilize the `metaData` field, which allows the sent parameter to be easily accessed by the data provider.```

2023-01-10 09:56 UTC, merged