feat(docs): add core useForm documentation
refinedev/refine pull request #3317
Opened 2022-12-26 13:04 UTC by alicanerdurmaz

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2022-12-26 14:35 UTC, salihozdemir commented
When I'm reviewing your doc, I saw that:

"If you're looking for a complete form library, Refine supports two form libraries out-of-the-box."

It must be "..., **refine** supports three form ..."

I've created comment because your changes not cover it 😅

2023-01-02 06:47 UTC, omeraplak requested changes

2023-01-02 06:47 UTC, omeraplak commented on documentation/docs/api-reference/core/hooks/useForm.md
> +-   on `edit` mode: `"list`", `"many"` and `"detail"`
```suggestion
-   on `create` or `clone` mode: `"list"`, and `"many"`
-   on `edit` mode: `"list"`, `"many"`, and `"detail"`
```

2023-01-02 06:47 UTC, omeraplak commented on documentation/docs/api-reference/core/hooks/useForm.md
> +If there is more than one dataProvider, you should use the dataProviderName that you will use.
```suggestion
If there is more than one dataProvider, you should use the `dataProviderName` that you will use.
```

2023-01-02 06:47 UTC, omeraplak commented on documentation/docs/api-reference/core/hooks/useForm.md
> +```tsx live tailwind url=http://localhost:3000 previewHeight=420px
```suggestion
```tsx live tailwind url=http://localhost:3000/posts/create previewHeight=420px
```

2023-01-02 06:47 UTC, omeraplak commented on documentation/docs/api-reference/core/hooks/useForm.md
> +```tsx live tailwind url=http://localhost:3000 previewHeight=420px
```suggestion
```tsx live tailwind url=http://localhost:3000/posts/edit/123 previewHeight=420px
```

2023-01-02 06:47 UTC, omeraplak commented on documentation/docs/api-reference/core/hooks/useForm.md
> +```tsx live tailwind url=http://localhost:3000 previewHeight=420px
```suggestion
```tsx live tailwind url=http://localhost:3000/posts/edit/123 previewHeight=420px
```

2023-01-05 08:38 UTC, omeraplak approved these changes

2023-01-05 12:08 UTC, merged