Add Pixels Admin
refinedev/refine pull request #3389
Opened 2023-01-13 07:18 UTC by anewman15

Add new app: Pixels Admin to main repo

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-01-24 07:26 UTC, aliemir commented on examples/pixels-admin/src/providers/authProvider.ts
> +        }
Do we have a security rule defined in our tables (such as users) in supabase side? Or are we just doing this control for auth? @anewman15

2023-01-24 09:45 UTC, anewman15 commented on examples/pixels-admin/src/providers/authProvider.ts
> +        }
None yet. I'm trying to set RLS and define a rule, but it looks like it is not possible to set rules on `auth.users` table. Do you have any resource I can look at ?

TY

2023-01-31 10:36 UTC, omeraplak requested changes

2023-01-31 10:36 UTC, omeraplak commented on examples/pixels-admin/package.json
> +    "casbin": "^5.19.3",
```suggestion
    "casbin": "^5.15.2",
```

2023-01-31 11:36 UTC, merged