docs: add tutorial unit 6 which contains auth provider
refinedev/refine pull request #3405
Opened 2023-01-16 14:26 UTC by salihozdemir

Documentation for new tutorial. The PR is related to Unit 6 which contains Auth Provider.

2023-01-19 08:10 UTC, alicanerdurmaz approved these changes

2023-01-19 11:26 UTC, aliemir approved these changes

2023-01-19 14:02 UTC, yildirayunlu approved these changes

2023-01-20 06:32 UTC, omeraplak requested changes

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +    confirmPassword: string;
```suggestion
    foo: string;
```

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +`checkAuth` method is used to check if the user is authenticated. Internally, it is called when the user navigates to a page that requires authentication.
and it is called page loads

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +-   If the Promise rejects, the user is not authenticated and pages that require authentication will not be accessible.
We should mention that when Promise.reject is returned, we redirect the user to the "/login" route and can be overridden.

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +The `<Authenticated>` component makes use of the `useAuthenticated` hook. It allows you to render components only if the user is authenticated. You can see how to use the `useAuthenticated` hook in t
We can avoid sharing the source code link because the file path may change in the future and we may forget to update it.

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +    console.log("User has admin permission");
```suggestion
    console.log("User has admin permissions");
```

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +Invoking the `useGetIdentity` hook will call the `getUserIdentity` method. If `getUserIdentity` method resolves a data, it will be available in the `useIdentity` hook's `data` property.
Depending on the UI framework used, we can say that when "name" and "avatar" return, we show them in the header.

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +const { data } = useIdentity();
```suggestion
import { useGetIdentity } from "@pankod/refine-core";

const { data } = useGetIdentity();
```

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +-   If the Promise rejects, the user is not authenticated and pages that require authentication will not be accessible.
are you sure?

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +Invoking the `useUpdatePassword` hook's mutation will call the `updatePassword` method, passing in the mutation's parameters as arguments. Additionally, the `updatePassword` method will take query pa
Can we explain with an example?

2023-01-20 06:32 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/headless/2-auth-pages.md
> +3. Run the app and navigate to the `/login` page.
Can we show with what parameters the login method of AuthProvider is called?

2023-01-20 06:58 UTC, salihozdemir commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +`checkAuth` method is used to check if the user is authenticated. Internally, it is called when the user navigates to a page that requires authentication.
Isn't it the same as navigating?

2023-01-20 07:03 UTC, salihozdemir commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +-   If the Promise rejects, the user is not authenticated and pages that require authentication will not be accessible.
Actually, `useAuthenticated` hook won't redirect to anywhere when the return Promise.reject. If user want to redirect the user specific page, I mention about it in below collapsable area.

2023-01-20 07:06 UTC, salihozdemir commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +    console.log("User has admin permission");
I think, it seems true, isn't it?

2023-01-20 07:21 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +-   If the Promise rejects, the user is not authenticated and pages that require authentication will not be accessible.
https://github.com/refinedev/refine/blob/next/packages/react-router-v6/src/routeProvider.tsx#L183

if checkAuth returns promise.reject the user is indirectly redirected to "/login"

maybe it can be mentioned like a tip or info box

2023-01-20 07:24 UTC, salihozdemir commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +-   If the Promise rejects, the user is not authenticated and pages that require authentication will not be accessible.
I'm not sure 😅, I'll update it.

2023-01-20 07:24 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +    console.log("User has admin permission");
I've always seen the use of plural

2023-01-20 07:26 UTC, salihozdemir commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +Invoking the `useUpdatePassword` hook's mutation will call the `updatePassword` method, passing in the mutation's parameters as arguments. Additionally, the `updatePassword` method will take query pa
Below, I show it with example. Can you check out it?

2023-01-20 07:28 UTC, salihozdemir commented on documentation/docs/tutorial/5-understanding-authprovider/headless/2-auth-pages.md
> +3. Run the app and navigate to the `/login` page.
I mentioned about it above. Can you checkout it in `Login Page` title?

2023-01-20 07:43 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/headless/2-auth-pages.md
> +3. Run the app and navigate to the `/login` page.
yes but it needs to be shown more clearly

2023-01-20 07:52 UTC, salihozdemir commented on documentation/docs/tutorial/5-understanding-authprovider/headless/2-auth-pages.md
> +3. Run the app and navigate to the `/login` page.
I thought about it too, but we already shown an general example in first section. After we gave an example for all methods and hooks in the second section. So, I am not sure there is any need to explain again in the third part? Although we explain again with text, but we do not show code. What do you think in this context? 😅

2023-01-20 08:07 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/headless/2-auth-pages.md
> +3. Run the app and navigate to the `/login` page.
AuthPage remains a bit of magic for users. We could add it to AuthPage docs. It would be nice to have a way to see what the component is calling without "debugging" it.

2023-01-20 08:11 UTC, omeraplak commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +Invoking the `useUpdatePassword` hook's mutation will call the `updatePassword` method, passing in the mutation's parameters as arguments. Additionally, the `updatePassword` method will take query pa
I'm talking about somehow explaining that you pass query parameters with an example.

2023-01-20 08:13 UTC, yildirayunlu reviewed
No link for the next section in the `updatePassord` section.

<img width="1076" alt="resim" src="https://user-images.githubusercontent.com/3484713/213647404-f1b66bc5-46bb-43ef-a539-f476e78a217e.png">

2023-01-20 08:14 UTC, yildirayunlu approved these changes

2023-01-23 11:27 UTC, necatiozmen approved these changes

2023-01-23 14:36 UTC, omeraplak approved these changes

2023-01-24 07:15 UTC, merged