docs(data-provider): update data provider doc
refinedev/refine pull request #3509
Opened 2023-02-02 05:58 UTC by alicanerdurmaz

2023-02-02 14:40 UTC, salihozdemir approved these changes

2023-02-02 14:40 UTC, salihozdemir commented on documentation/docs/api-reference/core/providers/data-provider.md
> +Data hooks use [TanStack Query](https://tanstack.com/query) to manage data fetching. React Query handles important concerns like caching, invalidation, loading states, etc.
```suggestion
Data hooks use [TanStack Query](https://tanstack.com/query) to manage data fetching. It handles important concerns like caching, invalidation, loading states, etc.
```

2023-02-02 14:40 UTC, salihozdemir commented on documentation/docs/api-reference/core/providers/data-provider.md
> +useTable<IPost>({
```suggestion
```tsx
useTable({
```

2023-02-02 14:40 UTC, salihozdemir commented on documentation/docs/api-reference/core/providers/data-provider.md
> +};
```suggestion
```tsx
        <Refine
            dataProvider={{
                default: defaultDataProvider,
                example: exampleDataProvider,
            }}
            resources={[
                {
                    // Refine will use the `default` data provider for this resource
                    name: "posts",
                },
                {
                    name: "products",
                    options: {
                        // Refine will use the `exampleDataProvider` data provider for this resource
                        dataProviderName: "exampleDataProvider",
                    },
                },
            ]}
        />
```

2023-02-02 14:40 UTC, salihozdemir commented on documentation/docs/api-reference/core/providers/data-provider.md
> +:::caution
I think, this caution no to be in here. Maybe we don't need it. We can describe it without caution.

2023-02-03 06:09 UTC, omeraplak requested changes

2023-02-03 06:09 UTC, omeraplak commented on documentation/docs/api-reference/core/providers/data-provider.md
> +                    // Refine will use the `default` data provider for this resource
```suggestion
                    // refine will use the `default` data provider for this resource
```

2023-02-03 06:09 UTC, omeraplak commented on documentation/docs/api-reference/core/providers/data-provider.md
> +                        // Refine will use the `exampleDataProvider` data provider for this resource
```suggestion
                        // refine will use the `exampleDataProvider` data provider for this resource
```

2023-02-03 08:13 UTC, alicanerdurmaz commented on documentation/docs/api-reference/core/providers/data-provider.md
> +:::info
```suggestion
:::info-tip
```

2023-02-06 08:00 UTC, aliemir commented on documentation/docs/api-reference/core/providers/data-provider.md
> +-   **Using `dataProviderName` prop in the data hooks **and all **data-related** components/**functions.**
```suggestion
-   **Using `dataProviderName` prop in the data hooks and all data-related components/functions.**
```

2023-02-06 08:01 UTC, aliemir approved these changes

2023-02-06 08:31 UTC, merged