docs: tutorial, unit3, p3 - Fix indentation, code contexts and syntax
refinedev/refine pull request #3532
Opened 2023-02-03 14:24 UTC by ngouy

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

 doc "fix"" so not sure an issue is useful

Please provide enough information so that others can review your pull request:

Context:
- Some code is out of context (example: [here](https://refine.dev/docs/tutorial/understanding-dataprovider/create-dataprovider/#getlist:~:text=...%0A%5D-,In%20the%20first%20step,-%2C%20we%27ll%20return%20the))
Some is in context (example [here](Now let's get the metaData parameter from the data provider.))
Which is way easier, especially at the beginning (like the `getList` example) to know where to put things.

- some code have syntax errors. (example [here](https://refine.dev/docs/tutorial/understanding-dataprovider/create-dataprovider/#getlist:~:text=getMany%3A%20async%20(%7B%20resource%2C%20ids%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20const%20%7B%20data%20%7D%20%3D%20await%20axiosInstance.get(%0A%20%20%20%20%20%20%20%20%60%24%7BapiUrl%7D/%24%7Bresource%7D%3F%24%7Bstringify(%7B%20id%3A%20ids%20%7D)%7D%60%2C%0A%20%20%20%20)%3B%0A%0A%20%20%20%20return%20%7B%0A%20%20%20%20%20%20%20%20data%2C%0A%20%20%20%20%7D%3B%0A%7D%3B))
The last `;` is in reality a `,`. But because the code was not in the proper context, it's not obvious.

- the code blocs example indentation is not always the same. Sometime 2, sometimes 4

Explain the **details** for making this change. What existing problem does the pull request solve?

- [x] put every data provider method in its context
- [x] replace faulty `;` by `,`
- [x] always use 4 spaces indentations (for code example, json blocks TODO)
> I've used 4 spaces indentation because it seems the norm for the refine codebase

### Test plan (required)

__none__

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-02-03 14:32 UTC, omeraplak approved these changes

2023-02-03 14:34 UTC, ngouy commented
also nice doc. Best tutorial docs i've used in a while
thanks for this incredible work 🙏

2023-02-03 14:35 UTC, omeraplak commented
Hey @ngouy ,
Thank you very much for your effort to beautify refine. We will probably merge it on Monday! Have a good weekend.

2023-02-03 14:41 UTC, omeraplak commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +    export const dataProvider = (apiUrl: string): DataProvider => ({
```suggestion
    import { DataProvider } from "@pankod/refine-core";
 
    export const dataProvider = (apiUrl: string): DataProvider => ({
```
Do we need to explicitly show the import of the DataProvider type?

2023-02-03 14:48 UTC, ngouy commented
_edit_

Given the generated files are in indent 2 spaces, I will go to indent with 2 spaces everywhere

2023-02-03 15:17 UTC, ngouy commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +    export const dataProvider = (apiUrl: string): DataProvider => ({
we do but it's already done here

https://github.com/refinedev/refine/pull/3532/files#diff-636ab32cba5e0f41add2e965f30f781596050249e5db08fe4243cb3452c4f44cR53

2023-02-03 15:21 UTC, ngouy commented
another edit: fix stringify usage

2023-02-06 05:31 UTC, alicanerdurmaz requested changes

2023-02-06 05:31 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +const { stringify } = queryString;import { stringify } from "query-string";
```suggestion
import { stringify } from "query-string";
```

I guess some typo happened here.

2023-02-06 05:34 UTC, alicanerdurmaz requested changes

2023-02-06 05:34 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +import queryString from "query-string";
```suggestion
import { stringify } from "query-string";
```

this is working in our code base. Why do we need to change this?

2023-02-06 14:27 UTC, ngouy commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +const { stringify } = queryString;import { stringify } from "query-string";
woops

2023-02-06 14:36 UTC, ngouy commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +import queryString from "query-string";
curious on where it works

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/12391171/216998442-f6c16a59-3f5f-4bfa-977a-7b932007bc63.png">


On the generated data provider one, that's how it's done:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/12391171/216998594-ea60f961-3b0e-4dcc-96ae-293de5696a30.png">


_edit_

Ok found the "issue" on why i have an error on my end
If I follow the tutorial 💯 
My installed version of query-string is 8.1.x
On your code, the used version of @pankod/refine-simple-rest is 7.1.x

Not sure what's the fix here

I will rollback to the old export (that's not working on a fresh tutorial due to version bump) because I don't want to address that in this PR

2023-02-06 14:37 UTC, ngouy commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +import queryString from "query-string";
a fix could be to import it from "pankod/refine-simple-rest" instead of query-string directly

2023-02-07 06:43 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +import queryString from "query-string";
Thank you for clear explanation 🙏

2023-02-07 06:48 UTC, alicanerdurmaz requested changes

2023-02-07 06:48 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +    AxiosInstance.defaults.headers = {
```suggestion
    axiosInstance.defaults.headers = {
```

its should be lowercase "a"

2023-02-07 06:50 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +import queryString from "query-string";
then I think it should be like this

```tsx
import queryString from "query-string";
const { stringify } = queryString
```

2023-02-07 13:28 UTC, ngouy commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +import queryString from "query-string";
@alicanerdurmaz is that ok if we leave that for another PR?

I feel like the dependency diff thing could be worth digging into a little bit

2023-02-07 13:47 UTC, alicanerdurmaz approved these changes

2023-02-07 13:48 UTC, alicanerdurmaz commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +import queryString from "query-string";
Thanks for improving **refine** documentation 🙏

2023-02-07 13:59 UTC, ngouy commented on documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
> +import queryString from "query-string";
Here is the issue I've created

https://github.com/refinedev/refine/issues/3555

2023-02-08 09:26 UTC, merged