docs(can-access): update can access doc
refinedev/refine pull request #3549
Opened 2023-02-07 08:41 UTC by alicanerdurmaz

added: https://refine.dev/docs/api-reference/core/components/accessControl/can-access/

2023-02-07 13:30 UTC, omeraplak requested changes

2023-02-07 13:30 UTC, omeraplak commented on documentation/docs/api-reference/core/components/accessControl/canAccess.md
> +-   `false`, it renders [`fallback`](#fallback) prop if provided. Otherwise, it renders `null` page.
```suggestion
-   `false`, it renders [`fallback`](#fallback) prop if provided. Otherwise, it renders `null`.
```

2023-02-07 13:30 UTC, omeraplak commented on documentation/docs/api-reference/core/components/accessControl/canAccess.md
> +</CanAccess>;
```suggestion
 </CanAccess>
```
indent

2023-02-07 13:51 UTC, salihozdemir approved these changes

2023-02-08 08:47 UTC, yildirayunlu approved these changes

2023-02-08 12:04 UTC, aliemir approved these changes

2023-02-08 12:05 UTC, merged