feat(core): add generic to option label-value on use select
refinedev/refine pull request #3571
Opened 2023-02-08 15:00 UTC by alicanerdurmaz

added: `hasPagination` default value set to `false` on `useSelect`.

### Closing issues

`closes #3569 ` 

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-02-09 08:04 UTC, salihozdemir approved these changes

2023-02-09 10:27 UTC, yildirayunlu approved these changes

2023-02-10 11:02 UTC, omeraplak commented on .changeset/swift-cycles-marry.md
> +"@pankod/refine-core": major
```suggestion
"@pankod/refine-core": minor
```

2023-02-10 11:41 UTC, omeraplak requested changes

2023-02-10 11:41 UTC, omeraplak commented on documentation/docs/api-reference/mantine/hooks/useSelect/index.md
> +/>;
```suggestion
/>
```

2023-02-13 04:57 UTC, aliemir approved these changes

2023-02-13 04:58 UTC, merged