feat(v4): add new binding types (#3561)
refinedev/refine pull request #3580
Opened 2023-02-10 06:04 UTC by alicanerdurmaz

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-02-10 11:11 UTC, omeraplak approved these changes

2023-02-13 04:59 UTC, aliemir approved these changes

2023-02-13 05:00 UTC, aliemir commented
Let's revert the changes in `/examples` so we can test out the codemods later 🤔

2023-02-13 05:58 UTC, aliemir requested changes
Let's revert the changes in `/examples` so we can test out the codemods later 🤔

2023-02-13 07:42 UTC, aliemir approved these changes

2023-02-13 08:07 UTC, merged