feat: pagination mode
refinedev/refine pull request #3602
Opened 2023-02-13 14:56 UTC by salihozdemir

Added "server", "client", and "off" mode to `useTable` hooks for pagination.

### Test plan (required)

Not completed, yet.

### Closing issues

close #3601

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-02-15 05:46 UTC, omeraplak requested changes

2023-02-15 05:46 UTC, omeraplak commented on packages/antd/src/hooks/list/useSimpleList/useSimpleList.ts
> +    setSorter: useTableReturnType<TData>["setSorter"];
```suggestion
    sorters?: CrudSorting;
    setSorters: useTableReturnType<TData>["setSorter"];
```
like `filters` and `setFilters`?

2023-02-22 06:48 UTC, aliemir approved these changes

2023-02-23 11:34 UTC, yildirayunlu approved these changes

2023-02-23 13:40 UTC, BatuhanW commented on packages/airtable/src/index.ts
> +            const generetedSort = generateSort(sorters) || [];
```suggestion
            const generatedSort = generateSort(sorters) || [];
```

2023-02-23 13:40 UTC, BatuhanW commented on documentation/docs/api-reference/antd/hooks/table/useTable.md
> +If you want to handle the pagination on client-side, you can pass the `pagination.mode` prop to the `useTable` hook and set it to `"client"`.
Should it be "off"?

2023-02-23 13:40 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/useTable/index.md
> +`useTable` has a pagination feature. The pagination is done by using the `current` and `pageSize` props of `pagination`. The `current` is the current page and the `pageSize` is the number of records
```suggestion
`useTable` has a pagination feature. The pagination is done by passing `current` and `pageSize` keys to `pagination` object. The `current` is the current page and the `pageSize` is the number of records per page.
```

2023-02-23 13:40 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/useTable/index.md
> +If you want to handle the pagination on client-side, you can pass the `pagination.mode` prop to the `useTable` hook and set it to `"client"`.
Should it be "off"?

2023-02-23 14:30 UTC, salihozdemir commented on documentation/docs/api-reference/antd/hooks/table/useTable.md
> +If you want to handle the pagination on client-side, you can pass the `pagination.mode` prop to the `useTable` hook and set it to `"client"`.
If the user defines "off", pagination will be disabled. However, you're right because users don't handle the pagination our `useTable` hook handles the pagination. I'll update it 🤙🏻

2023-02-23 14:40 UTC, salihozdemir commented on documentation/docs/api-reference/antd/hooks/table/useTable.md
> +If you want to handle the pagination on client-side, you can pass the `pagination.mode` prop to the `useTable` hook and set it to `"client"`.
By default, pagination happens on the server side. If you want to do pagination handling on the client side, you can pass the `pagination.mode` property and set it to `"client"`. Also, you can disable the pagination by setting the `"off"`.

@BatuhanW Is it good?

2023-02-23 15:07 UTC, omeraplak commented on .changeset/great-cooks-sell.md
> +- Added default values for `pagination.current` and `pagination.pageSize` properties of `useList` hook.
Can we share default values?

2023-02-24 07:01 UTC, merged