feat: remove `Ant Design` exports items for `@pankod/refine-antd`
refinedev/refine pull request #3603
Opened 2023-02-13 14:58 UTC by yildirayunlu

Remove `Ant Design` exports items for `@pankod/refine-antd`

2023-02-14 11:26 UTC, aliemir commented on packages/codemod/src/definitions/export.ts
> +    AntdListProps: "ListProps",
We should convert the `AntdBreadcrumb` import like;

```tsx
import { Breadcrumb as AntdBreadcrumb } from "antd";
```

to not break the existing users 😅

2023-02-14 12:03 UTC, alicanerdurmaz requested changes

2023-02-14 12:03 UTC, alicanerdurmaz commented on packages/codemod/src/helpers/separateImports.ts
> +            if (imports.includes(item.local.name)) {
```suggestion
			if (imports.includes(item.local.name) || imports.includes(item.imported.name))
```

I believe we should support "as" imports too.
https://astexplorer.net/#/gist/95a3a6e7f8c49482c38066554efb0702/1c5b31e6344cf56ec0c07afabd93979906e4fc11

2023-02-14 12:09 UTC, alicanerdurmaz commented
Should we delete the import declaration when there are no imports left?

https://astexplorer.net/#/gist/dd4022a4e79f2f123ca71fa697351e9e/c96dd2c7bd2f5b6ca0f7b36be9eda8f80e1f3a15

Before 
```ts
import { Modal } from "@pankod/refine-antd";
```

after
```ts
import "@pankod/refine-antd";
import { Modal } from "antd";
```

2023-02-15 05:42 UTC, omeraplak commented on packages/inferencer/src/inferencers/antd/code-viewer.tsx
> +import { Icons } from "@pankod/refine-antd";
Could we have talked about removing Icon exports from our antd package? @aliemir @yildiray @BatuhanW

2023-02-17 15:56 UTC, aliemir approved these changes

2023-02-20 12:47 UTC, alicanerdurmaz approved these changes

2023-02-21 11:42 UTC, merged