feat(v4-core): deprecate `authProvider`, implement new one
refinedev/refine pull request #3650
Opened 2023-02-23 06:42 UTC by alicanerdurmaz

This is a simple change but we're thinking it will make it our `AuthProvider` interface nicer if we rename `checkAuth` to `check` and `checkError` to `onError` since its invoked when there is an error in API calls. Also might be nicer to rename `getUserIdentity` to `getIdentity` for consistency.

- Rename `checkAuth` to `check` and `checkError` to `onError` in `AuthProvider` interface.

- Rename `getUserIdentity` to `getIdentity` in `AuthProvider` interface.

- Update the internal logic to respect the changes.

- Update docs to reflect the changes.

- Update examples to reflect the changes.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-02-23 10:47 UTC, BatuhanW commented on packages/core/src/hooks/auth/useGetIdentity/index.ts
> +export function useGetIdentity<TData = any>({
Why did we change this to function?

2023-02-23 10:58 UTC, alicanerdurmaz commented on packages/core/src/contexts/auth/index.tsx
> +        queryClient.invalidateQueries(["getUserIdentity"]);
with new `AuthBindings`, `getUserIdentity ` renamed to `getIdentity`.
I forgot to update query key. I will 👍

2023-02-23 11:06 UTC, alicanerdurmaz commented on packages/core/src/hooks/auth/useGetIdentity/index.ts
> +export function useGetIdentity<TData = any>({
Does function overloading work with function expressions? I changed it because as far as I know it doesn't work

2023-02-23 11:07 UTC, alicanerdurmaz commented on packages/core/src/contexts/auth/index.tsx
> + * @deprecated `AuthContext` is deprecated with refine@4, use `AuthBindingsContext` instead, however, we still support `AuthBindingsContext` for backward compatibility.
typo 👍

2023-02-23 11:40 UTC, omeraplak commented on packages/antd/src/components/layout/sider/index.tsx
> +            onClick={() => mutateLogout({ redirectPath: "/login" })}
This approach seems too strict. Why are we passing this in Sider?

2023-02-23 11:41 UTC, BatuhanW requested changes

2023-02-23 11:41 UTC, BatuhanW commented on examples/auth-antd/src/pages/dashboard.tsx
> +        legacy: true,
Since legacy isn't clear, let's make it something like `v3LegacyAuthProviderCompatible`, which is explicit and annoying. Encourages users to move to the new version.

2023-02-23 11:46 UTC, alicanerdurmaz commented on packages/antd/src/components/layout/sider/index.tsx
> +            onClick={() => mutateLogout({ redirectPath: "/login" })}
v3 `useLogout` have default `redirectPath` to `"/login"` v4 hasn't. 
I added to support the same logic for both data providers.

If we don't give default value, I think `<Sider>` users will confuse when updated to new auth provider.

2023-02-23 11:59 UTC, salihozdemir commented on packages/core/src/components/containers/refine/index.tsx
> +     * @deprecated `legacyAuthProvider` is deprecated with refine@4, use `authProvider` instead, however, we still support `legacyAuthProvider` for backward compatibility.
```suggestion
     * @deprecated `legacyAuthProvider` is deprecated with refine@4, use `authProvider` instead.
```

2023-02-23 12:13 UTC, salihozdemir commented on packages/core/src/hooks/auditLog/useLog/index.ts
> +        legacy: Boolean(authProvider?.isLegacy),
When `authProvider` is `undefined`, `legacy` will be `false`. Will this cause any problems anywhere?

2023-02-23 12:21 UTC, alicanerdurmaz commented on packages/core/src/hooks/auditLog/useLog/index.ts
> +        legacy: Boolean(authProvider?.isLegacy),
It will be the same result as using the auth hook without `authProvider`

2023-02-24 11:25 UTC, BatuhanW approved these changes

2023-02-24 14:03 UTC, aliemir approved these changes

2023-02-24 14:03 UTC, merged