feat(examples): Migrate examples to new auth provider
refinedev/refine pull request #3660
Opened 2023-02-27 05:47 UTC by alicanerdurmaz

Examples migrated to new auth provider

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-02-27 06:08 UTC, omeraplak commented on examples/antd-audit-log/src/App.tsx
> +        console.log("worked");
```suggestion
```

2023-03-02 09:33 UTC, BatuhanW commented on examples/antd-audit-log/src/App.tsx
> +                redirectTo: "/login",
Should we redirect here?

2023-03-02 09:33 UTC, BatuhanW commented on examples/antd-audit-log/src/App.tsx
> +                    redirectTo: "/login",
Do we need `logout: true` here?

2023-03-02 10:03 UTC, salihozdemir commented on examples/data-provider-supabase/src/App.tsx
> +            error: new Error("Login failed"),
```suggestion
            error: new Error("Register failed"),
```

2023-03-02 10:39 UTC, alicanerdurmaz commented on examples/antd-audit-log/src/App.tsx
> +                redirectTo: "/login",
yes

2023-03-02 10:41 UTC, alicanerdurmaz commented on examples/antd-audit-log/src/App.tsx
> +                    redirectTo: "/login",
I guess yes, depends on the backend tho. I will add `logout: true`

2023-03-03 08:09 UTC, salihozdemir requested changes

2023-03-03 08:09 UTC, salihozdemir commented on examples/with-storybook-mui/src/authProvider.ts
> +    getPermissions: async () => null,
The other methods are not updated in this example. Can you update them?

2023-03-03 08:09 UTC, salihozdemir commented on examples/with-custom-pages/src/App.tsx
> +                  }),
```suggestion
                ? {
                      authenticated: true,
                  }
                : {
                      authenticated: false,
                      redirectTo: "/login",
                  },
```

2023-03-03 08:38 UTC, alicanerdurmaz commented on examples/mern-dashboard-client/src/App.tsx
> +        getPermissions: async () => null,
This example from youtube video. should we change that ?

2023-03-03 08:40 UTC, alicanerdurmaz commented on examples/mern-dashboard-client/src/App.tsx
> +        getPermissions: async () => null,
This example from youtube video. should we change that ?

2023-03-03 08:42 UTC, salihozdemir commented on examples/mern-dashboard-client/src/App.tsx
> +        getPermissions: async () => null,
Oh, sorry I missed it. No need, I marked resolve 👌

2023-03-03 08:47 UTC, salihozdemir approved these changes

2023-03-03 09:34 UTC, aliemir approved these changes

2023-03-03 09:43 UTC, salihozdemir approved these changes

2023-03-03 09:43 UTC, merged