feat(v4-docs): update auth provider docs
refinedev/refine pull request #3666
Opened 2023-02-27 11:58 UTC by alicanerdurmaz

WIP

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-02-28 08:42 UTC, alicanerdurmaz commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
>          if (user) {
```suggestion
        if (!user) {
```

2023-02-28 21:18 UTC, aliemir commented on documentation/docs/api-reference/core/components/auth/authenticated.md
> +It internally uses [`useIsAuthenticated`][use-is-authenticated]'s return values (`isSuccess`, `isLoading`, and, `isError`) to provide its functionality.
Not applicable to the current interface of the `authProvider`. `data` is used mainly for the functionality.

2023-03-02 11:41 UTC, BatuhanW requested changes

2023-03-02 11:41 UTC, BatuhanW commented on documentation/docs/advanced-tutorials/auth/auth0.md
> +    const authProvider: AuthBindings = {
Should we also update import above, from AuthProvider to AuthBindings?

2023-03-02 11:41 UTC, BatuhanW commented on documentation/docs/advanced-tutorials/custom-pages.md
> +const authProvider: AuthBindings = {
Same here, I think we should update import above. Right now AFAIK, AuthBindings isn't imported.

2023-03-02 11:41 UTC, BatuhanW commented on documentation/docs/advanced-tutorials/data-provider/appwrite.md
> +const authProvider: AuthBindings = {
Same here, let's check ad make sure we import AuthBindings.

2023-03-02 11:41 UTC, BatuhanW commented on documentation/docs/advanced-tutorials/data-provider/supabase.md
>  const authProvider: AuthProvider = {
Should we change this to AuthBindings?

2023-03-02 11:41 UTC, BatuhanW commented on documentation/docs/advanced-tutorials/multi-tenancy/strapi.md
>  export const authProvider: AuthProvider = {
Let's check this line as well.

2023-03-02 11:41 UTC, BatuhanW commented on documentation/docs/api-reference/antd/components/auth-page.md
> +            status: true,
Shouldn't it be `success`?

2023-03-02 11:51 UTC, alicanerdurmaz commented on documentation/docs/api-reference/antd/components/auth-page.md
> +            status: true,
yes

2023-03-03 09:02 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/auth/useForgotPassword.md
> +const authProvider: AuthBindings = {
Let's add import statement.

2023-03-03 09:48 UTC, aliemir commented on documentation/docs/api-reference/core/providers/auth-provider.md
> +import { AuthBindings } from "@pankod/refine-core";
```suggestion
import type { AuthBindings } from "@pankod/refine-core";
```

2023-03-03 09:49 UTC, aliemir commented on documentation/docs/api-reference/core/providers/auth-provider.md
> +| Property                                          | Description                               | Resolve condition                     |
```suggestion
| Property                                          | Description                               | Success condition                     |
```

or smt similar but `resolve condition` is not working for the current status of auth provider

2023-03-03 09:49 UTC, aliemir commented on documentation/docs/api-reference/core/providers/auth-provider.md
> +```
```suggestion
```

2023-03-03 09:53 UTC, aliemir commented on documentation/docs/api-reference/core/components/auth/authenticated.md
> +-   `data.error` is `true`, it renders [`fallback`](#fallback) prop if provided. Otherwise, it redirects to `data.redirectTo` page.
Not true, the code is changed in the source code. `data.error` is a complementary property, has no effect on `Authenticated` directly. 

`fallback` is rendered when `data.authentication` is set to `false`.

2023-03-03 09:55 UTC, aliemir commented on documentation/docs/api-reference/core/components/auth/authenticated.md
>  | loading  | Component to render while checking whether user is logged in                                              | `ReactNode` |         |
PropsTable is repeated, one auto and one hand written tables are visible.

2023-03-03 09:56 UTC, aliemir commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +    import { AuthBindings } from "@pankod/refine-core";
```suggestion
    import type { AuthBindings } from "@pankod/refine-core";
```

2023-03-03 09:57 UTC, aliemir commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +**refine** automatically displays an error notification when the `login` method resolves the Promise with `success: false`. If you want to customize the error message, you can resolve the Promise wit
❤️

2023-03-03 11:54 UTC, aliemir approved these changes

2023-03-03 11:57 UTC, BatuhanW commented on documentation/docs/tutorial/5-understanding-authprovider/0-intro.md
> +    login: (params: any) => Promise.resolve(),
```suggestion
    async login: (params: any) => {},
```

2023-03-03 11:57 UTC, BatuhanW commented on documentation/docs/tutorial/5-understanding-authprovider/0-intro.md
> +    login: (params: any) => Promise.resolve(),
Let's update these methods, convert them to async and return nothing for mocks across documentation.

2023-03-03 11:57 UTC, BatuhanW commented on documentation/docs/api-reference/mui/components/auth-page.md
> +[check-auth]: /docs/api-reference/core/providers/auth-provider/#check-
Is this correct?

2023-03-03 11:57 UTC, BatuhanW commented on documentation/docs/api-reference/mantine/components/auth-page.md
> +        authenticated: window.__refineAuthStatus ? true : false,
Should we add optional redirects?

`redirectTo: window.__refineAuthStatus ? undefined : "/login",`

2023-03-03 11:57 UTC, BatuhanW commented on documentation/docs/api-reference/core/providers/auth-provider.md
> +`onError` method is called when you get an error response from the API. You can create your own business logic to handle the error such as refreshing the token, logging out the user, etc.
Maybe we can also mention sending some notification to the user. Something similar was asked on Discord recently.

2023-03-03 12:58 UTC, aliemir commented on documentation/docs/api-reference/mui/components/auth-page.md
> +[check-auth]: /docs/api-reference/core/providers/auth-provider/#check-
When there's an element next to the title (e.g. PropTag for required or deprecated statuses) Docusaurus fails to trim the slug and generates the id with `-` in the end.

2023-03-03 13:24 UTC, alicanerdurmaz commented on documentation/docs/api-reference/mantine/components/auth-page.md
> +        authenticated: window.__refineAuthStatus ? true : false,
yes

2023-03-03 14:36 UTC, aliemir approved these changes

2023-03-03 14:37 UTC, BatuhanW approved these changes

2023-03-03 14:40 UTC, BatuhanW approved these changes

2023-03-03 14:51 UTC, aliemir approved these changes

2023-03-03 14:54 UTC, aliemir approved these changes

2023-03-03 14:54 UTC, merged