docs: add migration guide about `3.x.x` to `4.x.x`
refinedev/refine pull request #3668
Opened 2023-02-27 14:57 UTC by salihozdemir

Added migration guide about `3.x.x` to `4.x.x`.

2023-02-28 06:08 UTC, omeraplak requested changes

2023-02-28 06:08 UTC, omeraplak commented on documentation/docs/migration-guide.md
> ++            mode,
```suggestion
+            mode: "off" | "server" | "client",
```

2023-02-28 06:08 UTC, omeraplak commented on documentation/docs/migration-guide.md
> +All **Ant Design** components re-exported from `@pankod/refine-antd` have been removed. You should import them from `antd` package directly.
Here, the user can be instructed to install the 'antd' package using npm, pnpm, or yarn.

2023-02-28 06:08 UTC, omeraplak commented on documentation/docs/migration-guide.md
> +`Icons` are also removed from `@pankod/refine-antd`. You should import them from `@ant-design/icons` directly.
Here, the user can be instructed to install the '@ant-design/icons' package using npm, pnpm, or yarn.

2023-02-28 06:08 UTC, omeraplak commented on documentation/docs/migration-guide.md
> +-   Now `useSimpleList` hook will not accept all of `<List>` component properties So, you can give their props to `<List>` component directly.
Could you give an example of the props we removed? You used to do it this way before, but now it's like this.

2023-02-28 06:08 UTC, omeraplak commented on documentation/docs/migration-guide.md
> +-   By default, pagination was disabled. If you want to enable pagination, you should set `pagination.mode` prop to `"server"`.
We can create a tip box here saying 'codemod can do this automatically'

2023-02-28 06:08 UTC, omeraplak commented on documentation/docs/migration-guide.md
> +### `useMenu` hook is deprecated
```suggestion
### `useMenu` hook is removed
```

2023-02-28 06:08 UTC, omeraplak commented on documentation/docs/migration-guide.md
> +`useMenu` hook is deprecated. It will be exported from `@pankod/refine-core` package.
```suggestion
`useMenu` hook is removed. It will be exported from `@pankod/refine-core` package.
```

2023-02-28 13:25 UTC, yildirayunlu commented on documentation/docs/migration-guide.md
> +And it's done. Now your project uses `refine@3.x.x`.
```suggestion
And it's done. Now your project uses `refine@4.x.x`.
```

2023-02-28 13:25 UTC, yildirayunlu commented on documentation/docs/migration-guide.md
> +
It will be difficult to do this manually. The `move-to-new-org` codemod is recommended.

2023-02-28 13:25 UTC, yildirayunlu commented on documentation/docs/migration-guide.md
> +
For those who prefer to do it manually, only codemod that makes these changes can be recommended. (antd, mui, mantine, chakra)

2023-02-28 19:59 UTC, BatuhanW requested changes

2023-02-28 19:59 UTC, BatuhanW commented on documentation/docs/migration-guide.md
> +`authProvider` methods now returns a resolved promise in all cases, with an object that contains a `success` key. The `success` key indicates whether the operation was successful or not, and an optio
```suggestion
`authProvider` methods now returns a resolved promise in all cases, with an object containing `success` key. The `success` key indicates whether the operation was successful or not, and an optional `error` key with `Error` object in case of a failure.
```

2023-02-28 19:59 UTC, BatuhanW commented on documentation/docs/migration-guide.md
> +Previously, the `authProvider` methods returned a resolved or rejected promise rather than a resolved promise with consistent return types. This behavior is not ideal since a rejected promise is typi
```suggestion
Previously, the `authProvider` methods were expected to be resolved on success and rejected on any failure. This behavior wasn't ideal since rejected promise is typically associated with an error or an exceptional case. Considering some expected errors like wrong email/password combination isn't a failure and needs to be propagated to the user, rejected promises caused confusion for developers and made it harder to debug real unexpected behaviors.
```

2023-02-28 19:59 UTC, BatuhanW commented on documentation/docs/migration-guide.md
> +Additionally, the auth hooks no longer have default redirection paths. This behavior could be confusing for developers who were not aware of it. By adding a `redirectTo` property to the `authProvider
```suggestion
Additionally, the auth hooks no longer have default redirection paths. This behavior could be confusing for developers who were not aware of it. By adding a `redirectTo` property to the `authProvider` methods' return object explicitly, developers can have more control over where the user is redirected after a successful operation.
```

2023-02-28 19:59 UTC, BatuhanW commented on documentation/docs/migration-guide.md
> +-   `getUserIdentity` method of the `authProvider` changed to `getIdentity`.
```suggestion
-   `authProvider`'s `getUserIdentity` method renamed to `getIdentity`.
```

2023-02-28 19:59 UTC, BatuhanW commented on documentation/docs/migration-guide.md
> +-   `login` method now requires that a promise be resolved instead of rejected, with a return type of `AuthActionResponse`
```suggestion
-   `login` method now requires promises to be resolved in all cases, with a return type of `AuthActionResponse`
```

2023-02-28 19:59 UTC, BatuhanW commented on documentation/docs/migration-guide.md
> +-   `login` method no longer rejects promises, you should resolve the promise with a `success` and an `error` value in case of login failure or success.
```suggestion
-   `login` method expects promises to be resolved in all cases. You should always resolve the promise with a `success` key and an additional `error` key in case of a failure.
```

2023-02-28 19:59 UTC, BatuhanW commented on documentation/docs/migration-guide.md
> +`getList` parameters still have `hasPagination`, `sort`, and `metaData` props. But they are deprecated. You can use them for now. But we recommend you to use `pagination.mode`, `sorters`, and `meta`
```suggestion
`getList` parameters will still have `hasPagination`, `sort`, and `metaData` props. But they are deprecated. You can use them with v4. But we recommend you to use `pagination.mode`, `sorters`, and `meta` props instead.
```

2023-03-02 08:49 UTC, merged

2023-03-02 09:26 UTC, BatuhanW commented on documentation/docs/migration-guide/auth-provider.md
> +Additionally, the auth hooks no longer have default redirection paths. This behavior could be confusing for developers who were not aware of it. By adding a `redirectTo` property to the `authProvider
Our motivation behind the changes to the authProvider prop in refine's v4 is to make it flexible and customizable enough to cover much more cases than before without going down the rabbit hole. 

We wanted to create a common interface for the authProvider methods to simplify the debugging and understanding of the authentication process.

 Previously, the authProvider methods were expected to be resolved on success and rejected on failure. This behavior was not ideal since a rejected promise is typically associated with an error or an exceptional case. Considering that some errors, like the wrong email and password combination, aren’t failures and need to be propagated to the user, rejected promises caused confusion for developers and made it harder to debug real unexpected behaviors. 
The authProvider methods now return a resolved promise with an object containing a success key in all cases. This success key indicates whether the operation was successful or not and contains an optional error key with an Error object in case of a failure. 

Additionally, the auth hooks no longer have default redirection paths. This behavior was confusing for developers who were not aware of it. By explicitly adding a redirectTo property to the authProvider methods' return object, developers can now have more control over where the user is redirected after a successful operation.