docs(v4): update changesets
refinedev/refine pull request #3688
Opened 2023-03-01 13:14 UTC by salihozdemir

Update changesets to make more clear.

2023-03-01 15:35 UTC, omeraplak commented on .changeset/early-bananas-reflect.md
> +-   `useUpdateMany`
```suggestion
-   [`useCreateMany`](https://refine.dev/docs/api-reference/core/hooks/data/useCreateMany/)
-   [`useDeleteMany`](https://refine.dev/docs/api-reference/core/hooks/data/useDeleteMany/)
-   [`useUpdateMany`](https://refine.dev/docs/api-reference/core/hooks/data/useUpdateMany/)
```

2023-03-02 09:19 UTC, BatuhanW requested changes

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/great-moose-jump.md
> +Used new props with deprecated props to ensure backward compatibility.
Let's be more explicit here. Which deprecated props changed to which props.

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/hip-waves-share.md
> +-   `sort` props of `useCheckboxGroup` hook is deprecated. Use `sorters` prop instead.
```suggestion
-   `useCheckboxGroup`'s `sort` prop is deprecated. Use `sorters` prop instead.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/hip-waves-share.md
> +-   `sort` props of `useSelect` hook is deprecated. Use `sorters` prop instead.
```suggestion
-   `useSelect`'s `sort` prop is deprecated. Use `sorters` prop instead.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/hip-waves-share.md
> +-   `sort` props of `useRadioGroup` hook is deprecated. Use `sorters` prop instead.
```suggestion
-   `useRadioGroup`'s `sort` prop is deprecated. Use `sorters` prop instead.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/hip-waves-share.md
> +-   `resourceName` props of `useImport` hook is deprecated. Use `resource` prop instead.
```suggestion
-   `useImport`'s `resourceName` prop is deprecated. Use `resource` prop instead.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/lazy-crews-poke.md
> +-   `initialCurrent` and `initialPageSize` props are deprecated. Use `pagination` prop instead. To ensure backward compatibility, `initialCurrent` and `initialPageSize` props work as before.
```suggestion
-   `initialCurrent` and `initialPageSize` props are now deprecated. Use `pagination` prop instead.
-   To ensure backward compatibility, `initialCurrent` and `initialPageSize` props will work as before.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/lazy-crews-poke.md
> +-   `hasPagination` prop is deprecated. Use `pagination.mode` instead. To ensure backward compatibility, `hasPagination` prop works as before.
```suggestion
-   `hasPagination` prop is now deprecated. Use `pagination.mode` instead.
-   To ensure backward compatibility, `hasPagination` prop will works as before.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/lazy-crews-poke.md
> +-   `initialSorter` and `permanentSorter` props are deprecated. Use `sorters.initial` and `sorters.permanent` instead. To ensure backward compatibility, `initialSorter` and `permanentSorter` props wo
```suggestion
-   `initialSorter` and `permanentSorter` props are now deprecated. Use `sorters.initial` and `sorters.permanent` instead.
-    To ensure backward compatibility, `initialSorter` and `permanentSorter` props will work as before.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/mean-kangaroos-press.md
> +New props are used instead of deprecated ones in the tests.
Let's mention which props are being used explicitly.

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/modern-socks-kiss.md
> +-   `sort` props of `useSelect` hook is deprecated. Use `sorters` prop instead.
```suggestion
-   `useSelect`'s `sort` prop is now deprecated. Use `sorters` prop instead.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/olive-ants-remain.md
> +`AuthProvider` deprecated and renamed to `LegacyAuthProvider` with refine@4. Component and functions are updated to support `LegacyAuthProvider`.
```suggestion
`AuthProvider` is renamed to `LegacyAuthProvider` with refine@4. Components and functions are updated to support `LegacyAuthProvider`.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/orange-tools-obey.md
> +-   `metaData` props is deprecated for all data provider methods. Use `meta` prop instead.
```suggestion
-   `metaData` prop is now deprecated for all data provider methods. Use `meta` prop instead.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/nasty-worms-drive.md
> +> You don't have to install all of packages. You can install only the packages that you use.
```suggestion
> You don't have to install all of these packages below. Only install the packages you use.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/orange-tools-obey.md
> +    If you provide `metaData` with **refine** hooks or components, the `meta` value will be same as your provided `metaData` value.
```suggestion
    For backward compatibility, we still support `metaData` prop with refine v4.
```

I'm not sure about this one, just a suggestion.

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/orange-tools-obey.md
> +    If you provide `sort`, `hasPagination` or `metaData` with **refine** hooks or components, the `sorters`, `pagination.mode` or `meta` value will be same as your provided prop value.
```suggestion
    For backward compatibility, we still support `sort`, `hasPagination` and `metaData` props with refine v4.
```

I'm not sure about this one, just a suggestion.

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/poor-kids-live.md
> +> You don't have to install all of packages. You can install only the packages that you use.
```suggestion
> You don't have to install all of these packages below. Only install the packages you use.
```

2023-03-02 09:19 UTC, BatuhanW commented on .changeset/slow-wasps-remain.md
> +-   `congig` prop of `useList` and `useInfiniteList` hooks are deprecated. Use `sorters`, `filters`, `pagination` and `hasPagination` props instead.
```suggestion
-   `useList` and `useInfiniteList`'s `congig` prop is now deprecated. Use `sorters`, `filters`, `pagination` and `hasPagination` props instead.
```

2023-03-03 06:52 UTC, alicanerdurmaz submitted a review, later dismissed

2023-03-03 07:54 UTC, yildirayunlu approved these changes

2023-03-03 10:26 UTC, BatuhanW requested changes

2023-03-03 10:26 UTC, BatuhanW commented on .changeset/strange-cats-sort.md
> +> You don't have to install all of packages. You can install only the packages that you use.
```suggestion
> You don't have to install all of these packages below. Only install the packages you use.
```

2023-03-03 10:26 UTC, BatuhanW commented on .changeset/strange-knives-end.md
> +-   `sort` prop of `useAutocomplete` hook is deprecated. Use `sorters` prop instead.
```suggestion
-   `useAutocomplete`'s sort prop is now deprecated. Use `sorters` prop instead.
```

2023-03-03 10:26 UTC, BatuhanW commented on .changeset/tidy-actors-grow.md
> +-   `hasPagination` prop is deprecated. Use `pagination.mode` instead. To ensure backward compatibility, `hasPagination` prop works as before.
```suggestion
-   `hasPagination` prop is now deprecated. Use `pagination.mode` instead.
-   To ensure backward compatibility, `hasPagination` prop will work as before.
```

2023-03-03 11:41 UTC, BatuhanW requested changes

2023-03-03 11:41 UTC, BatuhanW commented on .changeset/great-cooks-sell.md
> +-   To ensure backward compatibility, `hasPagination` prop works as before.
Please, let's review **all** sentences like this and rephrase them. 

Example: `-   To ensure backward compatibility, `initialCurrent` and `initialPageSize` props will work as before.`

2023-03-03 11:41 UTC, BatuhanW commented on .changeset/lazy-crews-poke.md
> +-   To ensure backward compatibility, `hasPagination` prop will works as before.
Please, let's review all sentences like this and rephrase them.

Example: -   To ensure backward compatibility, initialCurrentandinitialPageSize props will work as before.

2023-03-03 11:41 UTC, BatuhanW commented on .changeset/tidy-actors-grow.md
> +-   To ensure backward compatibility, `hasPagination` prop works as before.
Please, let's review all sentences like this and rephrase them.

Example: -   To ensure backward compatibility, initialCurrentandinitialPageSize props will work as before.

2023-03-03 11:41 UTC, BatuhanW commented on .changeset/young-pears-dream.md
> +-   To ensure backward compatibility, `hasPagination` prop works as before.
Please, let's review all sentences like this and rephrase them.

Example: -   To ensure backward compatibility, initialCurrentandinitialPageSize props will work as before.

2023-03-03 13:29 UTC, BatuhanW approved these changes

2023-03-03 13:32 UTC, yildirayunlu approved these changes

2023-03-03 13:32 UTC, merged