fix(v4): update swizzle based on v4
refinedev/refine pull request #3728
Opened 2023-03-06 14:30 UTC by salihozdemir

Updated swizzle `transform` functions based on v4.

- [x] All swizzleable item tested

2023-03-06 15:59 UTC, aliemir commented on packages/antd/refine.config.js
> +                If you want to see an examples of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers/react-router-v6
```suggestion
                If you want to see an examples of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-06 16:00 UTC, aliemir commented on packages/chakra-ui/refine.config.js
> +                If you want to see an examples of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers/react-router-v6
```suggestion
                If you want to see an examples of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-06 16:00 UTC, aliemir commented on packages/chakra-ui/refine.config.js
> +                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers/react-router-v6/#how-to-hand
```suggestion
                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-06 16:01 UTC, aliemir commented on packages/core/refine.config.js
> +                If you want to see an examples of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers/react-router-v6
```suggestion
                If you want to see an examples of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-06 16:01 UTC, aliemir commented on packages/core/refine.config.js
> +                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers/react-router-v6/#how-to-hand
```suggestion
                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-06 16:02 UTC, aliemir commented on packages/mantine/refine.config.js
> +                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers/react-router-v6/#how-to-hand
```suggestion
                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-06 16:02 UTC, aliemir commented on packages/mui/refine.config.js
> +                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers/react-router-v6/#how-to-hand
```suggestion
                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-06 16:04 UTC, aliemir requested changes
Hey @salihozdemir, requested some changes about the docs URLs. We've added an index page at #3689. We can use it as the entry point for the docs about router providers.

2023-03-07 10:24 UTC, aliemir submitted a review, later dismissed

2023-03-07 12:33 UTC, BatuhanW requested changes

2023-03-07 12:33 UTC, BatuhanW commented on packages/antd/refine.config.js
> +                If you want to see an examples of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```suggestion
                If you want to see an example of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-07 12:33 UTC, BatuhanW commented on packages/antd/refine.config.js
> +                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```suggestion
                If you want to see examples of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
```

2023-03-07 12:33 UTC, BatuhanW commented on packages/antd/refine.config.js
> +                You should pass the layout components to the **<Layout/>** component.
```suggestion
                You should pass layout related components to the **<Layout/>** component's props.
```

2023-03-07 12:33 UTC, BatuhanW commented on packages/antd/refine.config.js
> +                If you want to see an examples of error page in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
Let's update all references with the same sentence.

2023-03-07 12:33 UTC, BatuhanW commented on packages/antd/refine.config.js
> +                If you want to see an example of authentication pages in use, you can refer to the documentation at https://refine.dev/docs/packages/documentation/routers
Let's update all references with the same sentence.

2023-03-07 12:50 UTC, BatuhanW approved these changes

2023-03-07 14:15 UTC, merged