feat(v4-examples): Migrate auth examples to new router
refinedev/refine pull request #3735
Opened 2023-03-07 09:36 UTC by alicanerdurmaz

- auth-antd
- auth-auth0
- auth-chakra-ui
- auth-google-login
- auth-headless
- auth-keycloak
- auth-mantine
- auth-mui
- auth-otp
- access-control-cerbos
- access-control-casbin

-----

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-03-07 12:07 UTC, yildirayunlu commented on examples/access-control-cerbos/src/App.tsx
> +                        />
```suggestion
                        <Route path="/categories" element={<CategoryList />} />
                        <Route
                            path="/categories/show/:id"
                            element={<CategoryShow />}
                        />
                        <Route
                            path="/categories/create"
                            element={<CategoryCreate />}
                        />
                        <Route
                            path="/categories/edit/:id"
                            element={<CategoryEdit />}
                        />
```

2023-03-07 14:20 UTC, BatuhanW requested changes

2023-03-07 14:20 UTC, BatuhanW commented on examples/access-control-casbin/src/App.tsx
> +                        <Route path="/posts" element={<CategoryList />} />
```suggestion
                        <Route path="/categories" element={<CategoryList />} />
```

2023-03-07 14:20 UTC, BatuhanW commented on examples/access-control-casbin/src/App.tsx
> +                            path="/posts/show/:id"
```suggestion
                            path="/categories/show/:id"
```

2023-03-08 06:25 UTC, salihozdemir approved these changes

2023-03-08 06:25 UTC, salihozdemir commented on examples/audit-log-provider/src/App.tsx
> +                    <Route element={<Outlet />}>
No need to add parent `Route` in here.
```suggestion
```

2023-03-08 07:10 UTC, salihozdemir approved these changes

2023-03-08 07:12 UTC, BatuhanW approved these changes

2023-03-08 07:38 UTC, yildirayunlu approved these changes

2023-03-08 08:19 UTC, merged