fix(v4): migrate nextjs examples to new router
refinedev/refine pull request #3741
Opened 2023-03-07 13:42 UTC by yildirayunlu

Migrate nextjs examples to new router.

2023-03-08 06:22 UTC, salihozdemir approved these changes

2023-03-08 06:22 UTC, salihozdemir commented on examples/with-nextjs/pages/_app.tsx
> +// import { PostList, PostCreate, PostEdit, PostShow } from "@components";
```suggestion
```

2023-03-08 10:16 UTC, omeraplak requested changes

2023-03-09 08:00 UTC, salihozdemir commented on examples/with-nextjs/pages/index.tsx
> +import { NavigateToResource } from "@pankod/refine-nextjs-router";
```suggestion
import { NavigateToResource } from "@refinedev/nextjs-router";
```

2023-03-09 08:05 UTC, salihozdemir commented on examples/with-nextjs/pages/posts/create/index.tsx
> +export default function PostList() {
```suggestion
export default function PostCreate() {
```

2023-03-10 10:20 UTC, closed without merging