feat(v4-examples): update router provider examples starts with "c" and "b"
refinedev/refine pull request #3745
Opened 2023-03-07 14:56 UTC by alicanerdurmaz

- base-antd
- base-chakra-ui
- base-headless
- base-mantine
- base-mui
- calendar-app
- command-palette-kbar
- core-use-import
- core-use-menu
- core-use-modal
- core-use-select
- customization-footer
- customization-login
- customization-offlayout-area
- customization-rtl
- customization-sider
- customization-theme-antd
- customization-theme-chakra-ui
- customization-theme-mantine
- customization-theme-mui
- customization-top-menu-layout

---------- 

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-03-07 15:08 UTC, salihozdemir requested changes

2023-03-07 15:08 UTC, salihozdemir commented on examples/calendar-app/src/App.tsx
> +                        list: CalendarPage,
```suggestion
                        list: "/events",
```

2023-03-07 15:08 UTC, salihozdemir commented on examples/core-use-import/src/App.tsx
> +                    <Route element={<Outlet />}>
```suggestion                    
```
I think, there is no need to add parent `Route` in here.

2023-03-07 15:08 UTC, salihozdemir commented on examples/core-use-modal/src/App.tsx
> +                    <Route element={<Outlet />}>
```suggestion
```

2023-03-07 15:08 UTC, salihozdemir commented on examples/core-use-select/src/App.tsx
> +                    <Route element={<Outlet />}>
```suggestion
```

2023-03-08 07:09 UTC, salihozdemir approved these changes

2023-03-08 08:27 UTC, BatuhanW approved these changes

2023-03-08 09:30 UTC, merged