docs: fixed links,revised the docs of overview, quickstart and first 2 parts of tutorial
refinedev/refine pull request #3877
Opened 2023-03-15 13:39 UTC by DoguhanOzgurAkca

…ickstart and start of tutorial

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-03-15 13:40 UTC, omeraplak commented on documentation/docs/tutorial/1-getting-started/mui/3-generate-crud-pages.md
> +How **refine** apps communicate with the API via the `dataProvider` will be explained in [Unit 3](../../2-understanding-dataprovider/0-intro.md).
We need to fix this link @necatiozmen  @BatuhanW

2023-03-15 15:50 UTC, DoguhanOzgurAkca commented
https://refine.dev/docs/tutorial/getting-started/prepare-env/

There is supposed to be a "go back/previous segment" button in the bottom in this page but there isn't.

2023-03-15 16:22 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/antd/2-create-project.md
>  1. Launch your terminal and type the following command using your preferred package manager:
Down there, there is a small note in the yarn version where it says "Only support yarn@1 version." 
It should be "Only supports"

2023-03-15 16:28 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
> +You will learn how to create CRUD pages manually using the code generated by Inferencer as a reference in [Unit 5](/docs/tutorial/adding-crud-pages/antd/index).
There is a problem where both the sections of the current part of the tutorial(part 2 for one for example) and general parts of the tutorials are named "Units"
Using "Section" or another word for either of them can be better.

2023-03-15 16:29 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/headless/3-generate-crud-pages.md
> +Then, we need to add the `<HeadlessInferencer/>` component which is used by passing appropriate values to the `resources` prop of the `<Refine/>` component in `App.tsx` as shown below:
It seemed like a correct decision but ultimately i am unsure if this correction was right or not, wanted to point out in case it is.

2023-03-15 16:35 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/5-deploy-project.md
>  <Checklist>
in the 27th line, the "to support for client-side routing" seems a bit off. Shouldn't it be something along the lines of "For more support on client-side routing, check out the create Create React App documentation on deployment"?

2023-03-15 16:40 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/0-intro.md
>  **Deploy your App**
Link of [Generate CRUD pages automatically with Inferencer] is wrong.

2023-03-15 17:24 UTC, BatuhanW commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +<summary>What if I need help or want to learn more about or give feedback about <strong>refine</strong>?</summary>
```suggestion
<summary>What if I need help or want to learn more about or give feedback to <strong>refine</strong>?</summary>
```

2023-03-15 17:25 UTC, BatuhanW commented on documentation/docs/tutorial/0-introduction/2-select-framework.md
> +**refine** is a headless framework by default, which means that you can build your app without any UI frameworks. Ig you want to use one, however, **refine** offers built-in support for the most popu
```suggestion
**refine** is a headless framework by default, which means that you can build your app without any UI frameworks. If you want to use one, however, **refine** offers built-in support for the most popular UI frameworks such as **Material UI**, **Ant Design**, **Mantine** and **Chakra UI**. Using one of these frameworks can significantly speed up your app's UI development process.
```

2023-03-15 18:38 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +<summary>What if I need help or want to learn more about or give feedback about <strong>refine</strong>?</summary>
Reason why i went with "about" instead of "to" here is because "What if i need help, want to learn more about" part is talking about refine as in the product/framework. If you were to put "to" instead, it would seem like you are talking about people behind the refine/developers, which works for the "give feedback to developers" but doesn't exactly work when it comes to "want to learn more about developers".  Kind of a "Metonymy" thing.

Something along the lines of "What if i need help or want to learn more about Refine, or give feedback to developers behind it?" might be better. 
If we go with this though, replacing the first "or" with a comma and removing "about"
```suggestion
<summary>What if i need help, want to learn more or give feedback to <strong>refine</strong>?</summary>
```

2023-03-15 20:17 UTC, DoguhanOzgurAkca commented on documentation/docs/getting-started/overview.md
> +**refine** works *seamlessly* with any custom design or UI framework you may favor. For convenience, it ships with ready-made integrations for [Ant Design System](https://ant.design/), [Material UI](
```suggestion
refine also ships with ready-made integrations for [Ant Design System](https://ant.design/), [Material UI](https://mui.com/), [Mantine](https://mantine.dev/), and [Chakra UI](https://chakra-ui.com/) for convenience.

All in all, refine just works seamlessly with all custom design or UI framework.
```
This sentence was a slight eye-sore of sorts, this new version of solves that problem while making so that the first sentence is still very much on display.

2023-03-16 07:50 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/0-intro.md
> +As you make changes to your project, you can commit them to your GitHub repository. Netlify listens for changes to your GitHub repository to automatically rebuilds and deploys your application on eve
The intended point is that users can always access the latest deploys based on your most recent commits.

So we can say something like: "This allows anyone to access and view the latest version of your app"

2023-03-16 08:08 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
>  The `@refinedev/inferencer` package provides the `<AntdInferencer/>` component, which can be imported from `@refinedev/inferencer/antd`. It used to generate CRUD pages based on your API response with
"It" should be refers to  "`<AntdInferencer/>`"  component.  So you can commit if it's fits

2023-03-16 08:21 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/headless/3-generate-crud-pages.md
> +Then, we need to add the `<HeadlessInferencer/>` component which is used by passing appropriate values to the `resources` prop of the `<Refine/>` component in `App.tsx` as shown below:
It right you can commit

2023-03-16 08:24 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/5-deploy-project.md
>  <Checklist>
Yes you can update

2023-03-16 08:33 UTC, necatiozmen commented on documentation/docs/tutorial/0-introduction/1-prequisite.md
> +<summary>What if I need help or want to learn more about or give feedback about <strong>refine</strong>?</summary>
Nice, commit please @DoguhanOzgurAkca

2023-03-16 08:49 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/0-intro.md
>  **Deploy your App**
Could you fix?

2023-03-16 09:43 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/0-intro.md
> +If you’d like to deploy to Netlify, skip to [Deploy your app to the web](/docs/tutorial/getting-started/deploy-project/). Otherwise, skip to [Generate CRUD pages automatically with Inferencer](/docs/
Reading this now, it seems a bit weird. Deploying the app to the web comes after generating crud pages but this paragraph makes it look like it comes before it. If someone skips to "generate CRUD pages automatically with Inferencer" part, they are going to reach "Deploy your app to the web" anyways.

2023-03-16 11:47 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/0-intro.md
> +If you’d like to deploy to Netlify, skip to [Deploy your app to the web](/docs/tutorial/getting-started/deploy-project/). Otherwise, skip to [Generate CRUD pages automatically with Inferencer](/docs/
I think so. Maybe we can refactor the sentence like this: 
```suggestion
To learn how to deploy to Netlify, you can refer to the [Deploy your app to the web](/docs/tutorial/getting-started/deploy-project/).   

Now, you can navigate to [Generate CRUD pages automatically with Inferencer](/docs/tutorial/getting-started/antd/generate-crud-pages) to start building with **refine**!
```

2023-03-16 12:03 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/chakra-ui/3-generate-crud-pages.md
> +I understood what inferences is, how it works and how it can make my work easier.
```suggestion
I understood what Inferences is, how it works and how it can make my work easier.
```

2023-03-16 12:28 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/chakra-ui/3-generate-crud-pages.md
> +I understood what inferences is, how it works and how it can make my work easier.
I already fixed this one and all of its instances yesterday with one of the commits

2023-03-16 12:53 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/0-intro.md
> +If you’d like to deploy to Netlify, skip to [Deploy your app to the web](/docs/tutorial/getting-started/deploy-project/). Otherwise, skip to [Generate CRUD pages automatically with Inferencer](/docs/
Is pointing out "How to deploy to netlify/web" necessary here? I think it might confuse people since if they proceed after deploying, they will miss out on generating crud pages automatically, which is necessary, no?

2023-03-16 14:22 UTC, necatiozmen commented on documentation/docs/tutorial/1-getting-started/0-intro.md
> +If you’d like to deploy to Netlify, skip to [Deploy your app to the web](/docs/tutorial/getting-started/deploy-project/). Otherwise, skip to [Generate CRUD pages automatically with Inferencer](/docs/
OK, make sense. Maybe you can change the "Deploy your App" header to "What's Next" and remove sentence starts with "To learn.."

2023-03-16 18:54 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/mui/3-generate-crud-pages.md
> +How **refine** apps communicate with the API via the `dataProvider` will be explained in [Unit 3](../../2-understanding-dataprovider/0-intro.md).
If the problem was about links starting with .../../ and the like, i took care of it yesterday, replacing the links with their old counterparts.

2023-03-17 08:07 UTC, necatiozmen approved these changes

2023-03-17 10:28 UTC, omeraplak approved these changes
Thank you @DoguhanOzgurAkca @necatiozmen 🎉

2023-03-17 10:30 UTC, omeraplak requested changes

2023-03-17 10:33 UTC, merged