fix: `useModalForm`'s `autoSubmitClose` and `autoResetForm` features
refinedev/refine pull request #3911
Opened 2023-03-17 14:19 UTC by salihozdemir

`autoSubmitClose` and `autoResetForm` were not working even though they had these properties.

Now, both of them work properly. Just I found an issue with the "edit" action to reproduce it follow the below:

1- Call the useModalForm with `action: "edit"` prop
2- Add `autoSubmitClose: false,` prop
3- Update the form items with custom texts
4- When the mutation is successful, the values of the form items are filled with cache data instead of custom texts.

2023-03-17 14:49 UTC, BatuhanW requested changes
Let's add some tests

2023-03-20 12:46 UTC, BatuhanW commented on packages/antd/src/hooks/form/useModalForm/index.spec.tsx
> +        expect(result.current.modalProps.open).toBe(false);
```suggestion
        expect(result.current.modalProps.open).toBe(true);

        await act(async () => {
            result.current.modalProps.onCancel?.({} as any);
        });

        expect(result.current.modalProps.open).toBe(false);
```

2023-03-20 12:47 UTC, BatuhanW commented on packages/antd/src/hooks/form/useModalForm/index.spec.tsx
> +        expect(result.current.modalProps.open).toBe(true);
```suggestion
        expect(result.current.modalProps.open).toBe(false);

        await act(async () => {
            result.current.show();
        });

        expect(result.current.modalProps.open).toBe(true);
```

2023-03-20 13:20 UTC, omeraplak commented on packages/antd/src/hooks/form/useModalForm/useModalForm.ts
> +    const { visible: _visible, ...otherModalProps } = modalProps;
Is this a breaking change? Why did we change this?

2023-03-20 14:37 UTC, salihozdemir commented on packages/antd/src/hooks/form/useModalForm/index.spec.tsx
> +        );
In this hook, `isDirty` doesn't affect the working logic of the `useModalForm` hook so we should not add it.

2023-03-20 15:21 UTC, BatuhanW commented on .changeset/smooth-planets-suffer.md
> +Now, when the form is submitted successfully, the `setId` function is not called.
I think this is an internal knowledge and won't give an idea about who is reading it. Perhaps we can mention the fixed behaviour? That would be better, if someone else has this problem, it will be clear that it's fixed.

2023-03-21 06:18 UTC, omeraplak approved these changes

2023-03-21 06:27 UTC, alicanerdurmaz approved these changes

2023-03-21 14:02 UTC, BatuhanW approved these changes

2023-03-21 14:02 UTC, BatuhanW commented on .changeset/smooth-planets-suffer.md
> +In forms that use `useForm`, the `onFinish` will reset the current `id` to `undefined` when the mutation is successful. Now, the `id` will not be set to `undefined`.
```suggestion
In forms that use `useForm`, the `onFinish` was resetting the current `id` to `undefined` when the mutation is successful. Now, the `id` will not be set to `undefined`.
```

2023-03-21 14:50 UTC, merged