feat(antd): create themes and layout components to use with themes
refinedev/refine pull request #3912
Opened 2023-03-17 14:52 UTC by alicanerdurmaz

following changes implemented for `@refinedev/antd`:

-   blue, purple, magenta, red, orange, yellow, and green themes were added.

-   `<ThemedLayout>`, `ThemedSider`, `<ThemedTitle>`, `<ThemedHeader>` created to use theme colors.

-   `<EditButton>` in `<Show>` type changed to `primary`.
-   `CreateButton` type changed to `primary`.

2023-03-20 10:44 UTC, omeraplak requested changes

2023-03-20 10:44 UTC, omeraplak commented on packages/antd/src/components/themedLayout/sider/index.tsx
> +export const ThemedSider: React.FC<RefineThemedLayoutSiderProps> = ({
Could we share logic with the Sider component?

2023-03-20 10:44 UTC, omeraplak commented on packages/antd/src/components/themedLayout/header/index.tsx
> +    const { data: user } = useGetIdentity({
Could we share logic with the Header component?

2023-03-20 10:44 UTC, omeraplak commented on packages/antd/src/components/themedLayout/title/index.tsx
> +    const { token } = useToken();
Could we share logic with the Title component?

2023-03-20 10:44 UTC, omeraplak commented on packages/antd/src/definitions/themes/index.ts
> +export const BLUE_THEME: ThemeConfig = {
Why did we choose a distant naming convention for humans? I think we can extract names like Blue, Purple from an object like RefineThemes. This way, we can use them in IntelliSense.


ex:
```ts
import { RefineThemes } from "@refinedev/core";

    const [config, setConfig] = useState({
        token: RefineThemes.Blue.token,
        algorithm: theme.darkAlgorithm,
    });
```

2023-03-20 12:43 UTC, BatuhanW commented on examples/theme-antd-demo/package.json
> +    "typescript": "^4.7.4",
I know we had these earlier, but let's add them to devDependencies for new examples.

2023-03-20 12:43 UTC, BatuhanW commented on examples/theme-antd-demo/package.json
> +    "@types/react-dom": "^18.0.0",
I know we had these earlier, but let's add them to devDependencies for new examples.

2023-03-20 12:43 UTC, BatuhanW commented on packages/antd/src/components/themedLayout/sider/index.spec.tsx
> +    xit("should work sider collapse ", async () => {
```suggestion
    it("should work sider collapse ", async () => {
```

2023-03-20 13:37 UTC, omeraplak commented on packages/antd/src/hooks/layout/useSider/index.tsx
> +    const [collapsed, setCollapsed] = useState<boolean>(false);
Could we add some tests?

2023-03-20 15:30 UTC, BatuhanW commented on packages/antd/src/components/pages/auth/components/pageTitle/index.tsx
> +    const iconToRender = icon === null ? null : icon || defaultIcon;
```suggestion
    const iconToRender = icon ?? defaultIcon;
```

If I'm not missing something here, I think this suggested change is easier to read.

2023-03-20 15:30 UTC, BatuhanW commented on packages/antd/src/components/pages/auth/components/pageTitle/pageTitle.spec.tsx
> +            <AuthPageTitle icon={<div data-testid="custom-icon" />} />,
🔥

2023-03-21 06:14 UTC, omeraplak approved these changes
🥇

2023-03-21 06:52 UTC, yildirayunlu approved these changes

2023-03-21 08:14 UTC, BatuhanW approved these changes

2023-03-21 08:38 UTC, merged