fix(react-table): fixed bug that `current` being 1 when the `syncWithLocation` enabled
refinedev/refine pull request #3941
Opened 2023-03-21 12:57 UTC by salihozdemir

Fixed an issue where `current` was 1 when `filters` and `sorters` were in the URL when `syncWithLocation` was enabled.

2023-03-21 13:19 UTC, omeraplak requested changes

2023-03-21 13:19 UTC, omeraplak commented on packages/react-table/src/useTable/index.ts
> +function useFirstRender() {
Can we take this to a separate file? Also, let's not forget to add the tests.

2023-03-21 13:33 UTC, alicanerdurmaz approved these changes

2023-03-21 13:33 UTC, alicanerdurmaz commented on packages/react-table/src/utils/useFirstRender/index.ts
> +export const useFirstRender = () => {
what do you think ? 🤔 

```suggestion
export const useIsFirstRender = () => {
```

2023-03-21 14:02 UTC, omeraplak requested changes

2023-03-22 06:48 UTC, omeraplak approved these changes

2023-03-22 06:48 UTC, merged