feat: new `WelcomePage` component
refinedev/refine pull request #3974
Opened 2023-03-24 13:03 UTC by salihozdemir

Updated `WelcomePage` component on `@refinedev/core` package.

Deprecated `WelcomePage` components on UI framework packages.

- [x] Update superplate plugins ([PR](https://github.com/pankod/superplate-core-plugins/pull/315))

2023-03-24 14:05 UTC, omeraplak commented on packages/core/src/components/pages/welcome/index.spec.tsx
> +            "https://discord.com/invite/refine",
```suggestion
            "https://discord.gg/refine",
```

2023-03-24 14:05 UTC, omeraplak commented on packages/core/src/components/pages/welcome/index.tsx
> +        link: "https://discord.com/invite/refine",
```suggestion
        link: "https://discord.gg/refine",
```

2023-03-24 14:24 UTC, alicanerdurmaz approved these changes

2023-03-27 10:29 UTC, omeraplak requested changes

2023-03-27 15:13 UTC, omeraplak requested changes

2023-03-27 15:13 UTC, omeraplak commented on packages/core/src/components/pages/welcome/index.tsx
> +                    "url(https://images2.imgbox.com/cd/6b/gjMLMoBL_o.png)",
ups 
```suggestion
                    "url(https://refine.ams3.digitaloceanspaces.com/welcome-page/welcome-page-refine.png)",
```

2023-03-27 15:13 UTC, omeraplak commented on packages/core/src/components/pages/welcome/index.tsx
> +                    src="https://images2.imgbox.com/1c/b8/UKLkYsVh_o.png"
```suggestion
                    src="https://refine.ams3.cdn.digitaloceanspaces.com/welcome-page/refine-logo.png"
```

2023-03-27 21:11 UTC, aliemir commented on packages/core/src/components/pages/welcome/index.tsx
> +    }, []);
If this is only meant for adding the `:hover` class to an icon, we can use `onPointerEnter` and `onPointerLeave` instead of `:hover`. Won't hurt to have a basic state. We can have a separate component for the place we want to apply the `hover` to and add this enter/leave logic with a state there. 

I really don't like the idea of injecting a stylesheet. Issue magnet 🧲 

@omeraplak @salihozdemir @BatuhanW

2023-03-28 10:10 UTC, merged