fix: remove empty title
refinedev/refine pull request #4016
Opened 2023-03-29 13:25 UTC by BatuhanW

Removed redundant empty title from nextjs-router documentation.

### Closing issues

Closes #4011

2023-03-29 13:48 UTC, omeraplak requested changes

2023-03-29 13:48 UTC, omeraplak commented on documentation/docs/packages/documentation/routers/nextjs-router.md
> +    :::
```suggestion
:::
```

2023-03-29 13:48 UTC, BatuhanW commented on documentation/docs/packages/documentation/routers/nextjs-router.md
> +    :::
```suggestion
:::
```

2023-03-30 05:49 UTC, alicanerdurmaz approved these changes

2023-03-30 05:59 UTC, omeraplak approved these changes

2023-03-30 06:00 UTC, merged