fix: text color on footer
refinedev/refine pull request #4099
Opened 2023-04-06 07:22 UTC by himanshu1221

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

There was a problem with the footer text color  it was too light to be visible as discussed I changed the color to black and now it is much more visible

### Test plan (required)

I have tested it in a test server and its working perfectly fine
![Screenshot from 2023-04-06 12-51-06](https://user-images.githubusercontent.com/32031706/230303985-1fe64932-58aa-40c0-9829-d04fd87adbd1.png)

### Closing issues

### #3914 

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-04-06 13:03 UTC, himanshu1221 commented
> Hey @himanshu1221 , It looks better now. Thanks! Can social media icons stay as they were before? They already have a hover state.

sure I'll edit it and make a commit

2023-04-06 13:21 UTC, himanshu1221 commented
> Hey @himanshu1221 , It looks better now. Thanks! Can social media icons stay as they were before? They already have a hover state.

I have made the suggested hanged you may have  a look

2023-04-07 06:29 UTC, omeraplak requested changes

2023-04-07 06:29 UTC, omeraplak commented on .gitpod.yml
> +# This configuration file was automatically generated by Gitpod.
Gitpod configuration can be deleted.

2023-04-07 06:42 UTC, himanshu1221 commented on .gitpod.yml
> +# This configuration file was automatically generated by Gitpod.
Done

2023-04-07 06:53 UTC, omeraplak approved these changes

2023-04-07 06:53 UTC, merged