feat: add missing third generic type of `useQuery`
refinedev/refine pull request #4113
Opened 2023-04-06 13:45 UTC by salihozdemir

Added a new generic type to provide `useQuery` features. 

close #3960

2023-04-07 11:04 UTC, omeraplak requested changes

2023-04-07 11:04 UTC, omeraplak commented on .changeset/happy-geese-grin.md
> +Added missing third generic parameter to hooks which are using `useQuery` internally.
Could we add usage of example?

2023-04-10 07:04 UTC, alicanerdurmaz approved these changes

2023-04-10 08:23 UTC, omeraplak approved these changes

2023-04-10 09:21 UTC, aliemir commented on packages/core/src/hooks/show/useShow.ts
> +    queryResult: QueryObserverResult<GetOneResponse<TQueryFnData>>;
The usage below this file is correct (sending `TData` instead of `TQueryFnData`) but in this `useShowReturnType` type, naming of the generic is not quite right and hard to understand within the context of this file. (Might lead to confusion later in the future)

We can rename it to `TData` which is a better name and consistent with the `useShowProps`.

```suggestion
export type useShowReturnType<TData extends BaseRecord = BaseRecord> = {
    queryResult: QueryObserverResult<GetOneResponse<TData>>;
```

2023-04-10 09:21 UTC, aliemir commented on packages/core/src/hooks/show/useShow.ts
> +    queryResult: QueryObserverResult<GetOneResponse<TQueryFnData>>;
@omeraplak @salihozdemir

2023-04-10 09:22 UTC, aliemir approved these changes

2023-04-10 11:43 UTC, aliemir approved these changes

2023-04-10 12:02 UTC, omeraplak approved these changes

2023-04-10 12:02 UTC, aliemir approved these changes
🎖️

2023-04-10 12:03 UTC, merged