docs: revised the parts of the tutorial from unit 3 to unit 6
refinedev/refine pull request #4170
Opened 2023-04-13 16:00 UTC by DoguhanOzgurAkca

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-04-14 06:54 UTC, DoguhanOzgurAkca commented on documentation/docs/migration-guide/router-provider.md
> +-   > [`@refinedev/remix-router`](/docs/packages/documentation/routers/remix) and [`Remix`](https://remix.run/docs/en/main) documentations for Remix
I changed most of the links to be in markdown quotes, except for the ones in Admonitions like :::note
I think it looks clearer and better like this overall, but i can change them back in case it is weird and so on.

2023-04-14 06:56 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +Data providers can also communicate with `REST`, `GraphQL`, `RPC` and `SOAP` based APIs, so you can imagine the data provider as an adapter between **refine** and the API.
I tried to wrap API's in ` whenever i saw them, as they usually didn't have them but they do here.

2023-04-14 07:05 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +**refine** comes with various data providers out of the box, but for this tutorial, will be using the `refine-simple-rest` data provider to communicate with RESTful APIs.
should REST here be wrapped in `` ? `REST`ful APIs?

2023-04-14 07:28 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +## What is `swizzle`?
I think using `swizzle` everywhere looks good until it is something like "after swizzling" 
though those can be written as "after the `swizzle`"

2023-04-14 07:59 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md
> +In the previous unit, we consumed the API to show the data in the auto-generated Inferencer pages. To allow **refine** to communicate with the API, we registered a data provider using `dataProvider`
This is a bit of a weird sentence. It looks like it is talking about what was done before? Is it meant to be something like "we have already implemented a data provider before, did you forget?" and showing an example of how it was done? Then
```suggestion
In the previous unit, we already consumed the API to show the data in the auto-generated Inferencer pages and registered a data provider using the `dataProvider` property of the `<Refine>` component to allow **refine** communicate with the API:
```
Might be better i think? Unless this sentence/part has a different meaning

2023-04-14 08:08 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +:::note
considering it was written in bold normally, using
```suggestion
:::caution
```
might be better overall, but i am unsure.

2023-04-14 08:53 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/4-adding-crud-pages/antd/add-create-page.md
> -Create page is the page where you can create the record. In this tutorial, we will create the create page for the `blog_posts` resource.
I thought that these parts were unnecessary in all the pages, except for list but that is different.

2023-04-14 08:57 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/4-adding-crud-pages/antd/add-create-page.md
> +### The Create Page Hooks
I was unsure about what to capitalize and not in these parts honestly. I think not capitalizing them is better myself.

2023-04-14 08:59 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/4-adding-crud-pages/antd/add-create-page.md
>      next: tutorial/adding-crud-pages/{preferredUI}/add-delete-feature
I didn't update the names of the pages because i am unsure about capitalization
I think "Adding the create page" would be better overall.
Can change all the titles to be like that if people agree. Some already seem to be like that by the way.

2023-04-14 12:52 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
> +`login` method is used to authenticate users. It expects to return a resolved promise with the following type:
I think "promise" is supposed to be like this and doesn't need to be capitalized, unless i am mistaken.

2023-04-14 17:35 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
> +## What is `swizzle`?
Update
Managed make it work but i will have to bug-proof it a little with some tests
![image](https://user-images.githubusercontent.com/76914028/232116909-6257fa42-f4f7-427c-a962-d3ae0c789e88.png)

2023-04-18 11:37 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/3-understanding-resources/0-intro.md
> +It’s important to note that route management will be handled by your preferred framework (React Router, Next.js, Remix).
```suggestion
It’s important to note that route management will be handled by your preferred framework (React Router, Next.js, Remix) which is what makes it possible to use **refine** with any React (Web, Electron, React Native etc.) application freely.
```

2023-04-18 14:31 UTC, necatiozmen requested changes

2023-04-18 14:31 UTC, necatiozmen commented on documentation/docs/tutorial/5-understanding-authprovider/antd/2-auth-pages.md
> -                            <Route
Do not remove existing codes in codeblocks

2023-04-18 14:31 UTC, necatiozmen commented on documentation/docs/tutorial/5-understanding-authprovider/chakra-ui/2-auth-pages.md
> -`<AuthPage/>` component provides auth pages for login, signup, forgot password and reset password. It also provides a way to customize theses pages with various props. So, `<AuthPage/>` is a quick st
Why did you remove this section?

2023-04-19 08:26 UTC, necatiozmen approved these changes

2023-04-19 08:33 UTC, merged