feat: sticky headers
refinedev/refine pull request #4209
Opened 2023-04-20 08:13 UTC by yildirayunlu

feat: sticky headers

2023-04-24 08:46 UTC, alicanerdurmaz approved these changes

2023-04-26 08:24 UTC, salihozdemir approved these changes

2023-04-26 08:24 UTC, salihozdemir commented on .changeset/neat-snakes-sit.md
> +import { ThemedLayoutV2, ThemedHeaderV2 } from '@refinedev/chakra-ui';
```suggestion
import { ThemedLayoutV2 } from '@refinedev/chakra-ui';
```

2023-04-26 08:24 UTC, salihozdemir commented on .changeset/angry-pots-pretend.md
> +import { ThemedLayoutV2, ThemedHeaderV2 } from '@refinedev/antd';
```suggestion
import { ThemedLayoutV2 } from '@refinedev/antd';
```

2023-04-26 08:24 UTC, salihozdemir commented on .changeset/nine-boats-look.md
> +import { ThemedLayoutV2, ThemedHeaderV2 } from '@refinedev/mantine';
```suggestion
import { ThemedLayoutV2 } from '@refinedev/mantine';
```

2023-04-26 09:22 UTC, aliemir requested changes
The changeset for `@refinedev/ui-types` is missing @yildirayunlu

2023-04-26 09:44 UTC, aliemir requested changes
Since we've added the `isSticky` prop to the `RefineThemedLayoutV2HeaderProps` type. We should also update the `@refinedev/mui`'s `ThemedSiderV2` to reflect the changes accordingly. (By default the `AppBar` was set to `position: sticky`)

@yildirayunlu Thank you 🙏

2023-04-26 10:10 UTC, alicanerdurmaz approved these changes

2023-04-26 11:04 UTC, aliemir approved these changes

2023-04-26 11:05 UTC, merged