fix(supabase): return data on create/update
refinedev/refine pull request #4213
Opened 2023-04-21 19:29 UTC by 02JanDal

Please provide enough information so that others can review your pull request:

Getting data back when inserting or updating using supabase requires an extra function call, see #4212 for details.

Explain the **details** for making this change. What existing problem does the pull request solve?

See #4212 for details.

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

Tests previously had invalid mocks. They have been fixed accordingly.

### Closing issues

Closes #4212

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-04-24 05:19 UTC, aliemir reviewed
Hey @02JanDal thank you for the PR! Are there any specific reason for `select` to be different in `create` and `update`? It looks like `create` and `createMany` has a default `"*"` in the selection set but `update` and `updateMany`  only appends `select` if its defined 🤔 I like the approach in `update` methods more actually 😅 

Also any chance to write some tests for `update` and `updateMany` as well when you have the time?

2023-04-24 05:20 UTC, aliemir requested changes
Let's decide on which approach we should follow and update the methods accordingly. And have simple tests for update method as well

2023-05-02 12:56 UTC, omeraplak approved these changes
LGTM! 🎯

2023-05-02 12:57 UTC, aliemir approved these changes

2023-05-02 13:18 UTC, alicanerdurmaz approved these changes

2023-05-02 13:20 UTC, merged