Revise api reference
refinedev/refine pull request #4230
Opened 2023-04-26 09:55 UTC by DoguhanOzgurAkca

Revised the first 4 sections of core api providers

2023-04-26 10:12 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/data-provider.md
> +### Usage
Is this part about multiple data providers, or not? I added usage here but i am unsure about it

2023-04-26 10:15 UTC, DoguhanOzgurAkca reviewed
Was generally unsure about several parts in these documentations

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/data-provider.md
> +The `default` key is required for the default data provider and will be used as the default data provider.
not exactly sure what this means

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/audit-log-provider.md
> +For examepl, if you have the code below, only events will be created for the `create` mutation.
```suggestion
For example, if you have the code below, only events will be created for the `create` mutation.
```

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/audit-log-provider.md
> +The `meta.audit` allows you to manage the audit log events for a resource. It can additionally manage which type of mutations an event will have when created, **if no definition is made, it will have
I am not exactly sure about the last para here that is bold

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/accessControl-provider.md
> +`useCan` uses the `can` for the query function for **react-query**'s `useQuery`. It takes the parameters that `can` takes, can be configured with `queryOptions` of `useQuery` and returns the result o
Unsure about this part as well

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/accessControl-provider.md
> +> For more information, refer to these sections in the Interface References documentation [`IResourceItem`][iresourceitem], [`BaseKey`][basekey], [`CanParams`][canparams], [`CanReturnType`][canreturn
Unsure if this part is correct or not

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/accessControl-provider.md
> -Access control is a broad topic where there are lots of advanced solutions that provide different set of features. **refine** is deliberately agnostic for its own API to be able to integrate differen
"`can` method would be the entry point for those solutions"
I am unsure about what this part meant or if my revised version is correct or not

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/general-concepts.md
> +**refine** core is fully independent of UI, meaning that you can use core components and hooks without any UI dependency. All of the **data**-related hooks, such as [`useTable`](/docs/api-reference/c
I am unsure if the last part that i added, "that are independent of UI" is correct. I was trying to make the two sentences work together better.

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/general-concepts.md
> +To make the inferencer work, you need to pass the `routerProvider` prop to the `<Refine>` component from your router package choice.
I am unsure what this part was saying

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/auth-provider.md
> +**refine**'s v4 release is backward compatible and supports legacy auth provider implementations until v5.
<img width="609" alt="Screenshot 2023-04-26 at 13 08 54" src="https://user-images.githubusercontent.com/76914028/234543949-008badac-cc7e-4550-a2d7-1f047cdfd1c5.png">
<img width="616" alt="Screenshot 2023-04-26 at 13 09 08" src="https://user-images.githubusercontent.com/76914028/234544002-3c0d405f-724e-4bfb-ba2c-49c6e00f4c70.png">
I think they are a bit identical, unless we intend them to look through the entire document, if so, we can remove the code block as well.

2023-04-26 10:15 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/data-provider.md
> +**refine** gives you the ability to use multiple data providers in your app. All you need to do is to pass key and value pairs to the `dataProvider` prop of the `<Refine />` component in a form of va
"in a form of value being the data provider and the key being the name of the data provider."
unsure about this part

2023-05-03 09:16 UTC, necatiozmen requested changes

2023-05-03 09:16 UTC, necatiozmen commented on documentation/docs/api-reference/general-concepts.md
> +**refine** core is fully independent of UI, meaning that you can use core components and hooks without any UI dependency. All of the **data**-related hooks, such as [`useTable`](/docs/api-reference/c
@aliemir is this correct?

2023-05-03 09:16 UTC, necatiozmen commented on documentation/docs/api-reference/general-concepts.md
> +To make the inferencer work, you need to pass the `routerProvider` prop to the `<Refine>` component from your router package choice.
I'm not sure if it meant to say "Inferencer" feature. @aliemir

2023-05-03 09:38 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/accessControl-provider.md
> -**refine** checks for access control in its related components and pages. [Refer here to see all the places **refine** checks for access control.](#list-of-default-access-control-points)
Since it refers to the section just below this one, i didn't think it was necessary. I think there is a bit too many "note" or note-like parts in this section that make it a bit hard to read already.

2023-05-03 09:54 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/audit-log-provider.md
> -**refine** will use this `update` method in the [`useLog`](/api-reference/core/hooks/audit-log/useLog.md) hook.
I removed it because we already say 
"For example, using `useLog`'s `log` method creates an event like below" in this very part already, but i can add it in.

2023-05-03 10:00 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/data-provider.md
> +**refine** gives you the ability to use multiple data providers in your app. All you need to do is to pass key and value pairs to the `dataProvider` prop of the `<Refine />` component in a form of va
```suggestion
**refine** allows you to use multiple data providers in your app. All you need to do is pass key and value pairs to the `dataProvider` prop of the `<Refine />` component. In the pair object, the key corresponds to the data provider name, and the value corresponds to the data provider itself.
```

2023-05-03 10:03 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/data-provider.md
> +### Usage
No i mean, i added it in case it is about data providers, since it talks about usage of multiple data providers, but i can remove it if you think its unnecessary. 
Though, just below, shouldn't we then say "You can pick and use multiple data providers in two ways:

2023-05-03 20:06 UTC, aliemir commented on documentation/docs/api-reference/general-concepts.md
> +**refine** core is fully independent of UI, meaning that you can use core components and hooks without any UI dependency. All of the **data**-related hooks, such as [`useTable`](/docs/api-reference/c
Looks correct but redundant. As a matter of fact, these two sentences shouldn't even be in the same paragraph.

2023-05-03 20:10 UTC, aliemir commented on documentation/docs/api-reference/core/providers/data-provider.md
> +### Usage
Which one is the second way? There might be some confusion here, we only offer a single way to define multiple data providers.

2023-05-03 20:12 UTC, aliemir commented on documentation/docs/api-reference/core/providers/auth-provider.md
> +If you want to know about some topics such as setting authorization credentials, implementation of refresh token mechanism or creating an auth provider from scratch, refer to the ["Create Auth Provid
I agree with @necatiozmen, FAQs are better than the admonitions and we have them in many docs with same structure. @DoguhanOzgurAkca

2023-05-03 20:19 UTC, aliemir commented on documentation/docs/api-reference/core/providers/auth-provider.md
> +**refine**'s v4 release is backward compatible and supports legacy auth provider implementations until v5.
Meant for two different purposes.

We have a similar block in Migration Guide to make sure our users don't skip this info (they might want to keep using the legacy one at least for a while). 

The one in this section serves as a way to show the alternative (but legacy) approach. There might be users with old codebases who will check this page rather than the migration guide.

No changes are necessary about them. 

@DoguhanOzgurAkca

2023-05-03 20:26 UTC, aliemir commented on documentation/docs/api-reference/core/providers/audit-log-provider.md
> +The `meta.audit` allows you to manage the audit log events for a resource. It can additionally manage which type of mutations an event will have when created, **if no definition is made, it will have
Audit logs are created when there's a mutation (`create`, `update`, `delete`). For a resource, you might want to only log the `delete` events and skip the `create` and `update` events/mutations. 

To do this, you can define an array of actions in `meta.audit` such as `meta: { audit: ["delete"] }`. This will make the logging only happen for the delete actions. 

If you don't define the `meta.audit`, then all `create`, `update` and `delete` actions will be sent to the `auditLogProvider` to get logged. 

Currently, I don't have any better suggestion for it but I don't think the current changes made to this sentence is correct.

2023-05-03 20:29 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/data-provider.md
> +### Usage
https://refine.dev/docs/api-reference/core/providers/data-provider/#multiple-data-providers
I might be getting confused myself then? I am talking about the part just below this, that starts with "You can pick data providers in two ways:"

2023-05-03 20:31 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/general-concepts.md
> +**refine** core is fully independent of UI, meaning that you can use core components and hooks without any UI dependency. All of the **data**-related hooks, such as [`useTable`](/docs/api-reference/c
I merged the two paragraphs because it looked awkard to have the entire document start with a "list" and wasn't sure how to present them in a way that didn't look weird.

2023-05-03 20:40 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/audit-log-provider.md
> +The `meta.audit` allows you to manage the audit log events for a resource. It can additionally manage which type of mutations an event will have when created, **if no definition is made, it will have
```suggestion
With meta.audit, you can specify which mutations trigger audit logs; otherwise, all create, update, and delete actions will be logged by default.
```
How is this then?

2023-05-03 20:43 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/general-concepts.md
> +To make the inferencer work, you need to pass the `routerProvider` prop to the `<Refine>` component from your router package choice.
Reverted

2023-05-03 20:46 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/auth-provider.md
> +If you want to know about some topics such as setting authorization credentials, implementation of refresh token mechanism or creating an auth provider from scratch, refer to the ["Create Auth Provid
Yup, reverted this part already, forgot to resolve this one.

2023-05-05 07:49 UTC, necatiozmen commented on documentation/docs/api-reference/core/providers/accessControl-provider.md
> -**refine** checks for access control in its related components and pages. [Refer here to see all the places **refine** checks for access control.](#list-of-default-access-control-points)
Let keep it by making it one sentences. 

[**refine** checks for access control in its related components and pages.](#list-of-default-access-control-points)

2023-05-05 08:16 UTC, DoguhanOzgurAkca commented on documentation/docs/api-reference/core/providers/audit-log-provider.md
> -**refine** will use this `update` method in the [`useLog`](/api-reference/core/hooks/audit-log/useLog.md) hook.
We do already give a link to uselog at the end of both update and create.

I think merging would be a bit hard because "For example, using useLog's log method creates an event like below" is proceeded by an example but i can move them

<img width="555" alt="Screenshot 2023-05-05 at 11 14 08" src="https://user-images.githubusercontent.com/76914028/236408458-243bde07-06f3-4c57-9d23-09d6325093fb.png">

to be like this instead

<img width="555" alt="Screenshot 2023-05-05 at 11 15 44" src="https://user-images.githubusercontent.com/76914028/236408767-de30a89d-fd44-4e93-adba-a73d3e3f8f83.png">
With the link to uselog just below the example

2023-05-09 10:43 UTC, omeraplak approved these changes

2023-05-09 11:01 UTC, necatiozmen approved these changes

2023-05-09 11:01 UTC, merged