docs: update the headless tutorial
refinedev/refine pull request #4237
Opened 2023-04-27 09:11 UTC by salihozdemir

Updated the headless tutorial and depend examples.

2023-04-27 09:43 UTC, DoguhanOzgurAkca commented on documentation/docs/tutorial/1-getting-started/headless/3-generate-crud-pages.md
> +The Inferencer generates pages without any predefined layout, whereas creating a new app with **refine** comes with a default layout that includes basic components such as `Menu` and `Breadcrumb` to
```suggestion
Though refine has a default layout with basic components such as Menu and Breadcrumb, which is used to navigate between pages, Inferencer doesn't add any layouts to the pages it creates. 
Here is how we can add the default layout in our app:
```

moving this above "previewing the auto generated pages" and adding a "I have added the default layout to my app." to the checklist down below(between the existing two to preserve the order they are in the page) would also be good.

2023-04-27 12:18 UTC, salihozdemir commented on documentation/docs/tutorial/1-getting-started/headless/3-generate-crud-pages.md
> +The Inferencer generates pages without any predefined layout, whereas creating a new app with **refine** comes with a default layout that includes basic components such as `Menu` and `Breadcrumb` to
This section has been removed and a new section has been added to the new unit 5.7 instead, can you check it, please?

2023-04-27 13:21 UTC, aliemir approved these changes

2023-04-27 13:27 UTC, necatiozmen requested changes

2023-04-27 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/4-adding-crud-pages/headless/layout-menu-breadcrumb.md
> +I have learned about the layout, menu and breadcrumb components.
```suggestion
I have learned about the Layout, Menu and Breadcrumb components.
```

2023-04-27 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/4-adding-crud-pages/headless/layout-menu-breadcrumb.md
> +The `Breadcrumb` component is located in the `src/components/breadcrumb.tsx` file and it looks like this:
```suggestion
The `Breadcrumb` component is located in the `src/components/breadcrumb.tsx` file and it looks like below:
```

2023-04-27 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/4-adding-crud-pages/headless/layout-menu-breadcrumb.md
> +The `Menu` component is located in the `src/components/menu.tsx` file and it looks like this:
```suggestion
The `Menu` component is located in the `src/components/menu.tsx` file and it looks like below:
```

2023-04-27 13:27 UTC, necatiozmen commented on documentation/docs/tutorial/4-adding-crud-pages/headless/layout-menu-breadcrumb.md
> +When you create a new application with the **refine**, it creates a default layout under the `src/components/layout.tsx` file and it looks like this:
```suggestion
When you create a new application with the **refine**, it creates a default layout under the `src/components/layout.tsx` file and it looks like below:
```

2023-04-27 13:29 UTC, necatiozmen approved these changes

2023-04-28 06:12 UTC, alicanerdurmaz approved these changes

2023-04-28 06:33 UTC, aliemir approved these changes

2023-04-28 07:15 UTC, aliemir commented on documentation/docs/tutorial/4-adding-crud-pages/headless/layout-menu-breadcrumb.md
> +In [Unit 2.4](/docs/tutorial/getting-started/headless/generate-crud-pages/), we created the CRUD pages automatically with Inferencer, and wrapped them with a `<Layout>` component.
```suggestion
In [Unit 2.4](/docs/tutorial/getting-started/headless/generate-crud-pages/), we created the CRUD pages automatically with Inferencer and wrapped them with a `<Layout>` component.
```

2023-04-28 07:16 UTC, aliemir commented on documentation/docs/tutorial/4-adding-crud-pages/headless/layout-menu-breadcrumb.md
> +This component is provided when you create a new application using `create-refine-app` to help you get started quickly by providing a simple implementations of `Menu` and `Breadcrumb` components usin
```suggestion
This component is provided when you create a new application using `create-refine-app` to help you get started quickly by providing simple implementations of `Menu` and `Breadcrumb` components using **refine**'s hooks, [`useMenu`](/docs/api-reference/core/hooks/ui/useMenu) and [`useBreadcrumb`](/docs/api-reference/core/hooks/useBreadcrumb).
```

2023-04-28 07:18 UTC, merged