docs: `isSticky` docs for all ui libs
refinedev/refine pull request #4240
Opened 2023-04-27 12:37 UTC by yildirayunlu

`isSticky` docs for all ui libs

2023-04-27 12:43 UTC, omeraplak requested changes

2023-04-27 12:43 UTC, omeraplak commented on documentation/docs/api-reference/antd/components/themed-layout.md
> +You can also make it sticky with the `isSticky` component. It is optional and is `false` by default. The usage example is below.
```suggestion
You can also make it `sticky` with the `isSticky` property. It is optional and is `false` by default. The usage example is below.
```

2023-04-28 06:13 UTC, alicanerdurmaz approved these changes

2023-04-28 07:11 UTC, aliemir approved these changes

2023-04-28 07:21 UTC, omeraplak approved these changes

2023-04-28 07:21 UTC, merged