docs: refactor examples tags
refinedev/refine pull request #4341
Opened 2023-05-16 11:10 UTC by yildirayunlu

Update examples and refactor tags.

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-05-16 11:13 UTC, omeraplak requested changes

2023-05-16 11:13 UTC, omeraplak commented on documentation/docs/examples/authentication/chakra-ui.md
> +example-tags: [chakra-ui,authentication,react-table]
```suggestion
example-tags: [chakra-ui,authentication]
```

2023-05-16 11:13 UTC, omeraplak commented on documentation/docs/examples/authentication/headless.md
> +example-tags: [headless,authentication,react-hook-form,react-table]
```suggestion
example-tags: [headless,authentication]
```

2023-05-16 11:13 UTC, omeraplak commented on documentation/docs/examples/authentication/mantine.md
> +example-tags: [mantine,authentication,react-table]
```suggestion
example-tags: [mantine,authentication]
```

2023-05-16 14:27 UTC, omeraplak requested changes

2023-05-16 14:27 UTC, omeraplak commented on documentation/docs/examples/table/handsontable/basic.md
> +example-tags: [table,handsontable]
```suggestion
example-tags: [table]
```

2023-05-16 14:27 UTC, omeraplak commented on documentation/docs/examples/themes/refine-themes-chakra-ui.md
> +example-tags: [chakra-ui,customization,theme]
```suggestion
example-tags: [chakra-ui,customization]
```

2023-05-17 07:30 UTC, omeraplak commented on documentation/docs/examples/web3/signin-ethereum.md
> +example-tags: [web3,auth-provider]
```suggestion
example-tags: [auth-provider]
```

2023-05-17 10:52 UTC, BatuhanW commented on documentation/docs/examples/audit-log/audit-log-antd.md
> +example-tags: [audit-log,antd]
Do we need antd here? Audit log may not be specific to antd.

2023-05-17 10:52 UTC, BatuhanW commented on documentation/docs/examples/base/mui-base.md
> +example-title: Material UI
```suggestion
title: Material UI
example-title: Material UI Base
```

2023-05-17 10:52 UTC, BatuhanW commented on documentation/docs/examples/import-export/antd.md
> +example-tags: [import,export]
We have similar example for useImport says headless, maybe we can use another tag for both, like csv? import. export isn't clear enough on what's being imported.

2023-05-17 10:52 UTC, BatuhanW reviewed
Added some comments.

2023-05-17 11:14 UTC, yildirayunlu commented on documentation/docs/examples/audit-log/audit-log-antd.md
> +example-tags: [audit-log,antd]
We have an [`antd-audit-log`](https://github.com/refinedev/refine/tree/next/packages/antd-audit-log) package. We used this example.

2023-05-17 13:09 UTC, BatuhanW approved these changes

2023-05-17 14:01 UTC, yildirayunlu commented on documentation/src/components/example-list/index.tsx
> -    vite: "#646cff",
No, because many of our examples are Vite.

2023-05-18 10:42 UTC, omeraplak approved these changes

2023-05-18 10:43 UTC, aliemir approved these changes

2023-05-18 11:42 UTC, merged