feat: add `useLoadingOvertime` hook
refinedev/refine pull request #4523
Opened 2023-06-13 14:42 UTC by yildirayunlu

if you need to do something when the loading time exceeds the specified time, refine provides the `useLoadingOvertime` hook. It returns the elapsed time in milliseconds.

```tsx
const { elapsedTime } = useLoadingOvertime({
   isLoading,
   interval: 5000,
   onInterval(elapsedInterval) {
       console.log("loading overtime", elapsedInterval);
   },
});
```

### Test plan (required)

<img width="712" alt="image" src="https://github.com/refinedev/refine/assets/3484713/a9870336-c320-4a27-9a6a-5b7dc4fbe62c">

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-06-14 11:15 UTC, alicanerdurmaz approved these changes

2023-06-14 11:34 UTC, salihozdemir commented on examples/base-antd/src/App.tsx
> +    const { elapsedTime } = useLoadingOvertime({
Will you create a separate example for this feature?

2023-06-14 11:34 UTC, salihozdemir commented on .changeset/weak-fishes-wave.md
> +});
In my opinion, we should show the `overtime` usage on `<Refine/>` component.

2023-06-14 11:34 UTC, salihozdemir commented on packages/core/src/hooks/useLoadingOvertime/index.ts
> +        undefined,
I think it would be better if the default value is 0
```suggestion
        0,
```

2023-06-14 11:34 UTC, salihozdemir commented on packages/core/src/hooks/useLoadingOvertime/index.spec.tsx
> +    it("should override global interval", () => {
We can also add a test where we define a global interval as "should apply global interval if interval doesn't provided".

2023-06-14 12:10 UTC, yildirayunlu commented on packages/core/src/hooks/useLoadingOvertime/index.spec.tsx
> +    it("should override global interval", () => {
I added a test with `global interval and onInterval run`.

2023-06-14 12:21 UTC, yildirayunlu commented on examples/base-antd/src/App.tsx
> +    const { elapsedTime } = useLoadingOvertime({
A separate example can be made when we integrate it into data hooks. Just for demo for now.

2023-06-14 14:32 UTC, BatuhanW requested changes

2023-06-14 14:32 UTC, BatuhanW commented on packages/core/src/contexts/refine/IRefineContext.ts
> +    overtime?: Omit<UseLoadingOvertimeProps, "isLoading">;
AFAIK, we are providing a default value for `interval`, so it's not optional, this type is wrong because `interval` is optional. We should mark is as required. Some pseudo code for this:

```
Required<Pick<UseLoadingOvertimeProps, "interval">> & Omit<UseLoadingOvertimeProps, "isLoading", "interval">

```

2023-06-14 14:32 UTC, BatuhanW commented on packages/core/src/definitions/helpers/handleRefineOptions/index.spec.ts
> +                interval: 1000,
Are they needed since we already have a default value?

2023-06-14 14:32 UTC, BatuhanW commented on packages/core/src/definitions/helpers/handleRefineOptions/index.spec.ts
> +                interval: 1000,
Maybe we can add assertion about `interval` having a default value of 1000.

2023-06-14 14:32 UTC, BatuhanW commented on packages/core/src/hooks/useLoadingOvertime/index.ts
> +export type IUseLoadingOvertimeOnIntervalContext = UseResourceReturnType;
I think it's too much. We shouldn't return all of the resources array in the context, we better return only relative `resource` object.

2023-06-14 14:32 UTC, BatuhanW commented on packages/core/src/hooks/useLoadingOvertime/index.ts
> +    const onInterval = onIntervalProp ?? overtime?.onInterval;
Related to the review before, this shouldn't be optional, we should have value for sure.

2023-06-14 14:47 UTC, yildirayunlu commented on packages/core/src/contexts/refine/IRefineContext.ts
> +    overtime?: Omit<UseLoadingOvertimeProps, "isLoading">;
@BatuhanW  True, if `overtime` is defined then `interval` should be required.

2023-06-14 14:48 UTC, yildirayunlu commented on packages/core/src/definitions/helpers/handleRefineOptions/index.spec.ts
> +                interval: 1000,
I think there is. Because here we are already checking the default values.

2023-06-14 14:49 UTC, yildirayunlu commented on packages/core/src/definitions/helpers/handleRefineOptions/index.spec.ts
> +                interval: 1000,
Here we do this check.

2023-06-14 14:57 UTC, yildirayunlu commented on packages/core/src/hooks/useLoadingOvertime/index.ts
> +    const onInterval = onIntervalProp ?? overtime?.onInterval;
fixed `interval` is not optional

2023-06-15 06:56 UTC, yildirayunlu commented on packages/core/src/hooks/useLoadingOvertime/index.ts
> +export type IUseLoadingOvertimeOnIntervalContext = UseResourceReturnType;
Only passes `resource` object

2023-06-19 06:39 UTC, alicanerdurmaz approved these changes

2023-06-19 06:45 UTC, BatuhanW approved these changes

2023-06-19 08:48 UTC, aliemir requested changes
In the `onInterval` callback, we're passing a `context` that is not necessarily related to the parent hook since it's only inferred from the router. 

Since this is used in our hooks, we should accept a `context` value (probably in `Record` type) and pass the values we can provide (such as `resource`, `filters`, `meta` in `useList` and `values`, `resource`, `meta` etc. in `useCreate` and similar.)

This way we can give the user a better understanding in `onInterval` callback. (At least a correct one) 

Example: 

```tsx
const overtime = useLoadingOvertime({
  context: { meta, resource, values },
});
```

2023-06-19 15:10 UTC, BatuhanW commented on packages/core/src/contexts/refine/IRefineContext.ts
> +        Required<Pick<UseLoadingOvertimeCoreProps, "interval">>;
Maybe we can move this type definition to `packages/core/src/hooks/useLoadingOvertime/index.ts` and use it from there.

2023-06-19 18:00 UTC, aliemir approved these changes

2023-06-19 18:02 UTC, aliemir requested changes
In the documentation, can we also add `overtime` to the return values? 💯

2023-06-20 14:18 UTC, aliemir commented on documentation/docs/api-reference/core/hooks/data/useCreateMany/index.md
> +const { overtime } = useCreate();
```suggestion
const { overtime } = useCreateMany();
```

Other hooks also uses the same snippet with `useCreate`, can we change them accordingly?

2023-06-20 14:24 UTC, aliemir requested changes
Noticed some inconsistencies in the documentation. Waiting for their updates and we're good to go!

2023-06-20 15:03 UTC, salihozdemir commented
I didn't find the `useLoadingOvertime` hook. Am I missing something?

2023-06-20 15:37 UTC, aliemir commented
> I didn't find the `useLoadingOvertime` hook. Am I missing something?

We don't have a separate documentation for that and kept it internal for now.

2023-06-20 16:29 UTC, aliemir approved these changes

2023-06-20 21:55 UTC, merged