fix: support multiple `resource` usage with the same name via the `identifier`
refinedev/refine pull request #4527
Opened 2023-06-14 08:41 UTC by salihozdemir

Previously our primitive data hooks(`useList`, `useCreate`, etc.) only worked with resource name. So if you had multiple `resource` usage with the same name, it would cause issues. Now the hooks support `identifier` to distinguish between the resources.

### Test plan (required)

The existing tests are run successfully. Some new tests will be added.

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-06-19 06:49 UTC, yildirayunlu approved these changes

2023-06-19 06:51 UTC, alicanerdurmaz approved these changes

2023-06-19 11:39 UTC, BatuhanW requested changes

2023-06-19 11:39 UTC, BatuhanW commented on .changeset/early-fireants-accept.md
> +Previously our primitive data hooks(`useList`, `useCreate`, etc.) only worked with resource name. So if you had multiple `resource` usage with the same name, it would cause issues. Now the hooks supp
Even though the term `primitive data hooks` is clear for us, it may not be clear for everyone, let's make a list of these refactored hooks and add a sentence like, `following hooks now respects identifier` etc..

2023-06-19 11:39 UTC, BatuhanW commented on packages/antd/src/components/buttons/delete/index.tsx
> +    const resourceIdentifierOrName = resource?.identifier ?? resource?.name;
How do you feel about moving this one into the `useResource` hook itself, since it's repetitive everywhere?

Let's expose `identifier` key from useResource hook and use it everywhere.

```tsx
const { identifier } = useResource(...)
```

2023-06-19 11:39 UTC, BatuhanW commented on packages/core/src/components/canAccess/index.tsx
> +    const { resource: inferedResource } = useResource();
```suggestion
    const { resource: inferredResource } = useResource();
```

2023-06-19 11:39 UTC, BatuhanW commented on packages/core/src/components/canAccess/index.tsx
> +            resourceFromProp !== inferedResource?.name
Once we export `identifier` from `useResource`, we can simplify this condition:

```
resourceFromProp && resourceFromProp !== identifier
```

2023-06-19 15:06 UTC, BatuhanW commented on packages/core/src/hooks/data/useCreateMany.ts
> +            resource: resourceName,
🥇

2023-06-19 15:07 UTC, BatuhanW commented on packages/core/src/hooks/data/useCreateMany.ts
> +                    resource: resource.name,
Shouldn't we use identifier here too?

2023-06-20 07:12 UTC, salihozdemir commented on packages/chakra-ui/src/components/crud/list/index.tsx
> +                    `${identifier}.titles.list`,
Added the changesets 👍

2023-06-20 07:18 UTC, BatuhanW commented on packages/core/src/components/canAccess/index.tsx
>          resource: resourceFromProp ?? resource?.name,
Just to give context on decision, we are using identifier internally to find resource, communication with outside providers should be through name.

2023-06-20 14:50 UTC, BatuhanW requested changes
Let's add a warning about possible i18n issue, since we are using `identifier` now, instead of resource name.

2023-06-21 06:49 UTC, BatuhanW approved these changes

2023-06-21 06:51 UTC, yildirayunlu approved these changes

2023-06-21 08:47 UTC, aliemir commented on packages/core/src/hooks/form/useForm.ts
> +                        resource: identifier ?? resource.name,
As I can see, `identifier` satisfies both the `identifier` value and the `name`. Do we need the extra `?? resource.name` here? 🤔 Or do we have a type issue that requires us to do this? @salihozdemir

2023-06-21 08:48 UTC, aliemir commented on packages/core/src/hooks/form/useForm.ts
> +            resource: identifier ?? resource.name,
Same as above

2023-06-21 08:54 UTC, salihozdemir commented on packages/core/src/hooks/form/useForm.ts
> +                        resource: identifier ?? resource.name,
Actually, this is not a type problem. If `useResource` takes a parameter, `identifier` is always a string. However, if `useResource` takes a value `undefined | string`, there is a possibility that `identifier` is undefined. So, we need to add `??` in here.

2023-06-21 08:55 UTC, salihozdemir commented on packages/core/src/hooks/form/useForm.ts
> +            resource: identifier ?? resource.name,
Same answer above :)

2023-06-21 09:00 UTC, aliemir approved these changes

2023-06-21 09:00 UTC, aliemir commented on packages/core/src/hooks/form/useForm.ts
> +                        resource: identifier ?? resource.name,
Thank you

2023-06-21 09:01 UTC, merged