feat: comminity numbers made dynamic
refinedev/refine pull request #4556
Opened 2023-06-20 10:12 UTC by yildirayunlu

feat: comminity numbers made dynamic

No API found for `Contributors` and `Twitter Followers` numbers. I'm open to suggestions 🚀   

<img width="1211" alt="image" src="https://github.com/refinedev/refine/assets/3484713/57074011-7c52-4e76-95fc-ef54aef8aac0">

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-06-20 13:11 UTC, BatuhanW requested changes

2023-06-20 13:11 UTC, BatuhanW commented on documentation/src/context/CommunityNumber/index.tsx
> +export const CommunityNumberProvider: FC = ({ children }) => {
```suggestion
export const CommunityStatsProvider: FC = ({ children }) => {
```

2023-06-21 06:52 UTC, alicanerdurmaz approved these changes

2023-06-21 07:31 UTC, BatuhanW requested changes

2023-06-21 07:31 UTC, BatuhanW commented on documentation/src/refine-theme/landing-github-star-button.tsx
> +    const short = `${Math.floor((githubStarCount ?? 0) / 1000)}k`;
```suggestion
    const short = `${Math.floor((githubStarCount ?? 0) / 1000).toFixed(1)}k`;
```

2023-06-21 07:47 UTC, BatuhanW approved these changes

2023-06-21 08:06 UTC, merged