fix: i18n persist language for `inferencer-chakra-ui` and `inferencer-mantine`
refinedev/refine pull request #4562
Opened 2023-06-21 09:53 UTC by yildirayunlu

i18n persist language for `inferencer-chakra-ui` and `inferencer-mantine`

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-06-21 13:55 UTC, alicanerdurmaz approved these changes

2023-06-21 13:55 UTC, alicanerdurmaz commented on examples/inferencer-mantine/cypress/e2e/all.cy.ts
> +    it.only("should change language", () => {
```suggestion
    it("should change language", () => {
```

2023-06-22 09:32 UTC, BatuhanW requested changes

2023-06-22 09:32 UTC, BatuhanW commented on examples/inferencer-chakra-ui/cypress/e2e/all.cy.ts
> +        cy.wait("@getCategories");
This was causing flaky results on @alicanerdurmaz's tests. Should we remove it? I think it's sufficient to just wait for blog posts.

2023-06-22 09:53 UTC, BatuhanW approved these changes

2023-06-23 08:11 UTC, merged