feat: add ability to text transformers via `options`
refinedev/refine pull request #4568
Opened 2023-06-21 12:39 UTC by salihozdemir

By default, **refine** uses the following packages to transform some strings:
- [plurize](https://www.npmjs.com/package/pluralize)
- [humanize-string](https://www.npmjs.com/package/humanize-string)

In some languages other than English, these transformations could cause problems. So, this PR provides a solution for this.

``` tsx
<Refine options={{
    textTransformers: {
          humanize: (word) => handleHumanize(word),
          plural: (word) => handlePlurize(word),
          singular: (word) => handleSingularize(word),
      }
  }} 
/>
```

### Test plan (required)

WIP:

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-06-21 13:36 UTC, BatuhanW commented on documentation/docs/api-reference/core/components/refine-config.md
> +            textTransformers: {
I think it would be much better to have `disabled` boolean option, defaults to false.

So users can easier disable all transformations, without defining all the functions repetitively.

2023-06-21 13:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/components/refine-config.md
> +        ...
```suggestion
        // ...
```

2023-06-21 13:45 UTC, BatuhanW commented on .changeset/lucky-dingos-roll.md
> +        ...
```suggestion
        // ...
```

Without making it comment, formatting doesn't work for codeblocks. I think it's nice to have formatting in these code-blocks, so we can understand if we've made a typo in general.

2023-06-21 13:45 UTC, BatuhanW commented on packages/core/src/hooks/breadcrumb/index.ts
> +    const { textTransformers } = options;
😄  Nitpick: 

```suggestion
    const { options: { textTransformers } } = useRefineContext();
```

2023-06-22 10:10 UTC, salihozdemir commented on documentation/docs/api-reference/core/components/refine-config.md
> +            textTransformers: {
@aliemir What do you think about it?

2023-06-23 08:14 UTC, aliemir commented on documentation/docs/api-reference/core/components/refine-config.md
> +            textTransformers: {
These transformations are already used in the core package and the ability we provide with this PR is not for a customization on the raw values but an extension to the transformations. I'm not sure if it will be anywhere useful to disable them.

2023-06-23 12:29 UTC, BatuhanW requested changes

2023-06-23 12:29 UTC, BatuhanW commented on packages/react-router-v6/src/document-title-handler.tsx
> +            action === "list" ? "plural" : "singular",
This change didn't fail any spec. Let's add some tests.

2023-06-23 12:52 UTC, salihozdemir commented on packages/react-router-v6/src/document-title-handler.tsx
> +            action === "list" ? "plural" : "singular",
We don't have any test environment in router packages. So, we didn't test it

2023-06-23 12:56 UTC, salihozdemir commented on packages/react-router-v6/src/document-title-handler.tsx
> +            action === "list" ? "plural" : "singular",
Also, this change does not cause any perpetrators. Because `getUserFriendlyName` already does `capitalize`.

2023-06-23 13:18 UTC, BatuhanW approved these changes

2023-06-23 13:32 UTC, merged