feat: `autoSave` for edit pages
refinedev/refine pull request #4591
Opened 2023-06-23 13:27 UTC by yildirayunlu

```
const { autoSaveProps } = useForm<IPost>({
  warnWhenUnsavedChanges: true,
  autoSave: true,
});
```

```
//...
return (
  <Edit
      saveButtonProps={saveButtonProps}
      headerButtons={<AutoSaveIndicator {...autoSaveProps} />}
  >
//..
```

![Kapture 2023-06-23 at 16 26 00](https://github.com/refinedev/refine/assets/3484713/241f8fea-1b8f-470f-af9e-cd3bffdd06ed)

### Test plan (required)

TODO:

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-07-05 16:32 UTC, BatuhanW requested changes

2023-07-05 16:32 UTC, BatuhanW commented on documentation/docs/api-reference/antd/components/auto-save-indicator.md
> +`<AutoSaveIndicator>` component from **refine** for **Ant Design** contains logic for showing `autosave` feature.
```suggestion
`<AutoSaveIndicator>` component from **refine** for **Ant Design** can be used to communicate auto-save status to the user. 
```

2023-07-05 16:32 UTC, BatuhanW commented on documentation/docs/api-reference/antd/hooks/form/useDrawerForm.md
> +})
Let's wrap auto-save related props into some object.

2023-07-05 16:32 UTC, BatuhanW commented on documentation/docs/api-reference/antd/hooks/form/useModalForm.md
> +If open [`autosave`](#autosave) prop, `autoSaveProps` object is returned from this hook. `autoSaveProps` object has `data`, `error` and `status` properties. `data` is the data returned from the mutat
If auto-save is enabled, this hook will return `autoSaveProps` with data, error, status fields from auto-save mutation...

We can rephrase this sentence.

2023-07-05 16:32 UTC, BatuhanW commented on documentation/docs/api-reference/antd/hooks/form/useStepsForm.md
> +If you want to save the form automatically, you can pass the `autoSave` prop to the this hook. It is useful when you want to save the form automatically when the user changes the form values.
```suggestion
If you want to save the form automatically after some time when user edits the form, you can pass the `autoSave` prop to the this hook. 
```

2023-07-05 16:32 UTC, BatuhanW commented on packages/core/src/interfaces/autoSave.ts
> +    autoSave?: boolean;
```suggestion
    enabled?: boolean;
```

2023-07-05 16:32 UTC, BatuhanW commented on packages/core/src/interfaces/autoSave.ts
> +    autoSaveDebounce?: number;
```suggestion
    debounceDuration?: number;
```

2023-07-06 10:53 UTC, BatuhanW commented on documentation/docs/api-reference/antd/components/basic-views/edit.md
> +render(
Can you check if this example is working? Seems we are missing some imports here. I think it can't be rendered correctly.

2023-07-06 10:53 UTC, BatuhanW commented on documentation/docs/api-reference/antd/hooks/form/useDrawerForm.md
> +If you want to save the form automatically after some time when user edits the form, you can pass the `autoSave` prop to the this hook.
```suggestion
If you want to save the form automatically after some delay when user edits the form, you can pass true to `autoSave.enabled` prop.
```

2023-07-06 10:53 UTC, BatuhanW commented on documentation/docs/api-reference/antd/hooks/form/useDrawerForm.md
> +If `autoSave` prop is enabled, the hook returns an `autoSaveProps` object with `data`, `error`, and `status` properties. `data` holds the mutation's returned data, `error` stores any returned error,
```suggestion
If `autoSave` is enabled, this hook returns `autoSaveProps` object with `data`, `error`, and `status` properties from mutation.
```

2023-07-06 11:13 UTC, yildirayunlu commented on documentation/docs/api-reference/antd/components/basic-views/edit.md
> +render(
This example is working. Some imports are used from the `shared` section.

https://64a68f1889cb60060210f7c0--refine-doc-preview.netlify.app/docs/api-reference/antd/components/basic-views/edit/#autosaveprops

2023-07-06 13:30 UTC, BatuhanW commented on packages/core/src/hooks/form/useForm.ts
> +        autoSaveProps: {
Since we are returning this one, WDYT about calling it something like `autoSaveResponse` or `autoSaveResult`?

2023-07-06 14:37 UTC, BatuhanW commented on packages/mui/src/components/crud/edit/index.spec.tsx
> +                    }),
Can we also test error case?

2023-07-06 14:37 UTC, BatuhanW commented on packages/react-hook-form/src/useForm/index.ts
> +     * onFinish is override when `autoSave` is on
Are we ignoring `onFinish` when autoSave is enabled? If that's so, I think we can rephrase this one to something like `onFinish is overriden by this function when autoSave is enabled.`

2023-07-06 14:37 UTC, BatuhanW commented on packages/mui/src/components/crud/edit/index.spec.tsx
> +                jest.advanceTimersByTime(1100);
I'm confused by this one. So we are returning response 1000ms later, this means when we advance time by 1100 ms, we should e returned response already. So it should be on `saved` state, no?

2023-07-06 14:37 UTC, BatuhanW commented on packages/mantine/src/components/crud/edit/index.spec.tsx
> +                    // debounce: 500,
Let's remove if not needed.

2023-07-06 14:37 UTC, BatuhanW commented on packages/core/src/hooks/form/useForm.ts
> +    const mutationAutoSave = useUpdate<TResponse, TResponseError, TVariables>(
```suggestion
    const autoSaveMutation = useUpdate<TResponse, TResponseError, TVariables>(
```

I think it's slightly better.

2023-07-07 08:50 UTC, yildirayunlu commented on packages/react-hook-form/src/useForm/index.ts
> +     * onFinish is override when `autoSave` is on
This prop move `autoSave` object. Usage is as follows: 

```tsx
useForm({
      autoSave: {
          enabled: true,
          // highlight-start
          onFinish: (values) => {
              return {
                  foo: "bar",
                  ...values,
              };
          },
          // highlight-end
      },
})
```

2023-07-07 08:52 UTC, yildirayunlu commented on packages/mui/src/components/crud/edit/index.spec.tsx
> +                jest.advanceTimersByTime(1100);
It is not yet in the `saving...` state as the default `debounce` is 1000 ms.

2023-07-11 11:46 UTC, BatuhanW approved these changes

2023-07-12 06:28 UTC, aliemir approved these changes

2023-07-12 07:27 UTC, alicanerdurmaz approved these changes

2023-07-12 07:28 UTC, salihozdemir approved these changes

2023-07-12 12:04 UTC, merged