docs: fix live-previews where the `goBack` prop doesn't work
refinedev/refine pull request #4593
Opened 2023-06-23 14:35 UTC by salihozdemir

Fixed live-previews where the `goBack` prop doesn't work.

2023-06-23 15:06 UTC, BatuhanW requested changes

2023-06-23 15:06 UTC, BatuhanW commented on documentation/docs/api-reference/chakra-ui/components/basic-views/show.md
> +setInitialRoutes(["/posts", "/posts/edit/123"]);
Are we sure about this one? Example is `show` but we have `edit` route here.

2023-06-25 13:57 UTC, aliemir commented on documentation/docs/api-reference/mui/components/basic-views/show.md
> +import { useNavigation } from "@refinedev/core";
We should use `useBack` for this implementation.

2023-06-26 07:06 UTC, alicanerdurmaz approved these changes

2023-06-26 08:10 UTC, salihozdemir commented on documentation/docs/api-reference/mui/components/basic-views/show.md
> +import { useNavigation } from "@refinedev/core";
fixed 🚀

2023-06-26 10:21 UTC, aliemir approved these changes

2023-06-26 10:22 UTC, BatuhanW approved these changes

2023-06-26 12:26 UTC, merged