docs: add useGenerated community data provider
refinedev/refine pull request #4595
Opened 2023-06-23 20:22 UTC by usegen

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-06-23 20:25 UTC, usegen commented
@BatuhanW  I have opened this one with the commit convention

2023-06-25 13:41 UTC, aliemir approved these changes

2023-06-25 13:42 UTC, BatuhanW requested changes
Asked for minor changes, as we aren't officially supporting useGenerated, it would make more sense to include it into `Community Packages` section and remove it from overview.

Additionally, you can also create pr against awesome-refine repository and include your project there too!

https://github.com/refinedev/awesome-refine#community-packages-%EF%B8%8F

2023-06-25 13:42 UTC, BatuhanW commented on documentation/src/assets/integration-icons/usegenerated.tsx
> +    <defs><g /><clipPath id="c8a4d14669"><path d="M 265.109375 158.496094 L 280.585938 158.496094 L 280.585938 216.539062 L 265.109375 216.539062 Z M 265.109375 158.496094 " clip-rule="nonzero" /></c
Can we compress this one?

2023-06-25 13:42 UTC, BatuhanW commented on documentation/docs/getting-started/overview.md
> +🔌 Connectors for **15+ backend services** including [REST API](https://github.com/refinedev/refine/tree/master/packages/simple-rest), [GraphQL](https://github.com/refinedev/refine/tree/master/package
Hey @usegen can we move this to `Commmunity Packages` section and remove it from here? 

https://github.com/refinedev/refine/blob/e6ca248fafc2597c6ad69e598bd21b96a1cd1a27/documentation/docs/packages/list-of-packages.md#L86

2023-06-26 09:40 UTC, usegen commented on documentation/docs/getting-started/overview.md
> +🔌 Connectors for **15+ backend services** including [REST API](https://github.com/refinedev/refine/tree/master/packages/simple-rest), [GraphQL](https://github.com/refinedev/refine/tree/master/package
@BatuhanW sure!

2023-06-26 09:41 UTC, usegen commented on documentation/src/assets/integration-icons/usegenerated.tsx
> +    <defs><g /><clipPath id="c8a4d14669"><path d="M 265.109375 158.496094 L 280.585938 158.496094 L 280.585938 216.539062 L 265.109375 216.539062 Z M 265.109375 158.496094 " clip-rule="nonzero" /></c
yes

2023-06-26 10:34 UTC, usegen commented
@BatuhanW  I have pushed the changes both for compressing the SVG9let me know if it's enough)  and moving the useGenerated from overview to `Community Packages`

2023-06-26 12:22 UTC, aliemir commented on documentation/versioned_docs/version-3.xx.xx/getting-started/overview.md
> +🔌 Connectors for **15+ backend services** including [REST API](https://github.com/refinedev/refine/tree/master/packages/simple-rest), [GraphQL](https://github.com/refinedev/refine/tree/master/package
```suggestion
🔌 Connectors for **15+ backend services** including [REST API](https://github.com/refinedev/refine/tree/master/packages/simple-rest), [GraphQL](https://github.com/refinedev/refine/tree/master/packages/graphql), [NestJs CRUD](https://github.com/refinedev/refine/tree/master/packages/nestjsx-crud), [Airtable](https://github.com/refinedev/refine/tree/master/packages/airtable), [Strapi](https://github.com/refinedev/refine/tree/master/packages/strapi), [Strapi v4](https://github.com/refinedev/refine/tree/master/packages/strapi-v4), [Strapi GraphQL](https://github.com/refinedev/refine/tree/master/packages/strapi-graphql), [Supabase](https://github.com/refinedev/refine/tree/master/packages/supabase), [Hasura](https://github.com/refinedev/refine/tree/master/packages/hasura), [Appwrite](https://github.com/refinedev/refine/tree/master/packages/appwrite), [Firebase](https://firebase.google.com/) and [Directus](https://directus.io/).
```

Updated to match the current version

2023-06-26 15:39 UTC, BatuhanW approved these changes

2023-06-26 15:39 UTC, merged