feat(core): update optimistic specs for data and useForm hooks
refinedev/refine pull request #4605
Opened 2023-06-25 18:39 UTC by BatuhanW

Updated "optimistic" scenario tests for following hooks:
- useUpdate
- useUpdateMany
- useDelete
- useDeleteMany
- useForm

2023-06-26 10:18 UTC, salihozdemir requested changes

2023-06-26 10:18 UTC, salihozdemir commented on packages/core/src/hooks/form/useForm.spec.tsx
> +            const { result: useOneResult } = renderHook(
You can also add `useManyResult`

2023-07-03 10:46 UTC, salihozdemir approved these changes

2023-07-03 10:46 UTC, salihozdemir commented on packages/core/src/hooks/data/useUpdateMany.ts
> +                if (mutationModePropOrContext !== "pessimistic") {
Somebody really needed to fix this 😅

2023-07-03 16:25 UTC, aliemir approved these changes

2023-07-03 16:36 UTC, merged