feat: add server-side validation to useForm
refinedev/refine pull request #4652
Opened 2023-07-10 14:59 UTC by alicanerdurmaz

After triggering the `onMutationError` callback, `useForm` will automatically set the thrown errors to the corresponding form fields.
From now, when the `dataProvider` throws an `HttpError` with an `errors` field, the form will display the errors in the appropriate fields. With this feature, users can handle server-side validation errors out-of-the-box.

- Material UI and Chakra UI examples are added
- Mantine example is added
- Ant Design example is added

> [Documentation Link](https://refine.dev/docs/advanced-tutorials/forms/server-side-form-validation/)

### Test plan (required)

Tests are added for new features.

![image](https://github.com/refinedev/refine/assets/23058882/9b2b5001-b5ee-4abd-bfdc-0890717d2db6)

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-07-13 11:21 UTC, BatuhanW commented on .changeset/gentle-crabs-cough.md
> +feat: After the `onMutationError` callback is triggered, `useForm` will automatically set the thrown errors to the corresponding form fields.
```suggestion
feat: When `onMutationError` callback is triggered, `useForm` will automatically assign errors to the corresponding form fields.
```

Should we mention about `errors` field? We mention it in the next paragraph, looks like duplicated tho. Maybe we can merge 2 sentences.

2023-07-13 11:21 UTC, BatuhanW commented on .changeset/good-files-attend.md
> +```
Should we add an example error with fields to demonstrate?

2023-07-13 11:21 UTC, BatuhanW commented on .changeset/new-suits-ring.md
> +From know, when the `dataProvider` throws an `HttpError` with an `errors` field, the form will display the errors in the appropriate fields. With this feature users can handle server-side validation
Let's change this one too when we re-phrase changelog about mantine.

2023-07-13 11:21 UTC, BatuhanW commented on documentation/docs/advanced-tutorials/forms/partials/_mantine-server-side-form-validation.md
> +                message: "Update is not supported in this example.",
I think this error is misleading. We can use some generic message like `Error updating record` or something like that.

2023-07-13 11:21 UTC, BatuhanW commented on documentation/docs/advanced-tutorials/forms/server-side-form-validation.md
> +It requires that the `dataProvider` returning rejected promise with the following shape:
```suggestion
It expects `dataProvider` to return rejected promise with the following shape:
```

2023-07-13 11:21 UTC, BatuhanW commented on documentation/docs/advanced-tutorials/forms/server-side-form-validation.md
> +When the `dataProvider` returns rejected promise with [`errors`][http-error] field, the `useForm` hook will set the [`errors`][http-error] state with the `errors` returned from the `dataProvider`.
```suggestion
When the `dataProvider` returns a rejected promise with [`errors`][http-error] field, `useForm` hook will assign [`errors`][http-error] to the respective form fields.
```

2023-07-13 11:21 UTC, BatuhanW commented on documentation/docs/examples/form/antd/serverSideFormValidation.md
> +You can make server-side form validation out-of-the-box with [Ant Design useForm][antd-use-form].
```suggestion
You can handle server-side form validation errors out-of-the-box with [Ant Design useForm][antd-use-form].
```

2023-07-13 11:21 UTC, BatuhanW commented on documentation/docs/examples/form/mantine/serverSideFormValidation.md
> +You can make server-side form validation out-of-the-box with [Mantine useForm][mantine-use-form].
It gives an impressions that we are doing server-side validation, in fact, we are handling validation errors coming from the server side.

2023-07-14 11:40 UTC, yildirayunlu requested changes

2023-07-14 11:40 UTC, yildirayunlu commented on documentation/docs/api-reference/mantine/hooks/form/useForm.md
> +# <<<<<<< HEAD
```suggestion
```

2023-07-14 11:43 UTC, salihozdemir commented on examples/server-side-form-validation-antd/index.html
> +        <link rel="apple-touch-icon" href="/logo192.png" />
```suggestion
```

2023-07-14 11:45 UTC, salihozdemir commented on examples/server-side-form-validation-antd/public/manifest.json
> +  "name": "refine base example",
```suggestion
  "short_name": "refine server-side validation Ant Design example",
  "name": "refine server-side validation Ant Design example",
```

2023-07-14 11:49 UTC, yildirayunlu requested changes

2023-07-14 11:49 UTC, yildirayunlu commented on examples/server-side-form-validation-material-ui/package.json
> +    "cross-env": "^7.0.3",
```suggestion
```

2023-07-14 11:49 UTC, salihozdemir commented on examples/server-side-form-validation-antd/src/pages/posts/create.tsx
> +    });
```suggestion
    const { formProps, saveButtonProps } = useForm<IPost>();
```

2023-07-14 11:49 UTC, salihozdemir commented on examples/server-side-form-validation-antd/src/pages/posts/edit.tsx
> +    });
```suggestion
    >();
```
By default, it is already `true`

2023-07-14 11:49 UTC, salihozdemir commented on examples/server-side-form-validation-chakra-ui/index.html
> +        />
```suggestion
        
```

2023-07-14 11:51 UTC, salihozdemir commented on examples/server-side-form-validation-mantine/index.html
> +        />
```suggestion

```

2023-07-14 13:04 UTC, BatuhanW approved these changes

2023-07-18 07:00 UTC, yildirayunlu approved these changes

2023-07-18 07:02 UTC, merged