refactor: migrate refine4 on `/blog/react-admin-tutorial`
refinedev/refine pull request #4682
Opened 2023-07-19 09:45 UTC by yildirayunlu

Migrate refine4 on [`/blog/react-admin-tutorial`](https://refine.dev/blog/react-admin-tutorial)`

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-07-19 12:57 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
>  -   **Resources** A [resources](https://refine.dev/docs/tutorial/understanding-resources/index/) is a fundamental component of a refine application. A resource acts as a bridge between the Data/API l
```suggestion
-   **Resources**: A [resources](https://refine.dev/docs/tutorial/understanding-resources/index/) is a fundamental component of a refine application. A resource acts as a bridge between the Data/API layer and the Document/Page Layer. A resource enables the application's pages to interact with the API.
```

2023-07-19 12:57 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
>  -   **DataProvider**: a data provider enables a refine application connect to an external API or service. A dataProvider sends HTTP requests and receives responses via predefined methods.
```suggestion
-   **DataProvider**: Data provider enables a refine application to connect to an external API or service. A `dataProvider` sends HTTP requests and receives responses via predefined methods.
```

2023-07-19 12:57 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
> +-   Now let's define the `<Route>` corresponding to the actions we have created. We should not forget that the path in the resource definition and the path in the route definition must be the same.
This section is all about explaining-showing the main Refine app concepts. We need to give a brief explanation and link that indicates what Route system is, how it works/how it enables in the refine app.

So, instead of saying, "Let define....", we can briefly explain the route systems like the data provider and resources properties.

2023-07-19 12:57 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
> +To handle scenarios where the user is not authenticated, a `/login` route is created, employing the [`<AuthPage>`](https://refine.dev/docs/api-reference/chakra-ui/components/chakra-auth-page/) compon
```suggestion
To handle scenarios where a user is not authenticated, we've established a `/login` route. This utilizes the [`<AuthPage>`](https://refine.dev/docs/api-reference/chakra-ui/components/chakra-auth-page/) component found in refine UI packages, with the 'type' prop set to "login". This configuration effectively renders the login page.
```

2023-07-19 12:57 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
> +```tsx title="src/App.tsx"
To make article more readable, we can remove this codeblock and explain the Routes system on the codeblock above.

2023-07-19 12:57 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
>  ## Utilizing the Strapi v4 Provider in refine
I think we no longer need to "Setting AuthProvider" section. Since it's already fixed on v4.

2023-07-19 12:57 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
> +To manage authenticated routes the [`<Authenticated>`](https://refine.dev/docs/packages/documentation/routers/react-router-v6/#basic-usage) component is employed, utilizing the [`useIsAuthenticated`]
```suggestion
The [`<Authenticated>`](https://refine.dev/docs/packages/documentation/routers/react-router-v6/#basic-usage) component is used to manage authenticated routes. This component leverages the [`useIsAuthenticated`](https://refine.dev/docs/api-reference/core/hooks/authentication/useIsAuthenticated/) hook to determine the authentication status of the user. It handles redirection and rendering specific elements based on this status through children and `fallback` props.
```

2023-07-19 13:29 UTC, yildirayunlu commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
>  ## Utilizing the Strapi v4 Provider in refine
yes removed this

2023-07-20 12:10 UTC, necatiozmen requested changes

2023-07-20 12:10 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
> +-   To create a resource; define our resources and their action paths, this will inform **refine** to use these paths when generating the breadcrumbs, menus, handling redirections and inferring the c
```suggestion
-   To create a resource; define our resources and their action paths. This will inform **refine** to use these paths when generating the breadcrumbs, menus, handling redirections and inferring the current resource and action. 
In accordance with the path definitions in a resource object, we have to assign a `<Route />` for each path and an element to display at that path.
The `<Route>` corresponding to the created actions is defined. It is important to remember that the path specified in the resource definition should match the `path` specified in the route definition.

[Refer to Router docs for more information](https://refine.dev/docs/packages/documentation/routers/react-router-v6/#usage).
```

2023-07-20 12:10 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
> +The [`<NavigateToResource>`](https://refine.dev/docs/packages/documentation/routers/remix/#navigatetoresource) is a basic component to navigate to a resource page. It is useful when you want to navig
```suggestion
The [`<NavigateToResource>`](https://refine.dev/docs/packages/documentation/routers/react-router-v6/#navigatetoresource) is a basic component to navigate to a resource page. It is useful when you want to navigate to a resource page from the index route of your app.
```

2023-07-20 12:10 UTC, necatiozmen commented on documentation/blog/2023-03-03-ra-chakra-tutorial.md
>      );
So at this point, we need to  explain the Route usage here

2023-07-20 13:50 UTC, necatiozmen approved these changes

2023-07-25 08:59 UTC, merged