fix(antd):  `useModalForm` and `useDrawerForm` sends request twice when `syncWithLocation` is true
refinedev/refine pull request #4772
Opened 2023-08-02 08:51 UTC by alicanerdurmaz

If `syncWithLocation` is enabled, after the modal is opened, `useModalForm` and `useDrawerForm` was making another request because the URL was changing. This issue has been resolved by removing the URL parameters that indicate the modal is open from the `queryKey`.

### Test plan (required)

- e2e tests are updated.
- new unit tests are added.

![image](https://github.com/refinedev/refine/assets/23058882/1fb71dd5-7beb-47c9-9ca5-636593aa104b)

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-08-02 11:37 UTC, yildirayunlu approved these changes

2023-08-03 07:39 UTC, salihozdemir requested changes

2023-08-03 07:39 UTC, salihozdemir commented on packages/antd/src/hooks/form/useDrawerForm/index.spec.tsx
> +        await waitFor(() => expect(mockGetOne.mock.calls.length).toBe(1));
```suggestion
        await waitFor(() => expect(mockGetOne).toBeCalledTimes(1));
```

2023-08-03 07:39 UTC, salihozdemir commented on packages/antd/src/hooks/form/useDrawerForm/index.spec.tsx
> +    });
```suggestion
        expect(mockGetOne.toBeCalledWith(
            expect.objectContaining({
            meta:   expect.not.objectContaining({
            "drawer-posts-edit": expect.any()
            )}
             })
        );
    });
```

The suggestion may won't work however you can try like this

2023-08-04 07:12 UTC, salihozdemir approved these changes

2023-08-04 12:06 UTC, merged