fix(mantine): `useModalForm` sends request twice when  is true
refinedev/refine pull request #4773
Opened 2023-08-02 08:55 UTC by alicanerdurmaz

If `syncWithLocation` is enabled, after the modal is opened, `useModalForm` was making another request because the URL was changing. This issue has been resolved by removing the URL parameters that indicate the modal is open from the `queryKey`.

### Test plan (required)

- e2e tests are updated.
- new unit tests are added.

![image](https://github.com/refinedev/refine/assets/23058882/0b769105-6107-4c19-9222-7694e643c452)

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-08-03 07:42 UTC, salihozdemir requested changes

2023-08-03 07:42 UTC, salihozdemir commented on packages/mantine/src/hooks/form/useModalForm/index.spec.tsx
> +        await waitFor(() => expect(result.current.modal.visible).toBe(true));
You can apply for the #4772 reviews in here

2023-08-04 07:03 UTC, yildirayunlu approved these changes

2023-08-04 07:20 UTC, salihozdemir approved these changes

2023-08-04 12:05 UTC, merged