fix(antd): `<RefreshButton />` does not work
refinedev/refine pull request #4775
Opened 2023-08-02 13:12 UTC by alicanerdurmaz

WIP

### Test plan (required)

WIP

### Closing issues

closes #4618

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-08-04 07:18 UTC, salihozdemir requested changes

2023-08-04 07:18 UTC, salihozdemir commented on packages/antd/src/components/buttons/refresh/index.tsx
> +            }}
```suggestion
            onClick={(e) => (onClick ? onClick(e) : refetch())}
```

This may be caused an issue, for users who previously passed `onClick`.

2023-08-04 12:15 UTC, salihozdemir commented on packages/ui-tests/src/tests/buttons/refresh.tsx
> +}));
Did not `jest.spyOn` work?

2023-08-04 12:17 UTC, salihozdemir commented on packages/chakra-ui/src/components/buttons/refresh/index.tsx
> +    resourceNameOrRouteName: propResourceNameOrRouteName,
I think we should not rename prop name if is no conflict

2023-08-04 13:15 UTC, aliemir commented on packages/core/src/index.tsx
> +    pickDataProvider,
These exports doesn't have a corresponding changeset for the core package.

2023-08-04 13:16 UTC, aliemir requested changes
I think there's a missing changeset for `@refinedev/core`

2023-08-04 13:26 UTC, aliemir commented on examples/base-material-ui/package.json
> +    "@tanstack/react-query-devtools": "^4.32.1"
Let's remove this

2023-08-04 14:40 UTC, aliemir approved these changes

2023-08-07 06:50 UTC, salihozdemir approved these changes

2023-08-07 06:50 UTC, merged