feat(@refinedev/cli): add "--platform" option to specify project type
refinedev/refine pull request #4833
Opened 2023-08-16 22:02 UTC by mikeyfarina

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-08-17 00:02 UTC, MahirMahdi commented
> **IMPORTANT: Please do not create a Pull Request without creating an issue first.**
> 
> _Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._
> 
> Please provide enough information so that others can review your pull request:
> 
> Explain the **details** for making this change. What existing problem does the pull request solve?
> 
> ### Test plan (required)
> Demonstrate the code is solid. If not, please add `WIP:` in its title.
> 
> ### Closing issues
> closes #4795 
> 
> ### Self Check before Merge
> Please check all items below before review.
> 
> * [ ]  Corresponding issues are created/updated or not needed
> * [ ]  Docs are updated/provided or not needed
> * [ ]  Examples are updated/provided or not needed
> * [ ]  TypeScript definitions are updated/provided or not needed
> * [ ]  Tests are updated/provided or not needed
> * [ ]  Changesets are provided or not needed

2023-08-17 00:04 UTC, MahirMahdi commented
closes #4795

2023-08-17 00:09 UTC, MahirMahdi commented on .changeset/shiny-cooks-push.md
> +add "--platform" option to run, dev, and build to specify which project type to use for the commands
```suggestion
add "--platform" option to start, dev, and build to specify project type externally
```

2023-08-17 00:17 UTC, MahirMahdi requested changes
Looks good to me.

2023-08-17 00:21 UTC, mikeyfarina commented
@MahirMahdi Thank you for the review!

2023-08-17 08:06 UTC, aliemir commented
Hey @mikeyfarina thank you for the PR! 🚀  I'll review & test it soon. @MahirMahdi thank you for the review ❤️

2023-08-17 13:18 UTC, MahirMahdi commented
@aliemir anytime ❤️

2023-08-18 19:35 UTC, mikeyfarina commented
@aliemir @MahirMahdi Anything I can do to help get this into a place where I can utilize it in my project?

2023-08-21 18:40 UTC, mikeyfarina commented
@aliemir @MahirMahdi Hi guys 😁 anything i can do to help get this pr into a state that I can use it in my other repo?

2023-08-21 18:42 UTC, omeraplak approved these changes

2023-08-22 00:48 UTC, MahirMahdi commented
@mikeyfarina I guess you need to wait until it gets merged.

2023-08-22 04:23 UTC, aliemir approved these changes

2023-08-22 04:23 UTC, merged