Add refine-daisyUI App
refinedev/refine pull request #4837
Opened 2023-08-17 12:02 UTC by anewman15

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-08-17 12:14 UTC, aliemir commented on examples/blog-refine-daisyui/package.json
> +    "dev": "refine dev",
```suggestion
    "start": "refine dev",
```

2023-08-30 09:08 UTC, aliemir requested changes
Thank you for the good work, I left some comments to the code.

2023-08-30 09:08 UTC, aliemir commented on examples/blog-refine-daisyui/src/pages/products/list.tsx
> +    }));
Why is this needed?

2023-08-30 09:08 UTC, aliemir commented on examples/blog-refine-daisyui/src/pages/products/show.tsx
> +    const { queryResult } = useShow();
We can type the `useShow` with `IProduct` and get the `id` from the data instead of `useResource`

2023-08-30 09:09 UTC, aliemir commented on package-lock.json
I'm not sure if a change is required here.

2023-09-01 02:40 UTC, anewman15 commented on examples/blog-refine-daisyui/src/components/breadcrumb/index.tsx
> +                            <span className="mx-2">{breadcrumb?.icon}</span>
Okay thanks. I merged this :)

2023-09-01 02:41 UTC, anewman15 commented on examples/blog-refine-daisyui/src/components/menu/index.tsx
> +                            </NavLink>
Yes, thanks!

2023-09-01 02:44 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/categories/create.tsx
> +        resetField,
Thanks, changes made

2023-09-01 02:44 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/categories/edit.tsx
> +    const categoriesData = queryResult?.data?.data;
Thanks, removed

2023-09-01 02:47 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/categories/show.tsx
> +    const { queryResult } = useShow();
Yep, thanks!

2023-09-01 02:48 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/categories/show.tsx
> +    const { id } = useResource();
Yep

2023-09-01 02:51 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/products/show.tsx
> +    const { queryResult } = useShow();
Okay, thanks!

2023-09-01 03:10 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/dashboard/index.tsx
> +    };
This is a bit intentional. Ideally I would refactor. I want to keep it inside the same file just for the sake of the flow of the article.

If I refactor outside, it leads me to side notes while explaining. Stuff like open the `src/hooks/ `folder, and you'll see this, it looks like this, it does this and that, etc. In contrast, when it's inside the component, I just refer to it directly.

I will leave readers prompt to refactor it in hooks folder.

I hope It makes sense.

2023-09-01 03:12 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/categories/list.tsx
> +                <div className="join">
The same intention about article flow. I'll keep it for brevity and ask the audience to refactor it.

2023-09-01 12:55 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/dashboard/index.tsx
> +    });
Okay thanks. useList is the King

2023-09-01 14:17 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/products/list.tsx
> +    }));
I was thinking of adding meta values later on. It ended up not useful

2023-09-04 02:33 UTC, anewman15 commented on examples/blog-refine-daisyui/.eslintrc.cjs
Oka, thanks. Removed

2023-09-04 02:33 UTC, anewman15 commented on examples/blog-refine-daisyui/.npmrc
> +strict-peer-dependencies=false
Idk :) I removed

2023-09-04 02:34 UTC, anewman15 commented on examples/blog-refine-daisyui/src/pages/products/edit.tsx
> +    }, [categoryOptions]);
Okay

2023-09-06 07:52 UTC, aliemir commented on examples/blog-refine-daisyui/src/pages/dashboard/index.tsx
> +    };
This makes sense but I meant moving it outside of the component but keeping it in the same file 😅  @anewman15

2023-09-06 07:57 UTC, aliemir commented on examples/blog-refine-daisyui/src/pages/categories/list.tsx
> +                <div className="join">
Makes sense 🚀

2023-09-07 12:20 UTC, aliemir approved these changes

2023-09-07 16:04 UTC, merged