feat(core): add `invalidateOnUnmount` and `invalidateOnClose` prop on `autoSave` feature
refinedev/refine pull request #4903
Opened 2023-09-04 11:34 UTC by yildirayunlu

`autoSave` mutation not invalide when it was successful. Now `list` and `many` queries will be invalidated by default. 

Also added `invalidateOnUnmountDetailCache` prop to work when `unmount`. This prop will invalidate the `detail` query when `true` is set.

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-09-04 12:05 UTC, aliemir commented on packages/core/src/hooks/form/useForm.ts
> +        }
I'm not sure if I can follow what's happening here. I can't see a relation with unmount, how do these lines work? 🤔

2023-09-04 14:48 UTC, alicanerdurmaz requested changes

2023-09-04 14:48 UTC, alicanerdurmaz commented on documentation/docs/api-reference/mantine/hooks/form/useModalForm.md
> +If you want to invalidate the `detail` query cache when the modal is closed, you can set the `invalidateOnUnmountDetailCache` parameter to `true`. Default value is `false`.
I guess this won't work when the modal is closed. In our examples, `useModalForm` is still mounted

2023-09-04 14:48 UTC, alicanerdurmaz commented on documentation/docs/api-reference/mantine/hooks/form/useForm.md
> +If you want to invalidate the `detail` query cache when the form is unmounted, you can set the `invalidateOnUnmountDetailCache` parameter to `true`. Default value is `false`.
```suggestion
If you want to invalidate the `detail` query cache when the `useForm` is unmounted, you can set the `invalidateOnUnmountDetailCache` parameter to `true`. Default value is `false`.
```

2023-09-05 06:23 UTC, yildirayunlu commented on documentation/docs/api-reference/mantine/hooks/form/useModalForm.md
> +If you want to invalidate the `detail` query cache when the modal is closed, you can set the `invalidateOnUnmountDetailCache` parameter to `true`. Default value is `false`.
You are right, here I can update it as follows; `when the `useModalForm` is unmounted`

2023-09-11 06:57 UTC, salihozdemir requested changes

2023-09-11 06:57 UTC, salihozdemir commented on packages/mantine/src/hooks/form/useModalForm/index.ts
> +    const {} = useMantineFormResult;
```suggestion
```

2023-09-11 06:57 UTC, salihozdemir commented on documentation/docs/api-reference/antd/hooks/form/useForm.md
> +If you want to invalidate the `list`, `many` and `detail` queries from the current resource when auto save mutation is successful, you can use the `invalidateOnUnmount` prop. This prop is useful when
Here the before, we should say something like following:

By default the `autoSave` feature does not invalidate queries. If you want to invalidate, you can use the `invalidateOnUnmount` prop.

2023-09-18 13:29 UTC, alicanerdurmaz approved these changes

2023-09-18 14:17 UTC, omeraplak approved these changes

2023-09-19 07:36 UTC, BatuhanW requested changes

2023-09-19 07:36 UTC, BatuhanW commented on .changeset/fast-dodos-think.md
> +feat: `autoSave` mutation not invalide when it mutation successful. Now `list`,`many` and `detail` queries will be invalidated by default. Also added [`invalidateOnUnmount`](https://refine.dev/docs/a
```suggestion
feat: `autoSave` mutation wasn't being invalidated when the mutation is successful. Now `list`,`many` and `detail` queries will be invalidated by default. Also added [`invalidateOnUnmount`](https://refine.dev/docs/api-reference/core/hooks/useForm/#invalidateonunmount) prop to to trigger invalidate on `unmount`. You can use `invalidates` prop to customize it.
```

2023-09-19 07:36 UTC, BatuhanW commented on .changeset/six-parrots-joke.md
> +fix: when using [`useForm`](https://refine.dev/docs/api-reference/antd/hooks/form/useForm/), `autoSave` parameters are passed to `@refinedev/core/useForm` hook.
```suggestion
fix: [`useForm`](https://refine.dev/docs/api-reference/antd/hooks/form/useForm/)'s, `autoSave` parameters not passed to `@refinedev/core/useForm` hook.
```

2023-09-19 11:29 UTC, BatuhanW approved these changes
LGTM 👍🏼 Added minor comments.

2023-09-19 11:29 UTC, BatuhanW commented on .changeset/clever-elephants-decide.md
> +From now, you can use the use this props to invalidate queries upon unmount or close.
```suggestion
From now on, you can use these props to invalidate queries upon unmount and/or close.
```

2023-09-19 11:29 UTC, BatuhanW commented on .changeset/fast-dodos-think.md
> +From now, you can use the [`invalidateOnUnmount`](https://refine.dev/docs/api-reference/core/hooks/useForm/#invalidateonunmount) prop to invalidate queries upon unmount.
```suggestion
From now on, you can use the [`invalidateOnUnmount`](https://refine.dev/docs/api-reference/core/hooks/useForm/#invalidateonunmount) prop to invalidate queries upon unmount.
```

2023-09-19 11:29 UTC, BatuhanW commented on documentation/docs/api-reference/antd/hooks/form/useDrawerForm.md
> +This prop is useful when you want to invalidate the `list`, `many` and `detail` queries from the current resource when the hook is unmounted. By default, it invalidates the `list`, `many` and `detail
Can we also add example about how to use `invalidates` prop if we don't have already?

2023-09-19 15:56 UTC, merged