feat(cli): add command
refinedev/refine pull request #4904
Opened 2023-09-04 12:32 UTC by alicanerdurmaz

feat: added `add` command to add new features to the project
Now you can add a new provider or resource to the project using the command `npm run refine add <arg>`.

-   `npm run refine add resource posts`: will add a new resource to the project with the name `posts`.
-   `npm run refine add auth`: will add a new auth provider to the project.
-   `npm run refine add data`: will add a new data provider to the project.
-   `npm run refine add live`: will add a new live provider to the project.

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-09-04 15:04 UTC, BatuhanW commented on packages/cli/templates/provider/demo-data-provider.tsx
> +        // TODO: send request to the API
Let's add relevant documentation links to all templates.

2023-09-04 20:07 UTC, aliemir commented on packages/cli/templates/provider/demo-auth-provider.tsx
> +export const authProvider: AuthBindings = {
```
/**
 * Check out the Auth Provider documentation for detailed information
 * https://refine.dev/docs/api-reference/core/providers/auth-provider/
**/
```

Maybe we can add something like this in the demo providers 🤔 @alicanerdurmaz

2023-09-05 14:57 UTC, aliemir approved these changes

2023-09-05 17:07 UTC, omeraplak requested changes

2023-09-05 17:07 UTC, omeraplak commented on documentation/docs/packages/documentation/cli.md
> +> npm run refine add live
```suggestion
> npm run refine add live
> npm run refine add i18n
> npm run refine add notification
> npm run refine add accessControl
```
Can we update it for our other options as well?

2023-09-05 17:47 UTC, omeraplak commented
Hey @alicanerdurmaz,
Can we add a test?

2023-09-18 14:15 UTC, omeraplak approved these changes

2023-09-19 11:32 UTC, BatuhanW approved these changes

2023-09-19 15:05 UTC, merged