refine NextUI article demo app
refinedev/refine pull request #4912
Opened 2023-09-05 18:19 UTC by nibble0101

This PR adds the demo app for the refine NextUI article.

2023-09-06 08:28 UTC, alicanerdurmaz commented on examples/blog-refine-nextui/src/components/modal/index.tsx
> +export const DeleteModal: React.FC<DeleteModalPropsI> = ({
is this typo ?

```suggestion
export const DeleteModal: React.FC<IDeleteModalProps> = ({
```

2023-09-06 08:28 UTC, alicanerdurmaz commented on examples/blog-refine-nextui/src/components/table/RecentSalesTable.tsx
> +                console.log(+(rows as Set<string>).values().next().value);
Is this left on purpose?

```suggestion
                
```

2023-09-06 08:28 UTC, alicanerdurmaz commented on examples/blog-refine-nextui/src/pages/products/edit.tsx
> +                console.log("Inside controller", field);
Is this left on purpose?

```suggestion
                console.log("Inside controller", field);
```

2023-09-06 08:28 UTC, alicanerdurmaz commented on examples/blog-refine-nextui/src/pages/products/list.tsx
> +                  console.log(+(rows as Set<string>).values().next().value);
Is this left on purpose?
```suggestion
                  console.log(+(rows as Set<string>).values().next().value);
```

2023-09-06 08:31 UTC, alicanerdurmaz requested changes

2023-09-07 03:55 UTC, nibble0101 commented on examples/blog-refine-nextui/src/components/modal/index.tsx
> +export const DeleteModal: React.FC<DeleteModalPropsI> = ({
I've made the requested changes.

2023-09-07 09:07 UTC, alicanerdurmaz approved these changes

2023-09-18 16:21 UTC, merged