feat(core): add `optimisticUpdateMap` prop on `useUpdate`, `useUpdateMany` and `useForm`
refinedev/refine pull request #4914
Opened 2023-09-06 06:57 UTC by yildirayunlu

If the mutation mode is defined as `optimistic` the `useUpdate` hook will automatically update the cache without waiting for the response from the server. You may want to disable or customize this behavior. You can do this by passing the `optimisticUpdateMap` prop.

`list`, `many` and `detail` are the keys of the `optimisticUpdateMap` object. For automatically updating the cache, you should pass the `true`. If you want not update the cache, you should pass the `false`.

```tsx
const { mutate } = useUpdate();

mutate({
    //...
    mutationMode: "optimistic",
    optimisticUpdateMap: {
        list: true,
        many: true,
        detail: false,
    },
});
```
For `useForm`:

```tsx
const { formProps, saveButtonProps } = useForm({
        mutationMode: "optimistic",
        optimisticUpdateMap: {
            list: true,
            many: true,
            detail: (previous, values, id) => {
                if (!previous) {
                    return null;
                }

                const data = {
                    id,
                    ...previous.data,
                    ...values,
                    foo: `bar-one`,
                };

                return {
                    ...previous,
                    data,
                };
            },
        },
    });
```

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-09-06 14:58 UTC, yildirayunlu commented on .changeset/metal-flies-double.md
> +        optimisticUpdateMap: {
I renamed it. I added a section in the document that it will only work in `optimistic` mode.

2023-09-11 09:12 UTC, salihozdemir requested changes

2023-09-11 09:12 UTC, salihozdemir commented on packages/core/src/interfaces/query-cache-update-map.ts
> +export type OptimisticUpdateManyMapType<TData, TVariables> = {
```suggestion
QueryCacheUpdateManyMapType<TData, TVariables> = {
```

2023-09-11 09:12 UTC, salihozdemir commented on packages/core/src/hooks/data/useUpdate.ts
> +                                    );
```suggestion
                                    return queryCacheUpdateMap.detail(
                                        previous,
                                        values,
                                        id
                                    );
```
We can also return `id`.

2023-09-11 09:12 UTC, salihozdemir commented on documentation/docs/api-reference/core/hooks/data/useUpdateMany/index.md
> +This feature is only work with the `mutationMode` set to `optimistic`.
```suggestion
This feature is only work with the `mutationMode` set to `optimistic` and `undoable`.
```

2023-09-11 09:12 UTC, salihozdemir commented on documentation/docs/api-reference/core/hooks/data/useUpdateMany/index.md
> +If the mutation mode is defined as `optimistic` the `useUpdateMany` hook will automatically update the cache without waiting for the response from the server. You may want to disable or customize thi
```suggestion
If the mutation mode is defined as `optimistic` or `undoable` the `useUpdateMany` hook will automatically update the cache without waiting for the response from the server. You may want to disable or customize this behavior. You can do this by passing the `queryCacheUpdateMap` prop.
```

2023-09-11 09:21 UTC, salihozdemir requested changes

2023-09-11 09:21 UTC, salihozdemir commented on packages/core/src/hooks/form/useForm.ts
> +                        ...queryCacheUpdateMap,
```suggestion
                        ...queryCacheUpdateMap,
```
We should pass this prop to first parameter of the mutation.

2023-09-18 14:19 UTC, omeraplak approved these changes

2023-09-19 11:45 UTC, BatuhanW requested changes

2023-09-19 11:45 UTC, BatuhanW commented on .changeset/heavy-eels-speak.md
> +"@refinedev/antd": major
Are you sure we need a major release for this one?

2023-09-19 11:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/data/useUpdate/index.md
> +If the mutation mode is defined as `optimistic` or `undoable` the `useUpdate` hook will automatically update the cache without waiting for the response from the server. You may want to disable or cus
```suggestion
If the mutation mode is defined as `optimistic` or `undoable`, `useUpdate` hook will automatically update the cache without waiting for the response from the server. You may want to disable or customize this behavior. You can do this by passing `optimisticUpdateMap` prop.
```

2023-09-19 11:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/data/useUpdate/index.md
> +This feature is only work with the `mutationMode` is set to `optimistic` and `undoable`
```suggestion
This feature only works when `mutationMode` is set to `optimistic` or `undoable`.
```

2023-09-19 11:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/data/useUpdate/index.md
> +`list`, `many` and `detail` are the keys of the `optimisticUpdateMap` object. For automatically updating the cache, you should pass the `true`. If you want not update the cache, you should pass the `
```suggestion
`list`, `many` and `detail` are the keys of the `optimisticUpdateMap` object. To automatically update the cache, you should pass `true`. If you don't want to update the cache, you should pass `false`.
```

2023-09-19 11:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/data/useUpdate/index.md
> +Also for customize the cache update, you can pass the function to the `list`, `many` and `detail` keys. The function will be called with the `previous` data, `values` and `id` parameters. You should
```suggestion
Also for customize the cache update, you can pass a function to the `list`, `many` and `detail` keys. These functions will be called with `previous` data, `values` and `id` parameters. You should return  updated data from the function.
```

2023-09-19 11:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/data/useUpdateMany/index.md
> +If the mutation mode is defined as `optimistic` or `undoable` the `useUpdateMany` hook will automatically update the cache without waiting for the response from the server. You may want to disable or
```suggestion
If the mutation mode is defined as `optimistic` or `undoable`, `useUpdateMany` hook will automatically update the cache without waiting for the response from the server. You may want to disable or customize this behavior. You can do this by passing `optimisticUpdateMap` prop.
```

2023-09-19 11:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/data/useUpdateMany/index.md
> +This feature is only work with the `mutationMode` is set to `optimistic` and `undoable`
```suggestion
This feature only works when `mutationMode` is set to `optimistic` or `undoable`
```

2023-09-19 11:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/data/useUpdateMany/index.md
> +`list`, `many` and `detail` are the keys of the `optimisticUpdateMap` object. For automatically updating the cache, you should pass the `true`. If you want not update the cache, you should pass the `
```suggestion
`list`, `many` and `detail` are the keys of the `optimisticUpdateMap` object. To automatically update the cache, you should pass `true`. If you don't want to update the cache, you should pass `false`.
```

2023-09-19 11:45 UTC, BatuhanW commented on documentation/docs/api-reference/core/hooks/data/useUpdateMany/index.md
> +            optimisticUpdateMap: {
```suggestion
        // highlight-start
        optimisticUpdateMap: {
```

2023-09-19 11:45 UTC, BatuhanW commented on packages/core/src/hooks/data/useUpdate.spec.tsx
> +                                        foo: "bar-list",
Why don't we pass these parameters to hook itself?

2023-09-19 11:45 UTC, BatuhanW commented on packages/core/src/hooks/data/useUpdate.spec.tsx
> +            await assertList(useManyResult, "foo", "bar-many");
I think we can also assert these data will be reverted to original state after data provider fails.

2023-09-19 11:45 UTC, BatuhanW commented on packages/core/src/hooks/data/useUpdate.spec.tsx
> +                            }
In the code of `useUpdate`, we are already doing an early return for `if (!previous)` case, do we need to repeat it here?

2023-09-19 16:22 UTC, omeraplak approved these changes

2023-09-19 16:22 UTC, BatuhanW approved these changes

2023-09-19 16:23 UTC, merged