fix: antd notificationProvider bug
refinedev/refine pull request #4945
Opened 2023-09-15 09:27 UTC by MahirMahdi

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

`notificationProvider` cannot access the theme context when the static `notification` method is used. So used the `App` component's `notification` instance to access the theme context. 

Passed the `App` component as a child of `ConfigProvider` to access the theme context.

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Closes #4654

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-09-15 14:15 UTC, aliemir requested changes
Thank you for the PR @MahirMahdi, just left a comment to the `notificationProvider` implementation. We also need a changeset for the changes to be released. Check out the [contributing docs](https://refine.dev/docs/contributing) for more info about that.

2023-09-15 14:15 UTC, aliemir commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
This usage forces users to use the `App` component from `antd` without a notice in any docs, tsdoc typings or in console. For my understanding, this is a breaking change for the users with existing projects. 

It might not be if `antd` didn't had empty default values for the app context 😅 Check out this source code: https://github.com/ant-design/ant-design/blob/master/components/app/context.ts#L22

`useApp` will not throw if it's not used inside the `App` component but it will return `notification: {}`. We should add a check for this and use the previous `notification` instance (imported one) as a fallback. This will make sure we have the `notification`.

Also, I think we can move the `App.useApp` to a variable outside of the `notificationProvider` like;

```tsx
import { App, notification as staticNotification } from "antd";

const { useApp } = App;

export const notificationProvider = () => {
  const { notification: notificationFromContext } = useApp();
  const notification = "open" in notificationFromContext ? notificationFromContext : staticNotification;
}
```

There can be better ways to write this condition, leaving the implementation to you 😅 

This way will avoid releasing a breaking change and make sure we're keeping it working for the current users.

2023-09-15 15:21 UTC, MahirMahdi commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Thank you so much. I should have tested the other projects, sorry I forgot. 😅

Sure, we can go ahead with this approach using the static `notification` instance as a fallback. I'll make the necessary changes tomorrow.

Also, we could update the documentation and the `ColorModeContextProvider` by passing `App` as a child so that projects built with `antd` can access the theme context from now on. 

![Screenshot 2023-09-15 211317](https://github.com/refinedev/refine/assets/66949598/2d856e41-994a-4ee1-8d02-cf71487943a6)

If you're okay with that, I'll create a separate PR after I'm done with this one. Let me know what you think about it.😀

2023-09-17 11:16 UTC, aliemir commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Hey @MahirMahdi, thank you for the changes, looks great! 🚀 Yeah, I think adding `App` to `ColorModeContextProvider` makes sense for apps created with `create-refine-app` 🤔 I think we should also mention about the notifications in https://refine.dev/docs/api-reference/antd/theming/ this document, can you add a small section about it here? 🙏 

BTW, `create-refine-app` uses the templates inside [`superplate-core-plugins`](https://github.com/pankod/superplate-core-plugins) if you want to update them accordingly 🙏

2023-09-17 11:52 UTC, MahirMahdi commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Hey @aliemir, anytime. 😀 

Would you like me to create a separate PR for the document and plugin changes or should I include them in this PR?

2023-09-18 09:23 UTC, aliemir commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Let's make the documentation changes included in this PR and we can move to a separate one for the superplate changes

2023-09-19 00:19 UTC, MahirMahdi commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Sure. On it.

2023-09-19 02:27 UTC, MahirMahdi commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Here you go @aliemir. Let me know if it requires any changes.
![Screenshot 2023-09-19 082446](https://github.com/refinedev/refine/assets/66949598/845ce5ad-28e6-4a9a-ba3f-a3bb587d0d6f)

2023-09-28 05:02 UTC, MahirMahdi commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
@aliemir sorry to bother you. If it's okay then I'll update the PR.

2023-09-28 15:18 UTC, aliemir commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Hey @MahirMahdi sorry for the late response. Can you also add highlights to the code for the `<AntdApp>` lines using `// highlight-next-line` or `// highlight-start` and `// highlight-end`? 🙏 

Just noticed we also have some failing tests due to notifications, can you check those? Might be a type issue coming from the changes I've suggested 😅 

After these, we're good to go 🚀

2023-09-29 06:59 UTC, MahirMahdi commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Hey @aliemir , it's totally fine. 

I've added `// highlight-start` and  `// highlight-end`. But there's some issue with the useApp() context, working on it

2023-09-29 08:40 UTC, aliemir commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
Thank you! Just send a push to fix the test issue with the notification provider and also added couple more tests 😅

2023-09-29 09:58 UTC, MahirMahdi commented on packages/antd/src/providers/notificationProvider/index.tsx
> +    const { notification } = App.useApp();
No, thank you for helping me out. I never worked with Jest before. So was having a hard time figuring out the issue. Thank you.😀

2023-09-29 11:27 UTC, aliemir approved these changes
Thank you for the effort @MahirMahdi! I'm requesting couple more reviews from the team to make sure we're heading the right way here. I'm having some concerns about if we should mark this as breaking or not due to converting `notificationProvider` export from an object to function 🤔

2023-09-29 14:07 UTC, aliemir commented on .changeset/small-melons-sing.md
> +Antd notification component could not access theme context, now it's fixed.
````suggestion
Antd notification component could not access theme context, now it's fixed.

This release changes exported `notificationProvider` value from type `NotificationProvider` to `() => NotificationProvider`. If you previously had customizations applied to the `notificationProvider` object, you may need to update your code like the following:

```diff
- import { notificationProvider } from "@refinedev/antd";
+ import { notificationProvider as useDefaultNotificationProvider } from "@refinedev/antd";

- const myNotificationProvider = {
-    ...notificationProvider,
-    open: (...args) => {
-        // do some operation here
-        notificationProvider.open(...args);
-    },
- }
+ const myNotificationProvider = () => {
+     const notificationProvider = useDefaultNotificationProvider();
+     return {
+          ...notificationProvider,
+          open: (...args) => {
+             // do some operation here
+             notificationProvider.open(...args);
+          },
+     }
+ }
}

const App = () => {
    return (
        <Refine
            /* ... */
            notificationProvider={myNotificationProvider}
        >
            /* ... */
        </Refine>
    );
}
```
````

2023-09-29 17:01 UTC, MahirMahdi commented
It's absolutely my pleasure @aliemir.

Absolutely, having different viewpoints will make it resistant to further issues. 

Hopefully, there won't be any issues as the 'mui' 'notificationProvider' is also exported as a function.

2023-10-02 10:09 UTC, MahirMahdi commented
Hi @aliemir,no worries. I can take care of it and if I need help, I'll text you on Discord.😃

2023-10-06 06:47 UTC, aliemir commented on documentation/docs/api-reference/antd/theming.md
> +The `notificationProvider` has been deprecated because it cannot consume the current `theme` context by default. To enable the `Notification` component to consume the current `theme` context, import
```suggestion
The `notificationProvider` export has been deprecated because it cannot consume the current `theme` context by default. To enable the `Notification` component to consume the current `theme` context, import the `App` component from `antd` and the `useNotificationProvider` export from `@refinedev/antd` and pass it as highlighted below:
```

2023-10-06 07:41 UTC, aliemir approved these changes
🎖️

2023-10-06 09:10 UTC, omeraplak approved these changes

2023-10-06 13:09 UTC, MahirMahdi commented on .changeset/small-melons-sing.md
> ++ import { notificationProvider as useDefaultNotificationProvider } from "@refinedev/antd";
I believe it would be `useNotificationProvider`, not `useDefaultNotificationProvider`.

2023-10-06 13:15 UTC, MahirMahdi commented on .changeset/small-melons-sing.md
> +This release changes exported `notificationProvider` value from type `NotificationProvider` to `() => NotificationProvider`. If you previously had customizations applied to the `notificationProvider`
Updated it.

2023-10-06 13:18 UTC, MahirMahdi commented
> I know it's been a long run 😄 But this is the final change, then we are good to go!
> 
> Thanks for the great contribution and follow-ups 🎖️

No problem at all. I'm glad I could help. 😃 

I was able to connect with amazing people like you, @omeraplak, and @aliemir because of this. So it's totally worth the wait. 🙌

2023-10-09 07:48 UTC, BatuhanW approved these changes

2023-10-10 07:43 UTC, merged