fix: add missing DataGrid operator conversion cases
refinedev/refine pull request #4974
Opened 2023-09-20 10:46 UTC by IkumaTadokoro

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

MUI defines the operator for each column types in [here](https://github.com/mui/mui-x/tree/2d09dbc6e5d03c4e66765d225ef93d3984e300fc/packages/grid/x-data-grid/src/colDef). However, there were not enough conversion cases for the following operators, so I added them to the mapping.

- isAnyof: used in Numeric, SingleSelect, String
- contains: used in String,
- startsWith: used in String
- endsWith: used in String

### Test plan (required)

No additional unit tests have been added, as this is just a pattern added to an existing transformation and a simple switch statement.

However, the test case that was supposed to test the target was actually testing something else, so the describe part of that part has been changed in this PR.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

closes #4970

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-09-25 11:41 UTC, BatuhanW requested changes
Hi @IkumaTadokoro, thanks for the contribution! Added a minor comment, then we can release it!

2023-09-25 11:41 UTC, BatuhanW commented on packages/mui/src/definitions/dataGrid/index.spec.ts
>          expect(transformCrudOperatorToMuiOperator("ne", "number")).toEqual(
Could you update the tests with the new switch cases you've added?

2023-09-25 23:49 UTC, omeraplak approved these changes

2023-09-25 23:50 UTC, IkumaTadokoro commented on packages/mui/src/definitions/dataGrid/index.spec.ts
>          expect(transformCrudOperatorToMuiOperator("ne", "number")).toEqual(
Tests have been added with [97ee1d0](https://github.com/refinedev/refine/pull/4974/commits/97ee1d03dbd652a80dd89bd0631faca1067cbace)! (I had overlooked that there was a test case for transformMuiOpeartorToCrudOperator. Thanks for that.)

I  also updated the test plan in the PR description.

2023-09-27 08:12 UTC, BatuhanW approved these changes

2023-09-28 17:09 UTC, merged