feat(docs): add crm-example to examples
refinedev/refine pull request #4977
Opened 2023-09-20 15:27 UTC by alicanerdurmaz

CRM Example added to the example list.

page: https://refine.dev/docs/examples/

<img width="1629" alt="image" src="https://github.com/refinedev/refine/assets/23058882/bcee98b8-cd86-4d93-8a29-86f40fb3b811">

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-09-20 19:28 UTC, omeraplak requested changes

2023-09-20 19:28 UTC, omeraplak commented on documentation/src/assets/examples.tsx
> -        title: "refine Swag Store",
@alicanerdurmaz Can we replace the 'finefoods storefront' with the 'Swag store'?

2023-09-22 06:33 UTC, BatuhanW approved these changes

2023-09-22 07:13 UTC, BatuhanW approved these changes

2023-09-22 07:23 UTC, merged