fix: convert hasura operator with graphql-default
refinedev/refine pull request #5040
Opened 2023-10-02 11:31 UTC by IkumaTadokoro

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

When using the Hasura provider with the 'graphql-default' naming convention, snake-case hasura operators (e.g. _is_null) were not converted to the correct case, causing query errors.
This problem is now fixed. Now the snake_case operator is converted according to the given naming convention (e.g. hasura-default: _is_null, graphql-default: _isNull).

### Test plan (required)

- Snake case hasura operator correctly converted to case added.
- The signature of the `generateFilters` function has changed, so existing test cases for this function will now run against the appropriate naming convention (but are backwards compatible in behaviour, as they are optional arguments).

### Closing issues

closes: #4972

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-10-02 11:51 UTC, aliemir requested changes
Let's a tiny comment 😅 Thank you for the PR 🚀

2023-10-02 11:51 UTC, aliemir commented on packages/hasura/src/utils/generateFilters.ts
> +export const generateFilters: any = (
Shouldn't we also call the `generateFilters` with `namingConvention` in the data provider? @IkumaTadokoro

2023-10-02 12:41 UTC, IkumaTadokoro commented on packages/hasura/src/utils/generateFilters.ts
> +export const generateFilters: any = (
@aliemir 
Indeed, since the util is clearly dependent on the data provider, the format to pass it from there is better. Thanks for your review.

During the modification process I realised that currently the hasura live provider, unlike the data provider, does not support the naming convention.
Since it also references generateFilters, it is necessary to pass some naming convention, but the change to add naming convention to live provider is different from this PR scope, so I have modified it to pass `hasura-default` as a fixed convention once. 

If you would like me to make changes to this PR for that scope, please comment.

2023-10-02 13:22 UTC, aliemir commented on packages/hasura/src/utils/generateFilters.ts
> +export const generateFilters: any = (
Just send couple of commits to your branch. I thought the order of the parameters matter because there may be users who customized their hasura data providers and rely on these methods, we don't want to introduce a breaking change out of nowhere to them 😅 

Thank you for the quick work and thank you for your effort 🙏

2023-10-02 13:22 UTC, aliemir approved these changes

2023-10-02 14:12 UTC, alicanerdurmaz approved these changes

2023-10-03 07:57 UTC, omeraplak approved these changes

2023-10-03 08:05 UTC, merged