docs(devtools): add devtools to site
refinedev/refine pull request #5051
Opened 2023-10-03 13:35 UTC by necatiozmen

I added devtools docs. Need to add to sidebar as well

2023-10-03 14:23 UTC, omeraplak requested changes

2023-10-03 14:23 UTC, omeraplak commented on packages/devtools/README.md
> +
```suggestion
```

2023-10-03 14:23 UTC, omeraplak commented on packages/devtools/README.md
> +
```suggestion
> 🚨 If you don't have `@refinedev/cli` installed already, you can follow the [installation guide](https://refine.dev/docs/packages/documentation/cli/#how-to-add-to-an-existing-project) to add it to your project.

```

2023-10-04 08:46 UTC, BatuhanW commented on packages/devtools/README.md
> +npm install @refinedev/cli@latest
Maybe we can also add `@refinedev/core`?

2023-10-04 10:52 UTC, omeraplak approved these changes

2023-10-04 10:53 UTC, merged