fix: convert type of an option's value to string
refinedev/refine pull request #5160
Opened 2023-10-24 19:18 UTC by an-tran511

Currently, option value is not converted into string after getting result from `useSelect` hook.
I refactor to use String() constructor for type conversion instead of type casting

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #5157` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-10-25 05:50 UTC, omeraplak requested changes

2023-10-25 05:50 UTC, omeraplak commented on .changeset/quick-knives-jump.md
> +"@refinedev/core": major
```suggestion
"@refinedev/core": patch
```

2023-10-25 05:52 UTC, omeraplak commented on .changeset/quick-knives-jump.md
> +"@refinedev/core": major
Thank you so much for your attention and effort! Can you mark the change as `patch` instead of `major`?

2023-10-25 09:54 UTC, omeraplak approved these changes

2023-10-25 10:24 UTC, BatuhanW reviewed
Hello @an-tran511 

Thanks for the contribution! Looks good to me.

Before we merge it, could you add some test cases to cover your fix [in this file?](https://github.com/refinedev/refine/blob/90da1f82bba95edcf09a46a7fb51b760e4c711f2/packages/core/src/hooks/useSelect/index.spec.ts)

2023-10-25 10:25 UTC, alicanerdurmaz approved these changes

2023-10-25 15:46 UTC, an-tran511 commented
> Hello @an-tran511
> 
> Thanks for the contribution! Looks good to me.
> 
> Before we merge it, could you add some test cases to cover your fix [in this file?](https://github.com/refinedev/refine/blob/90da1f82bba95edcf09a46a7fb51b760e4c711f2/packages/core/src/hooks/useSelect/index.spec.ts)

I added test case for this patch

2023-10-26 08:27 UTC, BatuhanW approved these changes

2023-10-26 08:28 UTC, omeraplak approved these changes

2023-10-26 12:59 UTC, aliemir commented on .changeset/quick-knives-jump.md
> +convert type of an option's value to string
fix: convert type of an option's `value` to `string`

2023-10-26 13:02 UTC, merged