Example auth kinde
refinedev/refine pull request #5163
Opened 2023-10-25 08:35 UTC by hirenf14

[Kinde Auth Provider](https://github.com/hirenf14/refine-auth-kinde-react) example added.

Please check all items below before review.

-   *[x ] Corresponding issues are created/updated or not needed
-   *[x ] Docs are updated/provided or not needed
-   *[x ] Examples are updated/provided or not needed
-   *[x ] TypeScript definitions are updated/provided or not needed
-   *[x ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-10-25 12:57 UTC, omeraplak requested changes

2023-10-25 12:57 UTC, omeraplak commented on examples/auth-kinde/index.html
> +        <title>refine auth0 example app</title>
```suggestion
        <title>refine kinde example app</title>
```

2023-10-25 12:57 UTC, omeraplak commented on examples/auth-kinde/public/manifest.json
> +  "name": "refine auth0 example app",
```suggestion
  "short_name": "refine kinde example app",
  "name": "refine kinde example app",
```

2023-10-25 13:20 UTC, hirenf14 commented on examples/auth-kinde/public/manifest.json
> +  "name": "refine auth0 example app",
Fixed

2023-10-26 11:52 UTC, BatuhanW requested changes
Hi @hirenf14 thanks for the library and contribution! 

Could you also delete pages like create, edit, show as they aren't adding any value to the example? In this scope, it's sufficient to see user is authenticated and redirected to the list page.

2023-10-26 11:52 UTC, BatuhanW commented on examples/auth-kinde/src/index.tsx
> +            clientId="4a1272d4861a46eb9a14c97b3b66c096"
```suggestion
            clientId="1b29435f50084bbd91c4fe423d7586a6"
```

2023-10-26 11:52 UTC, BatuhanW commented on examples/auth-kinde/src/index.tsx
> +            domain="https://hirenf.kinde.com"
```suggestion
            domain="https://refine.kinde.com"
```

2023-10-26 11:52 UTC, BatuhanW commented on examples/auth-kinde/cypress/e2e/all.cy.ts
> +describe("auth-kinde", () => {
Can we remove e2e specs from this example? I believe it's redundant because our e2e tests in examples are meant to test our core features. We don't want to add extra minutes to the CI unless really needed.

2023-10-26 11:52 UTC, BatuhanW commented on examples/auth-kinde/src/index.tsx
> +            clientId="4a1272d4861a46eb9a14c97b3b66c096"
We've created refine organization on kinde 🎉 Let's use our clientId as it will be easier to do changes in configuration if we need it.

2023-10-26 13:16 UTC, hirenf14 commented on examples/auth-kinde/src/index.tsx
> +            clientId="4a1272d4861a46eb9a14c97b3b66c096"
Thanks for that. :)

2023-10-26 13:17 UTC, hirenf14 commented on examples/auth-kinde/cypress/e2e/all.cy.ts
> +describe("auth-kinde", () => {
Sure, I had added it as it seems required and had followed `auth-auth0` example.

2023-10-26 13:48 UTC, hirenf14 commented on examples/auth-kinde/cypress/e2e/all.cy.ts
> +describe("auth-kinde", () => {
Done.

2023-10-26 13:48 UTC, hirenf14 commented on examples/auth-kinde/src/index.tsx
> +            domain="https://hirenf.kinde.com"
Done

2023-10-27 12:43 UTC, BatuhanW requested changes
Thanks for the updates! 🎉 

Added comments for some leftover references to cypress.

2023-10-27 12:43 UTC, BatuhanW commented on cypress/fixtures/kinde-credentials.json
> +  }
We can also remove this file.

2023-10-27 12:43 UTC, BatuhanW commented on examples/auth-kinde/cypress/tsconfig.json
> +}
Let's remove this directory as well.

2023-10-27 12:43 UTC, BatuhanW commented on examples/auth-kinde/package.json
> +    "cypress:run": "cypress run -C ./cypress.config.ts"
```suggestion
```

2023-10-30 04:41 UTC, hirenf14 commented on examples/auth-kinde/cypress/tsconfig.json
> +}
done

2023-10-30 04:42 UTC, hirenf14 commented on cypress/fixtures/kinde-credentials.json
> +  }
done

2023-10-30 04:42 UTC, hirenf14 commented on examples/auth-kinde/package.json
> +    "cypress:run": "cypress run -C ./cypress.config.ts"
done

2023-10-30 08:53 UTC, BatuhanW approved these changes

2023-10-30 09:11 UTC, omeraplak approved these changes

2023-10-30 10:19 UTC, merged