chore: update blog banners
refinedev/refine pull request #5195
Opened 2023-10-30 13:58 UTC by necatiozmen

I update blog banner links

2023-10-30 14:46 UTC, BatuhanW requested changes

2023-10-30 14:46 UTC, BatuhanW commented on documentation/src/components/banner/banner-examples.tsx
> +        href: "https://s.refine.dev/blog-retool",
```suggestion
        href: "https://s.refine.dev/blog-retool?ref=banner-retool-alternative",
```

2023-10-31 07:07 UTC, BatuhanW approved these changes

2023-10-31 08:32 UTC, omeraplak approved these changes

2023-10-31 08:32 UTC, merged