docs: landing page redesign
refinedev/refine pull request #5226
Opened 2023-11-07 08:09 UTC by aliemir

Welcoming our users with a brand new landing page

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-11-08 07:02 UTC, BatuhanW commented on documentation/src/refine-theme/landing-packages.tsx
> +    },
```suggestion
```

2023-11-08 07:02 UTC, BatuhanW commented on documentation/src/refine-theme/landing-packages.tsx
> +    },
```suggestion
```

2023-11-08 13:58 UTC, BatuhanW requested changes

2023-11-08 13:58 UTC, BatuhanW commented on documentation/src/refine-theme/landing-pure-react-code.tsx
> +
```suggestion
import React from "react";

import { useGo, useList } from "@refinedev/core";

export const ProductList: React.FC = () => {
  const {
    data: { data, total },
    isLoading,
  } = useList();

  const go = useGo();

  if (isLoading) return <div>Loading...</div>;

  return (
    <>
      <h1>Products</h1>
      <h3>Showing {total} products in total.</h3>
      <ul>
        {data.map((product) => (
          <li key={product.id}>
            <span>{product.name}</span>
            <button
              onClick={() => {
                go({
                  to: {
                    resource: "products",
                    action: "show",
                    id: product.id,
                  },
                });
              }}
            >
              show
            </button>
          </li>
        ))}
      </ul>
    </>
  );
};
```

2023-11-09 11:27 UTC, omeraplak approved these changes

2023-11-09 11:27 UTC, merged