docs: clarify imports for useTable core examples
refinedev/refine pull request #5253
Opened 2023-11-13 20:39 UTC by jamesthesken

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:
This PR adds import statements to the `useTable` documentation under `Core API/Hooks/useTable`, as some properties are only available with `import { useTable } from "@refinedev/core"`. For example, changing examples such as:

```tsx
useTable({
    pagination: {
        pageSize: 20,
    },
});
``` 

to:

```tsx
import { useTable } from "@refinedev/core"
useTable({
    pagination: {
        pageSize: 20,
    },
});
``` 

Explain the **details** for making this change. What existing problem does the pull request solve?

It was confusing for myself while using the useTable hook referencing the examples without clarifying which packages to import.

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2023-11-13 20:40 UTC, jamesthesken commented
Closes: [#5216](https://github.com/refinedev/refine/issues/5216)

2023-11-14 10:05 UTC, omeraplak approved these changes
Thank you! 💥

2023-11-14 10:06 UTC, omeraplak requested changes

2023-11-14 10:06 UTC, omeraplak commented on documentation/docs/api-reference/core/hooks/useTable/index.md
> +import { useTable } from "@refinedev/core"
```suggestion
import { useTable } from "@refinedev/core";
```

Could you add missing semicolons?

2023-11-14 13:48 UTC, alicanerdurmaz approved these changes

2023-11-14 18:48 UTC, jamesthesken commented on documentation/docs/api-reference/core/hooks/useTable/index.md
> +import { useTable } from "@refinedev/core"
Thanks for reviewing I just added and pushed a new commit😄

2023-11-15 06:18 UTC, omeraplak approved these changes

2023-11-15 06:18 UTC, merged