docs: add new guides
refinedev/refine pull request #5272
Opened 2023-11-17 14:47 UTC by aliemir

Added new guides:
- Authorization
- Authentication
- Forms
- Data Fetching
- UI Libraries
- General Concepts
- Routing

This PR will be followed with some additions:

- Introduction guides for UI packages
- Updated useForm docs for Core API
- New section about query keys and state management in general concepts guide

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-11-17 14:50 UTC, omeraplak requested changes

2023-11-17 14:50 UTC, omeraplak commented on documentation/versioned_docs/version-3.xx.xx/advanced-tutorials/data-provider/supabase.md
> +    :::
```suggestion
:::
```

2023-11-17 15:25 UTC, omeraplak approved these changes

2023-11-21 09:12 UTC, omeraplak requested changes

2023-11-21 09:12 UTC, omeraplak commented on documentation/docs/guides-concepts/forms/index.md
> +  onMutationSuccess() {
```suggestion
  onMutationSuccess: () {
```

2023-11-21 09:26 UTC, BatuhanW approved these changes

2023-11-21 09:27 UTC, omeraplak approved these changes

2023-11-21 09:27 UTC, merged