feat(core): update github banner styles
refinedev/refine pull request #5289
Opened 2023-11-20 14:13 UTC by alicanerdurmaz

feat: `<GitHubBanner />` styles updated.

![localhost_5173_posts_pageSize=10 current=1(macbook 13)](https://github.com/refinedev/refine/assets/23058882/5f3edf20-e055-4998-ac36-d9f2cc62ca20)
![localhost_5174_posts_pageSize=10 current=1(macbook 13)](https://github.com/refinedev/refine/assets/23058882/c52106d7-c239-4a8a-93fe-6a59a03e8f2d)
![localhost_5175_posts_pageSize=25 current=1(macbook 13)](https://github.com/refinedev/refine/assets/23058882/106f5a5a-01d8-418f-b974-37b1ac80539c)
![localhost_5176_posts_pageSize=10 current=1 sorters 0 field =id sorters 0 order =desc(macbook 13)](https://github.com/refinedev/refine/assets/23058882/59b28eaf-c6aa-451f-8918-00f6f91bb618)

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-11-20 14:30 UTC, necatiozmen requested changes

2023-11-20 14:30 UTC, necatiozmen commented on packages/core/src/components/gh-banner/index.tsx
> +        "Be a part of our journey. Star Refine on GitHub!",
```suggestion
        "Be a part of our journey by starring Refine on GitHub.",
```

2023-11-20 14:30 UTC, necatiozmen commented on packages/core/src/components/gh-banner/index.tsx
> +        "Join our community. Star Refine on GitHub!",
```suggestion
        "Join our community and star Refine on GitHub.",
```

2023-11-20 14:30 UTC, necatiozmen commented on packages/core/src/components/gh-banner/index.tsx
> +        "Let's elevate Refine together. Star us on GitHub!",
```suggestion
        "Let's elevate Refine together - star us on GitHub.",
```

2023-11-20 14:30 UTC, necatiozmen commented on packages/core/src/components/gh-banner/index.tsx
> +        "Enhance Refine's reach. Give us a star on GitHub!",
```suggestion
        "Enhance Refine's reach by giving us a star on GitHub.",
```

2023-11-21 08:20 UTC, omeraplak approved these changes

2023-11-21 08:20 UTC, omeraplak commented on .changeset/yellow-suns-smile.md
> +fixed: `<GitHubBanner />` hydration error. #5295
```suggestion
fix: `<GitHubBanner />` hydration error. #5295
```

2023-11-21 08:43 UTC, omeraplak approved these changes

2023-11-21 09:08 UTC, merged