fix: `<AuthPage />` styling issues on mobile screens
refinedev/refine pull request #5325
Opened 2023-11-28 13:33 UTC by alicanerdurmaz

before:
<img width="400" alt="image" src="https://github.com/refinedev/refine/assets/23058882/da204353-f3fc-449d-ae4e-c9ce6fcc83e1">

<img width="400" alt="image" src="https://github.com/refinedev/refine/assets/23058882/ca555df0-0898-42d0-bf6c-cb04895d63ed">

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2023-11-30 10:41 UTC, omeraplak approved these changes

2023-12-01 14:30 UTC, aliemir approved these changes
🎖️

2023-12-01 14:55 UTC, aliemir requested changes
- In Core's `AuthPage`, if I set `hideForm: true`, `sign in` button is still visible
- In Mantine's and Ant Design's `AuthPage` components, the top padding is missing, causing logo + title to stick to the top in small screens. (with form)
- In Core's `AuthPage`, if I set `hideForm: true`, still had to set `rememberMe: false, forgotPasswordLink: false`, `registerLink: false`. This is the expected behavior but in Ant Design's `AuthPage` (and others), `hideForm` hides remember me and forgot password. We may need to discuss this behavior and decide which one is correct.

2023-12-04 06:59 UTC, aliemir approved these changes

2023-12-04 06:59 UTC, merged