WIP: Initial Mantine 7 support
refinedev/refine pull request #5340
Opened 2023-12-01 16:25 UTC by glebtv

closes #5178

I fixed theme-mantine-demo, most of the other examples are untested and probably won't work.

Notable problems:
Mantine 7 uses CSS modules for styling, and @refinedev/mantine uses tsup to build, which doesn't support css modules
https://github.com/egoist/tsup/issues/536

Any input or feedback welcome

2023-12-30 15:42 UTC, piccinnigius commented
any update on this? :) thanks for your pr!

2024-01-02 08:00 UTC, alicanerdurmaz requested changes

2024-01-02 08:00 UTC, alicanerdurmaz commented on packages/cli/src/utils/package/index.ts
> +    bun: {
these CLI changes should be in a different PR

2024-01-02 08:05 UTC, alicanerdurmaz commented
> * also export a `css` file from the package and let the users import it in their apps. So we'll use some prefixed classnames for our components and let users be able to use those class names as selectors.

Hello @piccinnigius, we are waiting for @glebtv to make the requested changes. if @glebtv is not available and you would like to continue this development, we would appreciate it 🙌

2024-01-16 19:09 UTC, amirmamaghani commented
Hey @glebtv , any update on this? :) highly appreciated!

2024-01-24 06:44 UTC, BatuhanW commented
> Hey @glebtv , any update on this? :) highly appreciated!

Hey @amirmamaghani we are open to contributions from the community, as the original owner of the PR seeems to be unresponsive.

2024-01-24 14:21 UTC, amirmamaghani commented
> > Hey @glebtv , any update on this? :) highly appreciated!
> 
> Hey @amirmamaghani we are open to contributions from the community, as the original owner of the PR seeems to be unresponsive.

Hey @BatuhanW , is there any how to guide how to work on these subpackages? I quickly tried to run it but I find it difficult to dig through sourcecodes without seeing any Storybook or sth. Thanks!

2024-01-24 15:44 UTC, BatuhanW commented
> > > Hey @glebtv , any update on this? :) highly appreciated!
> 
> > 
> 
> > Hey @amirmamaghani we are open to contributions from the community, as the original owner of the PR seeems to be unresponsive.
> 
> 
> 
> Hey @BatuhanW , is there any how to guide how to work on these subpackages? I quickly tried to run it but I find it difficult to dig through sourcecodes without seeing any Storybook or sth. Thanks!

Hey @amirmamaghani you can check our contribution guide. https://refine.dev/docs/guides-concepts/contributing/

2024-02-02 05:30 UTC, arloktev commented
Hi, what exactly do you need help with this PR? Fix checks or something else?

2024-02-09 11:08 UTC, glebtv commented on packages/cli/src/utils/package/index.ts
> +    bun: {
Won't build without it

2024-02-09 11:39 UTC, glebtv commented
Sorry, I didn't have any time for this PR, but  now I have rebased it to current master and am planning to fix the remaining examples soon

2024-02-12 13:38 UTC, glebtv commented
I made @test at packages/ui-tests/tsup.config.ts a separate entrypoint so TestWrapper and render function could be replaced to add MantineProvider to the tests.

A better solution it is welcome

2024-02-14 08:01 UTC, glebtv commented
Can someone trigger tests and examples build please?

2024-02-15 10:17 UTC, glebtv commented
Please try the builds again, all tests and examples should work now.

Please note there is now ```<Select>``` and ```<MultiSelect>``` components in refinedev/mantine, since mantine 7 ```Select``` doesn't work with integers as values, and a ```useMultiSelect``` since the MultiSelect prop type is incompatible with Select's.

This component is currently a wrapper around mantine's Selelct but can be later replaced with a custom implementation, like https://mantine.dev/combobox/?e=AsyncAutocomplete 

But Mantine select is overall not as good as react-select, maybe replace it with react-select?

Also should I rewrite\clean up the commits or will you squash them?

2024-02-15 10:20 UTC, glebtv commented
This PR will also fix MUI snapshots, currently they are broken because of random css- classes.

Will update the branch to fix a conflict in snapshots

2024-02-21 12:05 UTC, glebtv commented
I've updated and cleaned up the commits so they are more manageable.
Please tell me if there's anything else I could do to help get this merged.

2024-02-22 09:10 UTC, glebtv commented
Please try again, all e2e tests should also work now.
Also fixed sider border

2024-02-22 13:51 UTC, RWOverdijk approved these changes

2024-02-26 16:27 UTC, glebtv commented
Seems that snapshots were broken by master merge, I've updated them, please run the build again.

2024-02-27 07:04 UTC, BatuhanW reviewed
Hey, thanks for the detailed PR, it's a big one and taking time to review.

Added some minor comments, we'll try to add some more review comments later today.

Also, we are missing documentation updates.

2024-02-27 07:24 UTC, BatuhanW commented on packages/mantine/src/types/theme.ts
> +// }
Why did we commented this one?

2024-02-27 07:24 UTC, BatuhanW commented on packages/mantine/test/dataMocks.tsx
> +} from "@refinedev/core"; */
Let's remove if it's not needed.

2024-02-27 07:24 UTC, BatuhanW commented on packages/ui-tests/src/test/render.tsx
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
```suggestion
```

2024-02-27 07:24 UTC, BatuhanW commented on packages/ui-tests/src/test/render.tsx
> +    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
```suggestion
```

2024-02-27 07:24 UTC, BatuhanW commented on packages/ui-tests/src/test/render.tsx
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
We don't use eslint anymore.

2024-02-27 07:24 UTC, BatuhanW commented on packages/mantine/src/theme/index.ts
> -  ...commonThemeProperties,
Could you explain why did we delete these?

2024-02-27 07:24 UTC, BatuhanW commented on packages/mantine/src/index.tsx
> +//import "./types/theme";
Let's not keep commented lines **anywhere**. Remove comments completely if they aren't needed.

2024-02-27 07:24 UTC, BatuhanW commented on packages/mantine/src/hooks/useSelect/index.ts
> +      //filterDataOnExactSearchMatch: true,
```suggestion
```

2024-02-27 07:24 UTC, BatuhanW commented on packages/mantine/src/definitions/button/index.ts
> +      return "default";
I think we don't need this all together. It just returns `default` if you pass `white` and returns your variant by default.

2024-02-27 07:26 UTC, alicanerdurmaz requested changes

2024-02-27 07:26 UTC, alicanerdurmaz commented on packages/mantine/src/components/select/MultiSelect.tsx
> +export const MultiSelect: React.FC<RefineMantineMultiSelectProps> = ({
why do we need this component? Can't we import <Select /> directly from mantine and use it with useSelect?

2024-02-27 07:26 UTC, alicanerdurmaz commented on packages/mantine/src/components/select/Select.tsx
> +export const Select: React.FC<SelectProps> = ({
why do we need this component? Can't we import <Select /> directly from mantine and use it with useSelect?

2024-02-27 07:26 UTC, alicanerdurmaz commented on packages/mantine/src/hooks/useMultiSelect/index.ts
> +export const useMultiSelect = <
why do we need this hook? Is `useSelect` not enough?

2024-02-27 07:29 UTC, alicanerdurmaz commented
I believe we can remove `packages/mantine/src/components/themedLayout/index.tsx` and other related components completely, `<ThemedLayout />` is already deprecated. We can just continue with <ThemedLayoutV2 />

2024-02-27 07:31 UTC, alicanerdurmaz requested changes

2024-02-27 07:31 UTC, alicanerdurmaz commented on examples/base-mantine/src/pages/posts/create.tsx
> +          /* filter={(options, search, limit) => {
Commented codes are confusing. Please remove it if we don't need

2024-02-27 09:32 UTC, glebtv commented on packages/mantine/src/components/select/MultiSelect.tsx
> +export const MultiSelect: React.FC<RefineMantineMultiSelectProps> = ({
As noted in my comment there is now <Select> and <MultiSelect> components in refinedev/mantine, since mantine 7 Select doesn't work with integers as values, and a useMultiSelect since the MultiSelect prop type is incompatible with Select's.

I don't like my solution myself, so if anyone has a better one it is welcome

2024-02-27 09:34 UTC, glebtv commented on packages/mantine/src/types/theme.ts
> +// }
Commented because it errored out, didn't restore because can't find how it was used. Probably could be deleted

2024-02-27 09:37 UTC, glebtv commented on packages/mantine/src/theme/index.ts
> -  ...commonThemeProperties,
Because it seems to not be possible to set from theme object

https://mantine.dev/theming/theme-object/

see https://mantine.dev/theming/color-schemes/

2024-02-27 09:38 UTC, glebtv commented on examples/base-mantine/src/pages/posts/create.tsx
> +          /* filter={(options, search, limit) => {
Not sure if it is needed, but it doesn't work as filter option changed significantly in mantine 7 select

2024-02-27 09:41 UTC, glebtv commented on packages/mantine/src/components/select/MultiSelect.tsx
> +export const MultiSelect: React.FC<RefineMantineMultiSelectProps> = ({
As noted in my comment there is now and components in refinedev/mantine, since mantine 7 Select doesn't work with integers as values, and a useMultiSelect since the MultiSelect prop type is incompatible with Select's. I don't like my solution myself, so if anyone has a better one it is welcome

2024-02-27 09:41 UTC, glebtv commented on packages/mantine/src/components/select/Select.tsx
> +export const Select: React.FC<SelectProps> = ({
As noted in my comment there is now and components in refinedev/mantine, since mantine 7 Select doesn't work with integers as values, and a useMultiSelect since the MultiSelect prop type is incompatible with Select's. I don't like my solution myself, so if anyone has a better one it is welcome

2024-02-27 09:41 UTC, glebtv commented on packages/mantine/src/hooks/useMultiSelect/index.ts
> +export const useMultiSelect = <
As noted in my comment there is now and components in refinedev/mantine, since mantine 7 Select doesn't work with integers as values, and a useMultiSelect since the MultiSelect prop type is incompatible with Select's. I don't like my solution myself, so if anyone has a better one it is welcome

2024-02-27 11:07 UTC, glebtv commented on packages/mantine/src/definitions/button/index.ts
> +      return "default";
Implemented a better version. Thank you

2024-02-27 11:08 UTC, glebtv commented
Having trouble getting GithubBanner component to work with mantine's AppShell since AppShell uses fixed positioning, and the banner shows up below the layout.

I've moved the github banner to footer, please tell if this is ok

2024-02-29 08:23 UTC, BatuhanW reviewed
Hey @glebtv thanks for the great PR! Appreciate your efforts. There are couple of things needs to be resolved, added some minor comments. @alicanerdurmaz and @aliemir will make separate reviews later today.

We need to do some changes on our documentation after this upgrade. 

https://github.com/refinedev/refine/blob/master/packages/mantine/README.md

For example here, we have install script explicitly using v5. Now we have mantine 7 support, I think we can update them.

2024-02-29 08:23 UTC, BatuhanW commented on .changeset/friendly-queens-rest.md
> +mantine 7
This changeset should only include `@refinedev/mantine major`. Make sure to follow our [changeset format](https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset).

You can generate a different changeset for the other packages.

2024-02-29 08:23 UTC, BatuhanW commented on examples/server-side-form-validation-mantine/src/pages/posts/create.tsx
> +                    }} */
Let's completely remove if it's not needed.

2024-02-29 08:23 UTC, BatuhanW commented on examples/server-side-form-validation-mantine/src/pages/posts/edit.tsx
> +                    }} */
✏️

2024-02-29 14:52 UTC, alicanerdurmaz requested changes

2024-02-29 14:52 UTC, alicanerdurmaz commented on packages/mantine/src/components/themedLayoutV2/title/index.tsx
> +        <Text lh={0} fz="inherit">
```suggestion
        <Text lh={0} fz="inherit" c="primary">
```

icon color should be primary

https://github.com/refinedev/refine/assets/23058882/4eb9e4ef-5b4f-4fcf-9a93-039420c9e11f

2024-03-27 00:24 UTC, adamfeldman commented
Is this PR on-track to land in the April Refine release?

2024-04-03 06:46 UTC, closed without merging

2024-04-03 06:50 UTC, BatuhanW commented
Hey @glebtv, we've merged `releases/april` branch, so your PR is closed. Could you re-open your PR?

2024-04-04 07:10 UTC, BatuhanW commented
Hey @glebtv sorry for the inconvenience. I've also emailed you.

2024-04-22 14:44 UTC, mkhennoussi commented
Any news about Mantine 7 support guys ? Thanks !

2024-04-23 10:55 UTC, glebtv commented
I'm sorry but currently I don't have time to continue this work, anyone is free to open a new pull using (or not using) my changes

2024-05-10 21:03 UTC, mkhennoussi commented
@glebtv Thanks for your answer and for your work ! @BatuhanW is Mantine v7 on the roadmap ? as it seems we are very close to support it...

2024-06-05 11:36 UTC, BatuhanW commented
Hey @glebtv thanks for the contributions! You've come a long way and we appreciate it.

@mkhennoussi We are open to community contributions for this one.