fix: fix url with query string
refinedev/refine pull request #5378
Opened 2023-12-15 10:58 UTC by amanzrx4

`[WIP]`  

### Closing issues 

`closes #5359`

2023-12-18 07:01 UTC, BatuhanW requested changes
Hello @amanzrx4 thanks for the PR!

Could you add changeset? https://refine.dev/docs/further-readings/contributing/#changeset

2023-12-18 09:21 UTC, amanzrx4 commented
I've added. Could you check @BatuhanW

2023-12-18 09:44 UTC, BatuhanW requested changes

2023-12-18 09:44 UTC, BatuhanW commented on .changeset/perfect-ties-provide.md
> +"@refinedev/simple-rest": major
```suggestion
"@refinedev/simple-rest": patch
```

2023-12-18 09:53 UTC, amanzrx4 commented
I've also updated the fn implementation [here](https://github.com/refinedev/refine/blob/77c5cc9962a92a6d82d5ae7b7db716c4eae13286/packages/utils/index.ts)

2023-12-18 10:45 UTC, BatuhanW commented
> @BatuhanW I've also updated the fn implementation [here](https://github.com/refinedev/refine/blob/77c5cc9962a92a6d82d5ae7b7db716c4eae13286/packages/utils/index.ts)

Thanks @amanzrx4! Looks great! We'll review it soon! Assigned it to January release.

There are 2 minor updates:
- Add a test for the new utility file
- Add new file to `refine.config.js`. https://github.com/refinedev/refine/blob/7c8827b43d9e378818be6ee23032925c97ce02d5/packages/simple-rest/refine.config.js#L18

We need to add this file to `refine.config.js`, because if someone swizzles this data provider, it won't copy this file to users' directory.

2023-12-19 10:17 UTC, aliemir requested changes
Left two comments, should be easy to update. Thank you for the contribution.

2023-12-19 10:17 UTC, aliemir commented on packages/utils/index.ts
> +import { stringify, ParsedUrlQueryInput } from "querystring";
We use the `query-string` package instead of `querystring`

2023-12-19 10:17 UTC, aliemir commented on .changeset/perfect-ties-provide.md
> +add a urlWithQueryString util
Can we add more info about the issue the changes are going to resolve. This is going to be included in the changelogs and release notes for the next version.

2024-01-24 08:22 UTC, alicanerdurmaz approved these changes

2024-01-24 09:45 UTC, BatuhanW approved these changes
Great 🙌🏼

2024-01-31 13:01 UTC, aliemir approved these changes

2024-02-01 07:06 UTC, merged