feat(core): add gqlQuery and gqlMutation fields to MetaQuery type
refinedev/refine pull request #5409
Opened 2023-12-21 14:24 UTC by BatuhanW

Added `gqlQuery` and `gqlMutation` fields to `MetaQuery` type. These fields will enable using GraphQL Operations generated with `graphql-tag` package.

2023-12-22 06:46 UTC, omeraplak requested changes

2023-12-22 06:46 UTC, omeraplak commented on .changeset/three-masks-fail.md
> +const { data } = useList({ resource: "products", meta: gqlQuery: PRODUCTS_QUERY });
```suggestion
const { data } = useList({ resource: "products", meta: { gqlQuery: PRODUCTS_QUERY } });
```

2023-12-25 09:57 UTC, aliemir approved these changes

2023-12-25 11:58 UTC, alicanerdurmaz approved these changes

2023-12-25 12:46 UTC, omeraplak approved these changes

2023-12-25 12:48 UTC, merged