feat(nestjs-query): utilize meta.gqlQuery and meta.gqlMutation fields
refinedev/refine pull request #5411
Opened 2023-12-21 15:32 UTC by BatuhanW

- Refactor `nestjs-query` data provider to `meta.gqlQuery` and `meta.gqlMutation` fields when provided.

2023-12-22 14:31 UTC, omeraplak requested changes

2023-12-22 14:31 UTC, omeraplak commented on .changeset/brave-brooms-unite.md
> +const { data } = useList({ resource: "products", meta: gqlQuery: PRODUCTS_QUERY });
```suggestion
const { data } = useList({ resource: "products", meta: { gqlQuery: PRODUCTS_QUERY } });
```

2023-12-22 14:31 UTC, omeraplak requested changes

2023-12-22 14:31 UTC, omeraplak commented on .changeset/brave-brooms-unite.md
> +const { formProps } = useForm({ resource: "products", meta: gqlMutation: CREATE_PRODUCT_MUTATION });
```suggestion
const { formProps } = useForm({ resource: "products", meta: { gqlMutation: CREATE_PRODUCT_MUTATION } });
```

2023-12-25 08:38 UTC, alicanerdurmaz approved these changes

2023-12-25 09:42 UTC, aliemir approved these changes

2023-12-25 11:46 UTC, merged