Update generateSorting.ts | issue #5348
refinedev/refine pull request #5508
Opened 2024-01-12 13:31 UTC by Conqxeror

Commit Message: Fix for issue #5348

##Commit Description:

This commit addresses issue #5348 by enhancing the sorting functionality in the GraphQL query generation. The modification includes the utilization of the `reduceRight` method to iterate over the `fieldsArray` in reverse order, constructing a nested structure for multi-sorting with nested fields.

Here's a breakdown of the changes:

- The `generateNestedSorting` function now efficiently handles a single sorter, extracting both the field and order.
- The field is split into an array of nested fields to support hierarchical sorting.
- Utilizing `reduceRight`, the function iterates over the nested fields in reverse order, constructing the nested structure with the order as the leaf value.

The `generateSorting` function has been updated accordingly, mapping over the array of sorters and applying the enhanced `generateNestedSorting` function to each sorter. This modification ensures the generation of accurate GraphQL sort parameters for scenarios involving multi-sorting with nested fields.

**IMPORTANT: Please ensure that any changes are discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

### Details of Changes

This modification enhances the sorting mechanism in the GraphQL query generation to properly handle multi-sorting with nested fields. It addresses the specific requirements outlined in issue #5348.

### Test Plan

Tests have been added/updated to verify the robustness of the code changes. The pull request is marked as a work in progress (`WIP:`) until thorough testing is completed.

### Closing Issues

This pull request closes issue #5348.

### Self Check before Merge

Please ensure the following tasks are completed before merging:

- [x] Corresponding issues are created/updated or not needed
- [x] Documentation is updated/provided or not needed
- [x] Examples are updated/provided or not needed
- [x] TypeScript definitions are updated/provided or not needed
- [x] Tests are updated/provided or not needed
- [x] Changesets are provided or not needed

2024-01-12 13:35 UTC, Conqxeror commented
Forgive if I made a mistake, I am a beginner in Open Source and am trying to improve myself. If there is anything to learn about or where I am making mistake, do let me know. I will try my best to improve myself.

2024-01-14 20:30 UTC, aliemir requested changes
Thank you for your effort @Conqxeror, can you check the [Contributing - Creating a Changeset](https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset) guide 🙏 We're keeping our versions with changesets and we need to have one for this PR 🚀 🚀 

Let us know if you have any issues about my review, we'd love to help further.

2024-01-14 20:30 UTC, aliemir commented on packages/hasura/src/utils/generateSorting.ts
> +export const generateSorting = (sorters) => {
Since `generateSorting` is exported (which is used if user customizes the data provider or swizzles it to customize) we need to preserve the types here like the current version (`GenerateSortingType`)

2024-01-14 20:30 UTC, aliemir commented on packages/hasura/src/utils/generateSorting.ts
> +const generateNestedSorting = (sorter) => {
Would love to see some extra tests for nested cases in `packages/hasura/test/utils/generateSorting.spec.ts` to make sure we're good to go.

2024-01-15 10:26 UTC, Conqxeror commented
Did the requested task, let me know if there's any change required or any mistake I am making.

2024-01-18 06:33 UTC, Conqxeror commented
@aliemir @BatuhanW  Am I making any mistake here? If so, then can you guide me through my mistake and I will try not to repeat it again? I am new to writing test cases, that might be the mistake, I think. Sorry for it.

2024-01-22 09:06 UTC, BatuhanW approved these changes
LGTM, added a minor comment, can you also review? @aliemir

2024-01-22 09:06 UTC, BatuhanW commented on packages/hasura/src/utils/generateSorting.ts
> +const generateNestedSorting = (sorter) => {
```suggestion
const generateNestedSorting: GenerateSortingType = (sorter) => {
```

2024-01-24 06:56 UTC, BatuhanW commented on .changeset/hungry-readers-begin.md
> +"@refinedev/your-package": patch
```suggestion
"@refinedev/hasura": patch
```

2024-01-24 06:56 UTC, BatuhanW commented on .changeset/hungry-readers-begin.md
> +Resolves #5348
```suggestion
fix(utils): handle nested fields in generateSorting #5348

This change addresses an issue with nested fields in the generateSorting utility function. The fix ensures that sorting works correctly when dealing with nested fields in the GraphQL query generation.
```

2024-01-24 06:58 UTC, omeraplak commented on .changeset/hungry-readers-begin.md
> +Resolves #5348
```suggestion
fix(utils): handle nested fields in generateSorting #5348

This changeset addresses an issue with nested fields in the generateSorting utility function. The fix ensures that sorting works correctly when dealing with nested fields in the GraphQL query generation.
```

2024-01-24 07:13 UTC, Conqxeror commented
@BatuhanW @omeraplak So sorry for disturbing you all with this small thing. I made the required change, I hope it helps.

2024-01-30 15:27 UTC, aliemir approved these changes

2024-01-30 16:19 UTC, aliemir requested changes
I've left some comments to the implementation, it's quite not finished and fails on build & tests.

Please make sure that we're using the proposed input/output from the issue in our test case.

2024-01-30 16:19 UTC, aliemir commented on packages/hasura/src/utils/generateSorting.ts
> +const generateNestedSorting: GenerateSortingType = (sorter) => {
Types should be updated, with the current state they do not reflect the implementation and also doesn't properly build.

```ts
export type HasuraSortOrder = "asc" | "desc";
export type HasuraSorting = HasuraSortOrder | { [key: string]: HasuraSorting };

export type HasuraSortingType = Record<string, HasuraSorting>;

export type GenerateSortingType = (
    sorting?: CrudSorting,
) => HasuraSortingType[] | undefined;
```

I've quickly wrote the new types but not sure if they're matching the implementation.

`generateNestedSorting` should be:

```ts
(sorter: CrudSort): HasuraSortingType
```

`generateSorting` should be:

```ts
GenerateSortingType
```

Notice that I've updated the `GenerateSortingType` to return an array of `HasuraSortingType`

2024-01-30 16:19 UTC, aliemir commented on packages/hasura/src/utils/generateSorting.ts
> +  }
This condition should be removed and this condition should never met, its not possible by type.

2024-01-30 16:19 UTC, aliemir commented on packages/hasura/src/utils/generateSorting.ts
> +  return fieldsArray.reduceRight((acc, curr) => ({ [curr]: acc }), order);
Additional typing might be required for `reduceRight` to be properly typed for the return value.

`order` can be written as `order as HasuraSorting` and the reduceRight expression can be used with `as as HasuraSortingType`.

2024-01-30 16:19 UTC, aliemir commented on packages/hasura/test/utils/generateSorting.spec.ts
> +    });
I don't think this test has tested by running 😅 `generateSorting` by implementation returns an array (The type is outdated and should be updated) and the expected case is an object.

The implementation, types and the test should be updated.

2024-01-31 08:22 UTC, Conqxeror commented
Ok I will fix that issue 👍🏻

2024-02-06 12:40 UTC, BatuhanW commented
Hey @Conqxeror looking forward to your updates for the next `March Release`. 🙌🏼

2024-03-05 08:32 UTC, merged