Fix(core): useform onFinishUpdate promise settlement #5460
refinedev/refine pull request #5511
Opened 2024-01-14 18:53 UTC by ShivamDureja

### Issue
This fixes #5460

### Description
This PR addresses the issue where the `useForm` hook, specifically in the code path for pessimistic mutationMode, had a promise executor that returned without ever calling reject (nor resolve). This resulted in the promise not being settled, causing the `onFinishUpdate` promise never to reject (nor resolve). 

### Changes
The `return` statement from line 581 in the useForm hook has been removed to ensure that the promise executor now correctly calls reject after the `onMutationError` executes. This adjustment guarantees that the `onFinishUpdate` promise is now set to reject, and the form state is restored with `isSubmitting` set to `false`.

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2024-01-14 20:37 UTC, aliemir requested changes
Thank you for your effort @ShivamDureja 🙏 I've made some comments to your changes, shouldn't be hard to update but let me know if you have any issues 🚀

2024-01-14 20:37 UTC, aliemir commented on packages/core/src/hooks/form/useForm.ts
> +                                onMutationError(error, values, context);
@ShivamDureja can we add a case to our `useForm` tests to check for this? Let's make sure we're handling this in our tests to be safe for the future.

2024-01-14 20:37 UTC, aliemir commented on .changeset/tame-poems-deny.md
> +"@refinedev/core": minor
```suggestion
"@refinedev/core": patch
```

I'm suggesting this to be marked as `patch` rather than `minor` 🙏

2024-01-14 20:37 UTC, aliemir commented on .changeset/tame-poems-deny.md
> +
```suggestion
```

We don't need this heading here, changesets will handle this for us when creating GitHub releases 🙏

2024-01-26 07:02 UTC, BatuhanW commented on packages/core/src/hooks/form/useForm.ts
> +                                onMutationError(error, values, context);
@ShivamDureja you need to modify this file: https://github.com/refinedev/refine/blob/master/packages/core/src/hooks/form/useForm.spec.tsx

2024-01-30 16:25 UTC, aliemir requested changes
Thank you for the effort! I've noticed that the required changes have only made for the "update" action and not for the "create" action. Can you please update the necessary lines as well? (L462 on useForm.ts)

2024-01-30 16:25 UTC, aliemir commented on packages/core/src/hooks/form/useForm.ts
> +                                onMutationError(error, values, context);
This line is repeated for the `"create"` action and has the same problem.

2024-01-30 18:48 UTC, ShivamDureja commented on packages/core/src/hooks/form/useForm.ts
> +                                onMutationError(error, values, context);
Thanks for the review @aliemir I have made changes accordingly

2024-01-31 14:45 UTC, BatuhanW requested changes
Currently, tests are failing, since now we don't have early `return onMutationError` now, `reject()` is being called, causing tests to fail. I'm not sure if we need to return new Promise with setTimeout here at all, need to discuss. @aliemir @omeraplak

2024-02-29 06:58 UTC, BatuhanW commented
Hey @ShivamDureja thanks for the PR! We'll be refactoring this hook more throughly, as there are many other issues that needs to be fixed together. We'll handle these issues under issue https://github.com/refinedev/refine/issues/5702.

2024-02-29 06:58 UTC, closed without merging