fix(strapi-v4): Strapi-v4-data-provider-not-working-with-nested-conditional-operators
refinedev/refine pull request #5516
Opened 2024-01-15 15:28 UTC by vidurkhanal

fix: Looks into solving [Issue #5479](https://github.com/refinedev/refine/issues/5479)

Explanation:

Current implementation of an utility function in strapi-v4 package, generateFilter(), doesn't handle all the edge cases, as pointed out by the issue owner.  The original code doesn't handle the case where the value of a conditional filter may be another conditional filter. It assumes that value of a conditional filter will be a logical filter.

I have chosen a recursive parsing approach to solve this and do believe produce expected raw string. However, the raw string after being parsed and stringified through "qs" adds unnecessary square braces to the URL params. Attached is the screenshot of the issue. The console.log is me logging the raw string before parsing and stringifying. 

![Screenshot 2024-01-15 at 10 00 43 AM](https://github.com/refinedev/refine/assets/65837961/1fc7ff6b-63c8-4d05-9450-6258c4106895)

### Test plan (required)

WIP: Added a new test case when there are recursive conditional filters.

### Closing issues
closes #5479 

### Self Check before Merge

Please check all items below before review.

-   [.] Corresponding issues are created/updated or not needed
-   [.] Docs are updated/provided or not needed
-   [.] Examples are updated/provided or not needed
-   [.] TypeScript definitions are updated/provided or not needed
-   [.] Tests are updated/provided or not needed
-   [.] Changesets are provided or not needed

2024-01-24 08:58 UTC, alicanerdurmaz commented
Hello @vidurkhanal, thanks for the PR. this is looks neat 🚀

Can you provide a [changeset](https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset) please?

2024-01-24 08:58 UTC, alicanerdurmaz requested changes

2024-01-24 08:58 UTC, alicanerdurmaz commented on packages/strapi-v4/src/utils/generateFilter.ts
> +    console.log(rawQuery);
```suggestion
    
```

2024-01-24 09:15 UTC, alicanerdurmaz commented
@vidurkhanal It looks like you're still working on it, so can you pull PR to the draft, please?

2024-02-07 06:25 UTC, alicanerdurmaz commented
> Hey @alicanerdurmaz , I was actually looking for suggestion from the team. The raw string after being parsed and stringified through "qs" adds unnecessary square braces to the URL params. So I was wondering if some one from the team could take a look. The screenshot is attached as a reference when console logging the raw string and stringified url by 'qs'

Oh, I see. Thanks for the detailed explanation. I will try to find a solution when I find time.

2024-02-09 14:56 UTC, rilrom commented
@vidurkhanal

Adding a `depth` on `parse` resolves your test case.

`const parsedQuery = parse(rawQuery, { depth: 50 });`

I recommend determining what maximum depth is suitable for our use-case.

2024-02-09 17:07 UTC, vidurkhanal commented
> @vidurkhanal
> 
> Adding a `depth` on `parse` resolves your test case.
> 
> `const parsedQuery = parse(rawQuery, { depth: 50 });`
> 
> I recommend determining what maximum depth is suitable for our use-case. The [qs documentation](https://github.com/ljharb/qs?tab=readme-ov-file#parsing-objects) provides some good explanations about depth.

Thanks @rilrom, I will look into that immediately.

2024-02-13 13:22 UTC, rilrom commented
No worries @vidurkhanal.

Feel free to reach out if you'd like me to adjust the solution and put together a changeset for you.

2024-02-27 07:35 UTC, BatuhanW commented
Closing the PR due to inactivity. @rilrom feel free to send a PR.

2024-02-27 07:35 UTC, closed without merging