feat(core): add success notification #5473
refinedev/refine pull request #5522
Opened 2024-01-16 17:39 UTC by Conqxeror

### Fixes #5473 but need green light to go further if I am going in right direction @BatuhanW @aliemir @omeraplak.

#### I will add the changeset, specs, documentation and required things in my next commit if I am going right.

#### Changes Made:

1. Added `successNotification` field to `AuthActionResponse` type.

    ```typescript
    type SuccessNotificationResponse = {
      message: string;
      description?: string;
    };

    export type AuthActionResponse = {
        success: boolean;
        redirectTo?: string;
        error?: RefineError | Error;
        [key: string]: unknown;
        successNotification?: SuccessNotificationResponse;
    };
    ```

2. Updated relevant hooks (`useForgotPassword`, `useLogin`, `useLogout`, `useRegister`, `useUpdatePassword`) to display success notifications when the `successNotification` object is provided.

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2024-01-17 07:44 UTC, BatuhanW reviewed
Hey @Conqxeror thanks for the PR! You can proceed with tests and docs.

Also added comment for `key` parameter. We can use unique key for each notification, like `forgot-password-success`, `login-success` etc.

Looking forward

2024-01-17 07:44 UTC, BatuhanW commented on packages/core/src/hooks/auth/useRegister/index.ts
> +      key: "success-notification",
```suggestion
      key: "register-success",
```

2024-01-17 20:39 UTC, arghyapolley commented on packages/core/src/hooks/auth/useForgotPassword/index.spec.ts
> +
A well structured code but consider adding comments for explaining the behaviour of hook which will be helpful for other devs to modify the code in future.

2024-01-17 20:47 UTC, arghyapolley commented on packages/core/src/hooks/auth/useLogin/index.spec.ts
>  });
after each test case, a proper clean up will add efficiency, avoid false results, prevent resource leaks, and interference can also be avoided.

2024-01-22 06:59 UTC, BatuhanW approved these changes
Great work 🏅

2024-01-24 07:01 UTC, omeraplak commented on .changeset/twelve-laws-grab.md
> +Updated the core and added successNotification field to AuthActionResponse and Updated relevant hooks to show success notification when successNotification object is provided and added specs.
```suggestion
---
"@refinedev/core": minor
---
feat(core): add success notification support for auth provider methods #5473

Updated the core and added successNotification field to AuthActionResponse and Updated relevant hooks to show success notification when successNotification object is provided and added specs.
```

2024-01-30 09:02 UTC, alicanerdurmaz requested changes

2024-01-30 09:02 UTC, alicanerdurmaz commented on packages/core/src/hooks/auth/useUpdatePassword/index.ts
> +      message: successNotification.message || "Success",
message and descriptions are required but have fallback value. It confuses me. should we delete fallback values? what do you think? @Conqxeror

2024-01-31 08:57 UTC, alicanerdurmaz approved these changes

2024-02-01 07:17 UTC, merged