feat(core): update @ant-design/charts package to v2 for finefoods-antd, blog-issue-tracker examples
refinedev/refine pull request #5523
Opened 2024-01-16 19:23 UTC by devhik0

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Closing: #5474 

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [X] Corresponding issues are created/updated or not needed
-   [X] Docs are updated/provided or not needed
-   [X] Examples are updated/provided or not needed
-   [X] TypeScript definitions are updated/provided or not needed
-   [X] Tests are updated/provided or not needed
-   [X] Changesets are provided or not needed

2024-01-19 18:15 UTC, devhik0 commented
I dont know what else needed to complete this but as i understand i needed to add tests but because of i made a lot changes at different filles and not made big changes on that files, there is no additional tests. But i am thinking `v2` of that lib is not breaking anything currently, so i dont know if tests required or not. Please guide me about that because i am new to codebase and dont want to break anything important.

2024-01-22 08:22 UTC, omeraplak commented on documentation/package.json
> +    "dev:lean": "cross-env DISABLE_DOCGEN=true DISABLE_VERSIONING=true DISABLE_EXAMPLES=true DISABLE_CHECKLISTS=true npm run start",
Could you please add the cross-env dependency to the devDependencies? Thank you for the improvementç

2024-01-22 08:22 UTC, omeraplak commented on examples/blog-issue-tracker/src/components/task/pie.tsx
> +            // },
```suggestion
```
Can we remove this if it's not needed?

2024-01-22 08:22 UTC, omeraplak commented on examples/blog-issue-tracker/tsconfig.json
> +    "noImplicitAny": false,
I'm not sure why we need this. Could you explain?

2024-01-22 08:22 UTC, omeraplak commented on examples/finefoods-antd/src/components/dashboard/dailyOrders/index.tsx
> +            //* here
What is the issue here? Should we work on it?

2024-01-22 08:22 UTC, omeraplak commented on examples/finefoods-antd/src/components/dashboard/dailyRevenue/index.tsx
> +            // todo: problem here
What is the issue here? Should we work on it?

2024-01-22 08:22 UTC, omeraplak commented on examples/finefoods-antd/src/components/dashboard/newCustomers/index.tsx
> +            // todo: problem here
What is the issue here? Should we work on it?

2024-01-22 08:22 UTC, omeraplak commented on examples/finefoods-antd/tsconfig.json
> +    "noImplicitAny": false,
same

2024-01-22 08:22 UTC, omeraplak commented on examples/finefoods-antd/src/pages/dashboard/index.tsx
> +                    {/* <DeliveryMap /> */}
```suggestion
                    <DeliveryMap />
```

2024-01-22 08:22 UTC, omeraplak commented on package.json
> +    "cross-env": "^7.0.3",
We don't need this dependency in the root package.json

2024-01-22 08:22 UTC, omeraplak commented on packages/devtools-server/package.json
> +    "build:client": "cross-env NODE_ENV=production tsc && vite build --config src/client/vite.config.ts",
Could you please add the cross-env dependency to the devDependencies? Thank you for the improvement

2024-01-22 12:47 UTC, devhik0 commented on examples/blog-issue-tracker/src/components/task/pie.tsx
> +            // },
That function was showing percents on that graph at v1, but because of api changes at v2 there is no `datum.percent` so yeah we can remove it but it wont show percents anymore. We need a manual calculation for percent to fix that. So its up to you removing or editing via calculation. I left it as a ref.

2024-01-22 13:04 UTC, devhik0 commented on examples/blog-issue-tracker/tsconfig.json
> +    "noImplicitAny": false,
I added it because it was giving type errors at build step at here `render: (_, datum) => {` and there was no type for these parameters at `ant-design/charts` lib docs. And didnt want to add new type just for that. This is the type for that function, but when i give that it s giving errors.
```
// examples\blog-issue-tracker\src\components\task\pie.tsx ln: 23
type RenderFunc = (text: string, datum: object, index: number) => String | HTMLElement;
23 |    render: (_: string, datum: object) => `${datum.value}`,
                                                      ~~~~ // > Property 'value' does not exist on type 'object'.
```

I could write it as `datum: {value: number}` but it doesnt belong to library itself. So i added that TS rule to prevent further `:any` errors. So we can remove it if we add its type.

2024-01-22 13:22 UTC, devhik0 commented on examples/finefoods-antd/src/components/dashboard/dailyOrders/index.tsx
> +            //* here
Yes, that `interaction` function is not working as expected when i add it. And cuz of we used same interaction at other graphs i had to comment it for a while to run it without problems. 
Here is what i see when i uncomment it
![err](https://github.com/refinedev/refine/assets/151969082/508ba72e-9375-4548-aeab-a8282d60c67b)
Here is normal state from example:
![normal](https://github.com/refinedev/refine/assets/151969082/0209e410-610a-4a5a-ab91-a05b36924e6f)

So i dont know if its related with library or our codebase but looks like something is breaking via version update

2024-01-22 13:24 UTC, devhik0 commented on examples/finefoods-antd/src/components/dashboard/dailyRevenue/index.tsx
> +            // todo: problem here
Same problem related with graph library api `interaction` [tooltip](https://ant-design-charts-next.antgroup.com/en/examples/statistics/column/#tooltip)

2024-01-22 13:24 UTC, devhik0 commented on examples/finefoods-antd/src/components/dashboard/newCustomers/index.tsx
> +            // todo: problem here
Same problem related with graph library api interaction [tooltip](https://ant-design-charts-next.antgroup.com/en/examples/statistics/column/#tooltip)

2024-01-22 13:30 UTC, devhik0 commented on examples/finefoods-antd/tsconfig.json
> +    "noImplicitAny": false,
I was having issues with `any` in `finefoods-antd` example, so added it to suspend related errors because it was not building due to them. Library doesnt have enough types to use when building with it. 
```tsx
interaction: {
                tooltip: {
                    render: (event, options) => { // any, any
```
For example this is what library says for that function [render](https://ant-design-charts-next.antgroup.com/en/options/plots/interaction/tooltip)
```tsx
{
  interaction: {
    tooltip: {
      render: (event, { title, items }) => <div>Your custom render content here.</div>,
    },
  },
}
```

2024-01-22 13:37 UTC, devhik0 commented on examples/finefoods-antd/src/pages/dashboard/index.tsx
> +                    {/* <DeliveryMap /> */}
When i uncomment it i am giving these errors at browser console. And dont know if its related with me or codebase.
```
Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: http://localhost:5173/
```

2024-01-22 13:51 UTC, devhik0 commented
All in all, thanks for your interest and helps. I really appreciate that. I fixed some of your comments but some of them needs your decision, so i am waiting for your review, thanks.

2024-01-23 07:13 UTC, BatuhanW requested changes

2024-01-23 07:13 UTC, BatuhanW commented on package.json
> +    "cross-env": "^7.0.3",
```suggestion
```

Let's remove it from here. And add it to `documentation/package.json` file's `devDependencies`.

2024-01-23 07:13 UTC, BatuhanW commented on packages/antd/src/hooks/table/useTable/useTable.ts
Let's revert changes here, as they are irrelevant.

2024-01-23 07:13 UTC, BatuhanW commented on documentation/package.json
> +    "dev:lean": "cross-env DISABLE_DOCGEN=true DISABLE_VERSIONING=true DISABLE_EXAMPLES=true DISABLE_CHECKLISTS=true npm run start",
You need to add `cross-env` package to >> this << package.json's devDependencies.

2024-01-23 07:13 UTC, BatuhanW commented on packages/antd/src/components/table/components/filterDropdown/index.tsx
>      mapValue?: (selectedKeys: React.Key[]) => any;
Let's revert changes here too.

For convenience, you can use the following:

```
git checkout master -- packages/antd/src/components/table/components/filterDropdown/index.tsx
git add .
git commit -m 'fix: revert unnecessary changes'
```

2024-01-23 07:13 UTC, BatuhanW commented on packages/live-previews/package.json
> +    "build": "next build && (rm -rf .next/cache || rmdir /s .next/cache)",
Let's revert this change also. `rmdir` will **only** work for Windows, breaking it for most of users -unix-.

We can use `rimraf` package.

2024-01-23 12:55 UTC, devhik0 commented
So i ve applied that changes you both suggested but want to push one commit for all. I am waiting for @omeraplak 's decisions for his review. At local everything looks okay for now.

2024-01-23 14:06 UTC, BatuhanW commented
> So i ve applied that changes you both suggested but want to push one commit for all. I am waiting for @omeraplak 's decisions for his review because they could require additional changes depends on current. At local everything looks okay for now.

Hey @devhik0 don't worry about commits, we are squashing it before merge, as one commit already. You don't need to do anything special.

2024-01-24 07:10 UTC, BatuhanW commented
Hey @devhik0 I think this PR is too immature to be reviewed.

Disabling `noImplicitAny` or commenting out code blocks because they are throwing errors/warnings isn't way to go. PR should address exactly these issues.

I'm closing this PR for now, feel free to re-open it once you address the issues!

Thanks for the efforts, looking forward to your updates 🙌🏼

2024-01-24 21:58 UTC, devhik0 commented
So i fixed all issues and errors, tested locally both examples and docs, everything looks okay. I pushed them but i cant reopen this PR, should i add them in another PR or can you reopen this PR, thanks.

2024-01-26 09:51 UTC, devhik0 commented
Its ready for review i think

2024-02-20 04:32 UTC, uzairx012 commented on packages/live-previews/package.json
> +    "build": "next build && (rm -rf .next/cache || rmdir /s .next/cache)",
gg

2024-02-26 14:17 UTC, alicanerdurmaz commented
This PR contains changes in too many different packages and is very difficult to review. The scope of changes is too broad and lacks explanation. So I am closing it.

2024-02-26 14:17 UTC, closed without merging