chore(core): context aware welcome page
refinedev/refine pull request #5525
Opened 2024-01-17 07:27 UTC by aliemir

Updated the `<WelcomePage />` component from `@refinedev/core` to warn if it's used outside of the `<Refine />` component. This gives `<WelcomePage />` a bit more purpose and lets it check if the Refine context is successfully initialized.

**If `<Refine />` is properly set up**

![localhost_5173_posts_pageSize=10 current=1](https://github.com/refinedev/refine/assets/11361964/859c8ef8-6c4e-47e4-a2f4-5699a928960f)

**If `<Refine />` is not properly set up**

![localhost_5173_posts_pageSize=10 current=1 (1)](https://github.com/refinedev/refine/assets/11361964/5b0a273f-5115-41ca-b230-49b3033be086)

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2024-01-17 10:51 UTC, omeraplak requested changes

2024-01-17 10:51 UTC, omeraplak commented on packages/core/src/components/pages/config-error/index.tsx
> +                            To learn more about this error, please visit{" "}
We should redirect it to a more specific document section.

2024-01-22 07:25 UTC, BatuhanW approved these changes

2024-01-24 09:18 UTC, alicanerdurmaz approved these changes

2024-01-25 06:38 UTC, omeraplak approved these changes

2024-02-01 07:17 UTC, merged