feat(core): configure useCan's queryOptions globally and through CanA…
refinedev/refine pull request #5538
Opened 2024-01-19 19:45 UTC by Conqxeror

feat: add queryOptions configuration to useCan and CanAccess

Add ability to configure useCan's queryOptions globally and through CanAccess component props. 

**Test plan:**

Added the specs.

**Closing issues:**

Closes #5472

**Self Check before Merge:**

Let me know if any changes are needed or if I miss something that should be covered in the description!
-   [x] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2024-01-19 19:47 UTC, Conqxeror commented
If my code is right as it was described then I can go further with docs? @BatuhanW

2024-01-22 07:17 UTC, BatuhanW requested changes

2024-01-22 07:17 UTC, BatuhanW commented on .changeset/great-socks-hunt.md
> +"@refinedev/core": patch
```suggestion
"@refinedev/core": minor
```

2024-01-22 07:17 UTC, BatuhanW commented on packages/core/src/components/canAccess/index.spec.tsx
> +                queryOptions={{ cacheTime: 10000 }}
Let's test queryOptions too.

2024-01-22 07:17 UTC, BatuhanW commented on packages/core/src/hooks/accessControl/useCan/index.ts
> +    const { queryOptions: globalQueryOptions } = useContext(AccessControlContext)?.options || {};
We are missing tests for these cases.

2024-01-22 11:01 UTC, BatuhanW commented
Hey @Conqxeror thanks for the PR! Added some minor comments. Also, could you update documentation in the following files to reflect changes?

- https://github.com/refinedev/refine/blob/master/documentation/docs/authorization/access-control-provider/index.md
- https://github.com/refinedev/refine/blob/master/documentation/docs/authorization/components/can-access/index.md

2024-01-23 14:05 UTC, BatuhanW commented
Hey @Conqxeror, thanks for the updates! I've checked briefly and it looks good, will send a detailed review later.

2024-01-23 14:29 UTC, Conqxeror commented
> Hey @Conqxeror, thanks for the updates! I've checked briefly and it looks good, will send a detailed review later.

Thanks for your quick response, @BatuhanW  ! Take your time with the detailed review—I appreciate your insights.

2024-01-24 11:23 UTC, BatuhanW requested changes
PR Looks good, added minor comments needs to be resolved before merge. Great job 🙌🏼

2024-01-24 11:23 UTC, BatuhanW commented on .changeset/great-socks-hunt.md
> +Ability to configure useCan's queryOptions globally and through CanAccess component.
```suggestion
feat: ability to configure useCan's queryOptions globally and through CanAccess component. #5472
```

2024-01-24 11:23 UTC, BatuhanW commented on documentation/docs/authorization/access-control-provider/index.md
> +By default, `enableAccessControl` is **true**, `hideIfUnauthorized` is **false**, and `queryOptions` is provided with default values.
```suggestion
By default, `enableAccessControl` is **true**, `hideIfUnauthorized` is **false**, and `queryOptions` is **undefined**.
```

2024-01-24 11:23 UTC, BatuhanW commented on documentation/docs/authorization/access-control-provider/index.md
>  }) => UseQueryResult<CanReturnType*>
Since we have `queryOptions` also in `CanParams` now, we can just use that interface.

```suggestion
}: CanParams) => UseQueryResult<CanReturnType*>
```

2024-01-24 11:23 UTC, BatuhanW commented on documentation/docs/authorization/components/can-access/index.md
> +### Properties
```suggestion
## Properties
```

2024-01-24 11:23 UTC, BatuhanW commented on documentation/docs/authorization/components/can-access/index.md
> +#### onUnauthorized
```suggestion
### onUnauthorized
```

2024-01-24 11:23 UTC, BatuhanW commented on documentation/docs/authorization/components/can-access/index.md
> +#### fallback
```suggestion
### fallback
```

2024-01-24 11:23 UTC, BatuhanW commented on documentation/docs/authorization/components/can-access/index.md
> +#### queryOptions
```suggestion
### queryOptions
```

2024-01-24 11:23 UTC, BatuhanW commented on packages/core/src/components/canAccess/index.tsx
> +        queryOptions: componentQueryOptions,
We are only accepting queryOptions here, but we should also get global query options with `useContext` and use it.

2024-01-24 11:23 UTC, BatuhanW commented on packages/core/src/hooks/accessControl/useCan/index.ts
> +    queryOptions: userQueryOptions, // Rename to avoid conflict with internal queryOptions
```suggestion
    queryOptions: hookQueryOptions,
```

2024-01-24 11:23 UTC, BatuhanW commented on packages/core/src/components/canAccess/index.spec.tsx
> +            expect(queryByText("Accessible")).toBeInTheDocument();
Let's also add queryOptions globally, and make sure both of them are passed to useCan method.

2024-01-28 21:30 UTC, Conqxeror commented on packages/core/src/components/canAccess/index.spec.tsx
> +            expect(queryByText("Accessible")).toBeInTheDocument();
Can you explain the task here? Do I need to add that in test or I need to work that in useCan hook?

2024-01-30 08:52 UTC, BatuhanW approved these changes
LGTM, great stuff! 🚀

2024-01-30 09:05 UTC, alicanerdurmaz approved these changes

2024-01-31 11:04 UTC, aliemir commented on packages/core/src/contexts/accessControl/index.tsx
> +                          queryOptions: options.queryOptions,
```suggestion
```

I think we can remove this line since we're spreading options above.

2024-01-31 11:04 UTC, aliemir approved these changes

2024-02-01 07:20 UTC, merged