feat(core): ability to pass an argument to usePermissions
refinedev/refine pull request #5609
Opened 2024-02-07 10:04 UTC by Cavdy

ability to pass an argument to usePermissions

### Closing issues

Closing: #5607 

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

2024-02-07 10:27 UTC, BatuhanW reviewed
Hey @Cavdy thanks for the quick PR, could you add some tests covering the change and add changeset?

https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

2024-02-07 10:34 UTC, Cavdy commented
alright @BatuhanW

2024-02-07 11:34 UTC, Cavdy commented
@BatuhanW test case written but not sure if I got it right

2024-02-07 14:00 UTC, alicanerdurmaz commented
> @BatuhanW test case written but not sure if I got it right

Hello @Cavdy, It looks neat 🚀 But, I have some suggestions:

In the following code, I mocked the `getPermissions` function to assert that it is called with "params" 
```tsx
   it("should accept params", async () => {
        const mockGetPermissions = jest.fn(() => Promise.resolve(["admin"]));
        const { result } = renderHook(
            ({ params }: { params: string }) => usePermissions({ params }),
            {
                initialProps: { params: "admin" },
                wrapper: TestWrapper({
                    authProvider: {
                        login: () => Promise.resolve({ success: true }),
                        check: () => Promise.resolve({ authenticated: true }),
                        onError: () => Promise.resolve({}),
                        logout: () => Promise.resolve({ success: true }),
                        
                        getPermissions: mockGetPermissions,
                    },
                    dataProvider: MockJSONServer,
                    resources: [{ name: "posts" }],
                }),
            },
        );

        await waitFor(() => {
            expect(result.current.isSuccess).toBeTruthy();
        });
        
        expect(mockGetPermissions).toHaveBeenCalledWith("admin");
        expect(result.current.data).toEqual(["admin"]);
    });
```

Also, I believe we need to test with `{ v3LegacyAuthProviderCompatible: true }` prop.
I think the assertions will remain the same but in this case we will pass extra prop.

2024-02-07 15:35 UTC, Cavdy commented
Thanks for the suggestion @alicanerdurmaz 

I have updated the test

2024-02-08 14:09 UTC, BatuhanW requested changes
Hey @Cavdy thanks for the PR! Appreciate that you took time to report the issue and create a PR for it!

Added a couple of minor comments. Besides them, we should also update `AuthProvider` interface, make sure `getPermissions` function accepts `Record<string, any>` **optionaly**.

2024-02-08 14:09 UTC, BatuhanW commented on packages/core/src/hooks/auth/usePermissions/index.ts
> +export type UsePermissionsProps<TData = PermissionResponse, TParams = unknown> = {
```suggestion
export type UsePermissionsProps<TData = PermissionResponse, TParams extends Record<string, any> = Record<string, any>> = {
```

Let's make this type `any object`.

2024-02-08 14:09 UTC, BatuhanW commented on packages/core/src/hooks/auth/usePermissions/index.ts
> +        queryFn: (legacyGetPermission ? () => legacyGetPermission(params) : () => Promise.resolve(undefined)) as (params?: unknown) => Promise<TData>,
```suggestion
        queryFn: (legacyGetPermission ? () => legacyGetPermission(params) : () => Promise.resolve(undefined)) as (params?: TParams) => Promise<TData>,
```

I think we can use `TParams` here since.

2024-02-08 14:09 UTC, BatuhanW commented on packages/core/src/hooks/auth/usePermissions/index.spec.ts
> +                initialProps: { params: 'admin', v3LegacyAuthProviderCompatible: true },
```suggestion
                initialProps: { params: { currentRole: 'admin' }, v3LegacyAuthProviderCompatible: true },
```

Let's make this one object as mentioned before to cover more use-cases with minimal changes.

2024-02-08 20:07 UTC, Cavdy commented on packages/core/src/hooks/auth/usePermissions/index.ts
> +        queryFn: (legacyGetPermission ? () => legacyGetPermission(params) : () => Promise.resolve(undefined)) as (params?: unknown) => Promise<TData>,
@BatuhanW  I tried replacing unknown to TParams, I got this error `Object literal may only specify known properties, and 'meta' does not exist in type 'readonly unknown[]'`, so I had to leave it as unknown

2024-02-29 07:57 UTC, BatuhanW reviewed
LGTM, added minor comments to be addressed before we merge.

2024-02-29 07:57 UTC, BatuhanW commented on .changeset/metal-bears-perform.md
> +## "@refinedev/core": minor
```suggestion
---
"@refinedev/core": minor
---
```

2024-02-29 07:57 UTC, BatuhanW commented on .changeset/metal-bears-perform.md
> +
Can we add example usage here?

2024-02-29 07:57 UTC, BatuhanW commented on packages/core/src/hooks/auth/usePermissions/index.spec.ts
> +      (props: PermissionsProps) => usePermissions({ ...props }),
```suggestion
      (props) => usePermissions({ ...props }),
```

2024-02-29 07:57 UTC, BatuhanW commented on packages/core/src/hooks/auth/usePermissions/index.spec.ts
> +      (props: PermissionsProps) => usePermissions({ ...props }),
```suggestion
      (props) => usePermissions({ ...props }),
```

2024-02-29 07:57 UTC, BatuhanW commented on packages/core/src/hooks/auth/usePermissions/index.spec.ts
> +
```suggestion
```

Jest should be able to infer hook prop's type. We shouldn't need this.

2024-02-29 08:04 UTC, BatuhanW reviewed
Oh, finally, we should update relevant documentation pages.

https://github.com/refinedev/refine/blob/master/documentation/docs/authentication/hooks/use-permissions/index.md

https://github.com/refinedev/refine/blob/master/documentation/docs/guides-concepts/authentication/auth-provider-interface.md

https://github.com/refinedev/refine/blob/master/documentation/docs/authentication/auth-provider/index.md

These updates should be simple and take no time.

2024-03-04 12:52 UTC, BatuhanW approved these changes
Great stuff 🚀 cc @alicanerdurmaz @aliemir

2024-03-04 14:40 UTC, aliemir approved these changes

2024-03-04 15:05 UTC, alicanerdurmaz approved these changes

2024-03-05 08:33 UTC, merged