feat(core): added custom optionLabel
refinedev/refine pull request #5610
Opened 2024-02-07 13:15 UTC by Conqxeror

Please provide enough information so that others can review your pull request:
Added option to add custom option label if provided.

 ‼️ If provided changes meet the required changes than I should go further with docs. ‼️

### Test plan (required)

Test case is given.

### Closing issues

## Closes #4880

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

2024-02-08 13:55 UTC, BatuhanW commented
Hey @Conqxeror thanks for the PR with great description as always!

Let's do the implementation according to the comment here: https://github.com/refinedev/refine/issues/4880#issuecomment-1742600902

`optionValue` and `optionLabel` params are currently string only, let's make each of them a union of string or function. And invoke the given function with `item` as in your implementation.

It would be amazing to implement similar changes for similar hooks other than `@refinedev/core`'s `useSelect`.

`@refinedev/antd` has following hooks which can be refactored in a similar way:
- useSelect
- useRadioGroup
- useCheckboxGroup

2024-02-08 14:22 UTC, Conqxeror commented
> Hey @Conqxeror thanks for the PR with great description as always!
> 
> Let's do the implementation according to the comment here: [#4880 (comment)](https://github.com/refinedev/refine/issues/4880#issuecomment-1742600902)
> 
> `optionValue` and `optionLabel` params are currently string only, let's make each of them a union of string or function. And invoke the given function with `item` as in your implementation.
> 
> It would be amazing to implement similar changes for similar hooks other than `@refinedev/core`'s `useSelect`.
> 
> `@refinedev/antd` has following hooks which can be refactored in a similar way:
> 
> * useSelect
> * useRadioGroup
> * useCheckboxGroup

Thanks, @BatuhanW ! Your feedback is always appreciated. I'll update `optionValue` and `optionLabel` as per the comment in [#4880 (comment)](https://github.com/refinedev/refine/issues/4880#issuecomment-1742600902). Also, extending these changes to `@refinedev/antd`'s `useSelect`, `useRadioGroup`, and `useCheckboxGroup` sounds great.

2024-02-09 21:05 UTC, Conqxeror commented
Hello @BatuhanW I wanted to know if all the required changes are satisfied or not. If so then I can go further with the docs. 

Review it whenever you are free, its okay if you take time.

2024-03-01 07:21 UTC, aliemir requested changes
Thank you for the PR @Conqxeror! I've left couple of comments for the changes required.

2024-03-01 07:21 UTC, aliemir commented on packages/core/src/hooks/useSelect/index.ts
> +    : (item: TData) => string;
The type doesn't seems correct. Here's a demonstration and the corrected type example [here in TS playground](https://www.typescriptlang.org/play?#code/PTAEBcE8AcFNQDIEMBGsA2AeAKgESeEqLAB7iwB2AJgM6gBKsAxgPYBOVmN4bAlhQHMANKCQVIAPlABeBs3adufQSLGSpsgNaxILAGag8BIqXLU6S-gIBQIUPYcB+UNt0GjhW2Af2AXPYAKXnIAW38PJABKGSlLQQBua2soOERUDBx8QmIySlo5Vg4uHitVcQ0ChWLlYVFyioDXfUMsk1zzUDibH1BnJvdW6x7-ClgAN1g2aIAfUACg0PDW6OlYksFIxOSYeAAFNhYqAFcmcBlQAG8hh14qEaOQtDZEn3Bg9Fh-LpeHJgJYATsSD+C6gW73R6TUAAXx+9iosBoTD40DeLAoX3WAjhnUI4CONH8ACJoEcUOheDQABawKhE0CzIlsWAAK2Y5DpDNARKobCQenARMS0KSrAo3FA6HS6H8yDQWH2hxO4AqRLe4A+QqSdjFEql8oATLLpZhFcdTqq9CwWELQHZJgc2NqwLqzvqMABmY3y00Hc0q84BaArKTQAB0CKRKLRFHidrALE0QA)

2024-03-01 07:21 UTC, aliemir commented on packages/antd/src/hooks/fields/useCheckboxGroup/index.ts
> +    : (item: TData) => string;
No need to add these here they will be provided by the `UseSelectProps` of `@refinedev/antd` and use select props from `@refinedev/core`. Same also applies to `useRadioGroup`

2024-03-01 07:21 UTC, aliemir commented on packages/core/src/hooks/useSelect/index.ts
> +        field: optionLabel as string,
I think we can add a new prop named `searchLabel` and make `optionLabel` the fallback value if its a string. Default value will be `"title"` (like `optionLabel`) but if a `searchLabel` is passed then it will use it (should be `key TData`).

something like this:

```suggestion
        field: searchLabel ?? (typeof optionLabel === "string" ? optionLabel : "title")
```

and ensure that we're prioritizing `searchLabel` and then `optionLabel` with type string  and if not, fallback to default `optionLabel` which is `"title"`. 

But before making any changes, let's validate this thought 😅 @alicanerdurmaz @BatuhanW

While we're adding `searchLabel`, I think it's best to also add `searchOperator` which is now hardcoded to `"contains"`. When using a custom `optionLabel` with function type, these don't really make sense to me to use.

2024-03-06 10:25 UTC, alicanerdurmaz approved these changes

2024-03-06 10:25 UTC, alicanerdurmaz commented on packages/core/src/hooks/useSelect/index.ts
> +  searchLabel?: keyof TData extends string ? keyof TData : never;
I don't think naming and JSDoc is descriptive here
Maybe It can be something like this

```suggestion
  /**
   * Field name to search for
   * @default `"title"``
   */
  fieldToSearch?: keyof TData extends string ? keyof TData : never;
```

2024-03-06 10:32 UTC, alicanerdurmaz requested changes

2024-03-06 10:32 UTC, alicanerdurmaz commented on packages/core/src/hooks/useSelect/index.ts
> +  searchLabel?: keyof TData extends string ? keyof TData : never;
I don't think naming and JSDoc is descriptive here
Maybe It can be something like this

```suggestion
  /**
   * Field name to search for
   * @default `"title"``
   */
  fieldToSearch?: keyof TData extends string ? keyof TData : never;
```

2024-03-06 10:57 UTC, BatuhanW commented on packages/core/src/hooks/useSelect/index.ts
> +  searchLabel?: keyof TData extends string ? keyof TData : never;
Nice catch. Maybe `searchField` ?

2024-03-06 12:46 UTC, alicanerdurmaz approved these changes

2024-03-06 13:35 UTC, aliemir approved these changes

2024-03-06 14:03 UTC, merged