Fix: Use Material UI notifications provider in documentation code sample
refinedev/refine pull request #5621
Opened 2024-02-10 02:44 UTC by Mohamed-khattab

The documentation provided an incorrect code sample that utilized the notifications provider from the Ant Design UI package instead of the intended Material UI notifications provider. This commit updates the code sample to import and use the Material UI notifications provider from @refinedev/mui as recommended in the documentation.

Changes:
- Updated import statement to import the notification provider from @refinedev/mui.
- Updated the code sample to use the Material UI notifications provider in the <Refine /> component.

## What is the current behavior?
The current behavior is that the documentation provides an incorrect code sample using the notifications provider from the Ant Design UI package instead of the Material UI notifications provider.

## What is the new behavior?
The new behavior is that the documentation code sample is updated to import and use the Material UI notifications provider from @refinedev/mui as recommended.

fixes #5620 (issue)

Notes for reviewers
No additional notes. Everything should be straightforward.

2024-02-11 14:09 UTC, BenMusch commented
LGTM, thanks for the quick turnaround!

2024-02-12 08:39 UTC, BatuhanW requested changes
Hey @Mohamed-khattab thanks for the PR!

`notificationProvider` is deprecated, let's use `useNotificationProvider` here.

2024-02-12 08:39 UTC, BatuhanW commented on documentation/docs/ui-integrations/material-ui/introduction/index.md
> +import { useNotificationProvider, notificationProvider } from "@refinedev/mui";
```suggestion
import { useNotificationProvider } from "@refinedev/mui";
```

2024-02-12 08:39 UTC, BatuhanW commented on documentation/docs/ui-integrations/material-ui/introduction/index.md
> +    <Refine notificationProvider={notificationProvider}>
```suggestion
    <Refine notificationProvider={useNotificationProvider}>
```

2024-02-12 13:26 UTC, BatuhanW approved these changes

2024-02-12 13:26 UTC, merged