docs(tutorial): Material UI option
refinedev/refine pull request #5672
Opened 2024-02-23 06:18 UTC by aliemir

Added Material UI option to the UI Libraries and Next Steps units in tutorial.

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [x] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## Notes for reviewers

Inferencer step is not working for both Ant Design and Material UI and throws an error when rendering the inferred view

2024-02-26 12:10 UTC, omeraplak approved these changes

2024-02-29 07:39 UTC, BatuhanW requested changes

2024-02-29 07:39 UTC, BatuhanW commented on documentation/tutorial/next-steps/cli/react-router/material-ui/index.md
> +npm run refine add i18n
```suggestion
npm run refine add provider i18n
```

2024-02-29 07:39 UTC, BatuhanW commented on documentation/tutorial/next-steps/cli/react-router/material-ui/index.md
> +We can use the `add` command to create a new provider, with available provider options including:
```suggestion
We can use the `npm run refine add provider` command to create multiple providers, with available provider options including:
```

2024-02-29 07:39 UTC, BatuhanW commented on documentation/tutorial/ui-libraries/crud-components/material-ui/react-router/sandpack.tsx
> +// updatxes
```suggestion
// updates
```

2024-02-29 07:39 UTC, BatuhanW commented on documentation/tutorial/next-steps/cli/react-router/material-ui/index.md
> +The `add` command creates new resources and providers with a single command.
```suggestion
The `add` command can be used to create resources and providers.
```

2024-02-29 07:39 UTC, BatuhanW commented on documentation/tutorial/next-steps/inferencer/react-router/material-ui/index.md
> +Refine's [`@refinedev/inferencer`](/docs/packages/inferencer) package is a powerful tool that generates views for resources based on their data structure. The aim is to reduce the amount of time spen
I think we are setting a high expectation here with the first paragraph here:

`package is a powerful tool that generates views for resources based on their data structure. ....  you can get a fully functional view ...`

Even though we are adding a note later, I think it's better to have 2 short paragraphs explaining it.

```suggestion
Refine's [`@refinedev/inferencer`](/docs/packages/inferencer) package can be used to scaffold initial code for your resource pages based on API responses.

Generated code aren't guaranteed to work perfectly. This tool meant to be used locally to speed up the development process by generating the initial code and shouldn't be used on production.
```

2024-02-29 07:39 UTC, BatuhanW commented on documentation/tutorial/next-steps/inferencer/react-router/material-ui/index.md
> +:::
Having shorters paragraph above, we can remove this one.

```suggestion
```

2024-02-29 07:39 UTC, BatuhanW commented on documentation/tutorial/next-steps/inferencer/react-router/material-ui/sandpack.tsx
> +} from "@refinedev/mui";
Let's adjust indentation in example code blocks.

2024-03-05 07:26 UTC, necatiozmen commented on documentation/tutorial/next-steps/devtools/react-router/material-ui/index.md
> +Then we'll need to wrap our application with the `<DevtoolsProvider />` component. The `<DevtoolsProvider />` component should be wrapped around the `<Refine />` component in the `App` component. We'
```suggestion
Then we'll need to wrap our application with the `<DevtoolsProvider />` component. ensuring it wrapped around the `<Refine />` component in the `App` component. We'll also be importing the `<DevtoolsPanel />` component to have a nice shortcut to open the Devtools in our application.
```

2024-03-05 07:26 UTC, necatiozmen commented on documentation/tutorial/next-steps/devtools/react-router/material-ui/index.md
> +After you've installed and setup the Devtools package, you'll be able to see the small devtools panel on the bottom of your application. Clicking on the panel will open the devtools. Then you can cli
```suggestion
After installing and setting up the Devtools package, a small devtools panel will appear at the bottom of your application. Clicking on it will open the devtools, allowing you to access the monitoring screen by clicking on "Monitor" in the sidebar.
```

2024-03-05 07:26 UTC, necatiozmen commented on documentation/tutorial/next-steps/devtools/react-router/material-ui/index.md
> +You'll be able to filter the queries and mutations by their type, resource, status and the component/hook that triggered them. Also, you can pick the component you want to filter on your UI by using
```suggestion
You can filter the queries and mutations by their type, resource, status and the component/hook that triggered them. Also, you can select the component to filter on your UI by using the selector.
```

2024-03-05 07:26 UTC, necatiozmen commented on documentation/tutorial/next-steps/summary/react-router/material-ui/index.md
> +Congratulations! You've completed the tutorial, learning how to create a CRUD application from scratch using Refine and understanding its basic concepts. With this knowledge, you can now use Refine t
```suggestion
Congratulations! You've completed the tutorial by learning how to create a CRUD application from scratch using Refine and understanding its basic concepts. With this knowledge, you can now use Refine to develop your own applications without limitations.
```

2024-03-07 07:50 UTC, BatuhanW approved these changes

2024-03-07 08:43 UTC, merged