feat(mui): add circular progress to <Show>
refinedev/refine pull request #5710
Opened 2024-03-01 07:11 UTC by issa012

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?
<Show isLoading={true}>  in MUI doesn't show loading spinner
## What is the new behavior?
Added loading spinner.
fixes #5668

## Notes for reviewers

Hello. This is my first PR ever. I have added the <Backdrop> along with <CircularProgress> to render a loading spinner. Should I add the possibility to pass props to these components?
Also, what color should they be?

2024-03-04 11:08 UTC, BatuhanW reviewed
Hey @issa012 thanks for the PR!

It seems we have conflicts, let's fix them and address review comments.

2024-03-04 11:08 UTC, BatuhanW commented on packages/mui/src/components/crud/show/index.tsx
> +            <CardContent {...(contentProps ?? {})}>
Let's add tests covering these changes.

2024-03-04 11:08 UTC, BatuhanW commented on packages/mui/src/components/crud/show/index.tsx
> +        <Card {...(wrapperProps ?? {})} sx={{ position: "relative" }}>
Could you provide a demo video using one of the examples?

2024-03-05 12:17 UTC, issa012 commented on packages/mui/src/components/crud/show/index.tsx
> +        <Card {...(wrapperProps ?? {})} sx={{ position: "relative" }}>
https://github.com/refinedev/refine/assets/57894795/17bde139-fc51-42ec-9b47-bacdc1caeda4

Here

2024-03-05 12:17 UTC, issa012 commented on packages/mui/src/components/crud/show/index.tsx
> +        <Card {...(wrapperProps ?? {})} sx={{ position: "relative" }}>
Thanks for the reivew!

2024-03-05 12:20 UTC, issa012 commented on packages/mui/src/components/crud/show/index.tsx
> +        <Card {...(wrapperProps ?? {})} sx={{ position: "relative" }}>
I am also thinking about adding backdropProps, so that it is possible to pass props to the <Backdrop> component, similar to other props, such as contentProps etc. I think it is a good idea. What do you think?

2024-03-06 10:37 UTC, aliemir commented on packages/mui/src/components/crud/show/index.tsx
> +        <Card {...(wrapperProps ?? {})} sx={{ position: "relative" }}>
Hey @issa012, thanks for the video but it looks like you've recorded the one for the `<List />` 😅

About the same line, I think if user sends `wrapperProps.sx` its overwritten by the latter. Can we update this line to also cover `wrapperProps.sx`?

```suggestion
        <Card {...(wrapperProps ?? {})} sx={{ position: "relative", ...wrapperProps?.sx }}>
```

2024-03-06 10:41 UTC, alicanerdurmaz requested changes

2024-03-06 10:41 UTC, alicanerdurmaz commented on packages/mui/src/components/crud/show/index.tsx
> +        <Card {...(wrapperProps ?? {})} sx={{ position: "relative" }}>
```suggestion
        <Card {...(wrapperProps ?? {})} sx={{ position: "relative", ...wrapperProps.sx }}>
```

2024-03-06 11:31 UTC, issa012 commented on packages/mui/src/components/crud/show/index.tsx
> +        <Card {...(wrapperProps ?? {})} sx={{ position: "relative" }}>
Hi. You're right, I recorded the wrong component. Here is the correct component.

https://github.com/refinedev/refine/assets/57894795/34812369-cc9a-4e4e-965f-505019198f8e
I have made some changes. I moved the sx={{position: "relative"}} to CardContent. It can also now be overridden. The color of the backdrop is now similar to the color when <DataGrid> is loading.

2024-03-06 13:41 UTC, aliemir commented on packages/mui/src/components/crud/show/index.tsx
> +                        bgcolor: "rgba(255, 255, 255, 0.38)",
Not sure if the hardcoded color is appropriate here. I think it's best to use the current theme to decide `bgColor`. We can do `theme.palette.background.paper` (I think this is what the `<Card />` use) and use the `alpha` method from `@mui/material/styles` to adjust the opacity. This way we don't have to worry about light/dark schemes I guess 🤔 

Can we try to make this change @issa012? It would be great if you can update this line and test it 🙏

2024-03-06 13:43 UTC, aliemir commented on packages/mui/src/components/crud/show/index.tsx
> +        <Card {...(wrapperProps ?? {})} sx={{ position: "relative" }}>
Thank you for the update @issa012!

2024-03-06 14:15 UTC, issa012 commented on packages/mui/src/components/crud/show/index.tsx
> +                        bgcolor: "rgba(255, 255, 255, 0.38)",
I tested it. Now it is the same color as in <List> component in light and dark modes. I used theme.palette.action.disabledOpacity. Thanks a lot for reviews!

2024-03-26 05:59 UTC, issa012 commented
Hello. What tests should I add for this change? Similar Antd component does not have any tests regarding the loading state. Should I update the documentation?

2024-04-11 06:44 UTC, closed without merging