feat(mui): editable Data Grid
refinedev/refine pull request #5744
Opened 2024-03-13 08:39 UTC by beg1c

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [x] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the new behavior?

Data Grid can now be edited by specifying `editable` property on DataGrid column definition, just as in MUI Data Grid documentation. `useDataGrid` will now utilize existing Data Grid props `processRowUpdate`, `onRowEditStart` and `onCellEditStart` to update resource whenever `processRowUpdate` is triggered. 

fixes #5656 (issue)

## Notes for reviewers

This is lightweight implementation of this functionality, using only existing Data Grid props. This functionality can be later extended for handling multiline editing.

`processRowUpdate` must return value to Data Grid, that is why we must return oldRow if mutation does not succeed.

I've set title column on `examples/table-material-ui-use-data-grid` as editable.

2024-03-13 09:44 UTC, beg1c commented
Some problems occurred because my fork was not completely synced. Resolved it now.

2024-03-14 15:10 UTC, BatuhanW requested changes
Hey @beg1c thanks for the PR! Added some comments.

2024-03-14 15:10 UTC, BatuhanW commented on examples/table-material-ui-use-data-grid/src/pages/posts/list.tsx
> +      },
We have cypress e2e tests for this example, let's update them to test this new behavior.

2024-03-14 15:10 UTC, BatuhanW commented on packages/mui/src/hooks/useDataGrid/index.ts
> +  });
Users may provide custom resource, let's make sure we handle that and other similar props if any.

2024-03-14 15:10 UTC, BatuhanW commented on packages/mui/src/hooks/useDataGrid/index.ts
> +  const { setId, onFinish: onFinishEdit } = edit;
I think this is useless, better to destruct from hook.

2024-03-14 15:10 UTC, BatuhanW commented on packages/mui/src/hooks/useDataGrid/index.ts
> +      onRowEditStart: (params) => setId(params?.id),
Let's add tests for the updates in this file.

2024-03-18 22:30 UTC, beg1c commented on packages/mui/src/hooks/useDataGrid/index.ts
> +      onRowEditStart: (params) => setId(params?.id),
We will have to extend `UseDataGridReturnType` with `onFinish`, `setId`, `id` and maybe `formLoading` from `UseFormReturnType`. That will also allow users to completely override this functionality and call mutations on different events. 
I was not able to write tests without these return types as only way to call `setId` is to call `onCellEditStart` which accepts a lot of different arguments that I can not replicate.

2024-03-19 09:00 UTC, beg1c commented
@BatuhanW Added tests and some changes.  I'd appreciate it if you could take a look when you have a moment.  I plan to update the documentation later since there might be more changes before merging. Additionally, it seems we're lacking functionality where the user can call `useForm` with different `action` based on the call. This would enable users to extend the functionality and create new rows in the DataGrid, not just edit existing ones. Same goes for delete. I will look into it more when I catch time.

2024-03-19 14:57 UTC, BatuhanW commented
> @BatuhanW Added tests and some changes. I'd appreciate it if you could take a look when you have a moment. I plan to update the documentation later since there might be more changes before merging. Additionally, it seems we're lacking functionality where the user can call `useForm` with different `action` based on the call. This would enable users to extend the functionality and create new rows in the DataGrid, not just edit existing ones. Same goes for delete. I will look into it more when I catch time.

@beg1c appreciate the effort! Looks good initially, I'll review more in detail later. Also cc @aliemir @alicanerdurmaz

2024-03-20 07:30 UTC, alicanerdurmaz approved these changes

2024-03-20 07:30 UTC, alicanerdurmaz commented on packages/mui/src/hooks/useDataGrid/index.ts
> +  formProps?: UseFormProps<TQueryFnData, TError, TData>;
maybe we should omit these props `"autoSave" | "action" | "redirect"` because `action` and `redirect` can't be overridden and `autoSave` doesn't  work because `processRowUpdate` is triggered `onBlur`


```suggestion
  formProps?: Omit<
    UseFormProps<TQueryFnData, TError, TData>,
    "autoSave" | "action" | "redirect"
  >;
```

@BatuhanW @aliemir @beg1c  What do you think?

2024-03-20 07:32 UTC, alicanerdurmaz requested changes

2024-03-20 07:32 UTC, alicanerdurmaz commented on packages/mui/src/hooks/useDataGrid/index.ts
> +  formProps?: UseFormProps<TQueryFnData, TError, TData>;
maybe we should omit these props `"autoSave" | "action" | "redirect"` because `action` and `redirect` can't be overridden and `autoSave` doesn't  work because `processRowUpdate` is triggered `onBlur`


```suggestion
  formProps?: Omit<
    UseFormProps<TQueryFnData, TError, TData>,
    "autoSave" | "action" | "redirect"
  >;
```

@BatuhanW @aliemir @beg1c  What do you think?

2024-03-20 20:39 UTC, beg1c commented on packages/mui/src/hooks/useDataGrid/index.ts
> +  formProps?: UseFormProps<TQueryFnData, TError, TData>;
@alicanerdurmaz I agree!

2024-03-21 23:41 UTC, beg1c commented
@BatuhanW @alicanerdurmaz updated docs. Do you think we should accept boolean `editable` as prop to `useDataGrid` or is this PR over? For further usage I don't think we need that prop, but we could break older versions if we don't accept it. If some users have their own implementation of editable datagrid, and they didn't declare `processRowUpdate` on `<DataGrid />` component, `<DataGrid />` `processRowUpdate` will trigger our `useForm` `onFinish` every time column is commited.

2024-03-26 07:13 UTC, alicanerdurmaz commented
> @BatuhanW @alicanerdurmaz updated docs. Do you think we should accept boolean `editable` as prop to `useDataGrid` or is this PR over?
> 
> For further usage I don't think we need that prop, but we could break older versions if we don't accept it. If some users have their own implementation of editable datagrid, and they didn't declare `processRowUpdate` on `<DataGrid />` component, `<DataGrid />` `processRowUpdate` will trigger our `useForm` `onFinish` every time column is commited.
> 
> So for example if someone defined their data grid as:
> 
> ```
> <DataGrid
>     {...dataGridProps}
>     columns={columns}
>     onRowEditStart={ownSetIdFunction}
>     onRowEditCommit={ownMutateFunction}
> />
> ```
> 
> which is wrong as `processRowUpdate` should be used for migrations from `DataGrid version 6`, our `processRowUpdate` from `...dataGridProps` spread could break that functionality.
> 
> I don't know, what do you think?

I believe you are right. We should accept `editable` prop.

something like this:
```tsx
useForm({
  queryOptions: {
    enabled: editable,
  },
});

processRowUpdate: async (newRow, oldRow) => {
   if(!editable) return
   /* .... */
}
  
 ```

2024-04-03 06:46 UTC, closed without merging

2024-04-03 06:48 UTC, BatuhanW commented
Hey @beg1c we've merged `releases/april` branch, could you re-open your PR?