Feat/allow translation for required field messages
refinedev/refine pull request #5868
Opened 2024-04-19 11:48 UTC by Ac-Srikanth

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [x] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behaviour?
Auth Input fields which were required  had no custom error message feature.

## What is the new behaviour?
can provide Custom error message  for required Auth Input fields with correct translation.

fixes # (issue)
#[5855](https://github.com/refinedev/refine/issues/5855)

## Notes for reviewers
This is my first PR , please do suggest changes or more things to be added if i missed out any.

2024-04-21 17:19 UTC, aliemir requested changes
Hey @Ac-Srikanth thank you for the PR! We'll review it soon. Before we do, can you please check [Creating a changeset](https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset) section in our contributing guide? We'll need a changeset for the related changes 💯

2024-04-25 10:06 UTC, aliemir commented
Hey @Ac-Srikanth thank you for the update! I was reviewing the PR and just noticed that we also require a small update on our live previews package to reflect i18n changes;

Can you provide the keys you've created to the files below:

- `packages/live-previews/public/locales/en/common.json`
- `packages/live-previews/public/locales/de/common.json`

We've marked this PR to be included in our May release and I'm hoping to complete its review if you can provide the changes I mentioned above 🙏

2024-04-25 10:33 UTC, Ac-Srikanth commented
hey @aliemir thank you for the review , i will add the keys to these files as well and yes this can be done before the may release. Very soon you can see the changes.

2024-04-25 13:38 UTC, aliemir commented on .changeset/cold-emus-visit.md
> +"@refinedev/live-previews": minor
live-previews is not published so we're not including it in our changesets. We can safely remove it.
```suggestion
```

2024-04-25 13:41 UTC, aliemir approved these changes
Left a small change request in the changeset, other than that I think we're good to go! Thank you for your contribution! 🚀

2024-04-25 16:31 UTC, aliemir approved these changes

2024-04-25 21:43 UTC, merged