fix(appwrite): make `meta.permissions` overrideable
refinedev/refine pull request #5886
Opened 2024-04-24 10:15 UTC by abdelrahman-essawy

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Users couldn't override the default `readPermissions` /  `writePermissions` values.

## What is the new behavior?

Users are able to override the default permissions by passing `options.defaultReadPermissions` / `options.defaultWritePermissions` OR by passing `meta?.readPermissions` / `meta?.writePermissions`.

If user passed `options.defaultReadPermissions` AND `meta?.readPermissions`, then the priority will be as following:

`meta?.readPermissions` if not? then `options.defaultReadPermissions` if not? then `Role.any()`.

fixes #5767 

## Notes for reviewers

This should be compatible with old users who are not passing `meta?.readPermissions` and expecting to get `Role.any()` by default.

2024-04-24 10:20 UTC, aliemir requested changes
Hey @abdelrahman-essawy thank you for the contribution! I think the `defaultReadPermissions` and `defaultWritePermissions`  should respect the previous values:

```ts
[
  Permission.read(Role.any()),
  Permission.write(Role.any()),
]
```

to avoid any breaking changes due to this PR.

Am I missing something here?

2024-04-24 10:25 UTC, abdelrahman-essawy commented
Hey @aliemir , please check out my discussion https://github.com/refinedev/refine/issues/5767#issuecomment-2006964445 with @BatuhanW on this regard, and tell me what you think.

2024-04-25 09:54 UTC, aliemir commented
> Hey @aliemir , please check out my discussion [#5767 (comment)](https://github.com/refinedev/refine/issues/5767#issuecomment-2006964445) with @BatuhanW on this regard, and tell me what you think.

Just discussed with @BatuhanW about this again. Here on [Default Values - Permissions docs of Appwrite](https://appwrite.io/docs/advanced/platform/permissions#default-values) says that if there's no explicit permissions, client SDK will provide permissions to the author.

Tested out with our `data-provider-appwrite` example and used two different accounts. I can confirm that I was unable to update the record created with another account when I don't pass explicit permissions. 

I confirm that this will be a breaking change if default permissions will be empty. Can you make the necessary changes to avoid this breaking change? 🙏 If you can, please let us know. We'll mark this PR to be included in our May release 🚀 

We'll review again after you make the changes 🙌

2024-04-26 13:28 UTC, aliemir requested changes
Thank you for the update @abdelrahman-essawy, just left two small comments. Hope you can have time to check those 🙏

2024-04-26 13:28 UTC, aliemir commented on packages/appwrite/src/dataProvider.ts
> +    databaseId,
Can we also add the `"default"` here to make sure we keep the default values correct?

2024-04-26 13:28 UTC, aliemir commented on packages/appwrite/src/dataProvider.ts
> +  defaultWritePermissions?: Permission[];
Since we've added the ability to configure permissions through `dataProvider` instance. Can we add a section like "Handling Permissions" to our Appwrite docs? https://refine.dev/docs/data/packages/appwrite/#example Adding a small section above "Example" section will be enough I guess. 

Can you add this?

2024-04-26 13:39 UTC, abdelrahman-essawy commented
> Thank you for the update @abdelrahman-essawy, just left two small comments. Hope you can have time to check those 🙏

you are very welcome, sure thing!

2024-05-02 08:46 UTC, aliemir commented on .changeset/tasty-garlics-notice.md
> +fixing an issue which didn't allow users to override the default `readPermissions` / `writePermissions` values `Role.any()`, by passing `defaultReadPermissions` / `defaultWritePermissions` OR by pass
```suggestion
fix: add ability to customize default permission without explicitly passing them on each mutation

fixing an issue which didn't allow users to override the default `readPermissions` / `writePermissions` values `Role.any()`, by passing `defaultReadPermissions` / `defaultWritePermissions` OR by passing `meta?.readPermissions` / `meta?.writePermissions`.
```

2024-05-02 08:46 UTC, aliemir approved these changes

2024-05-02 09:01 UTC, merged