fix: lock antd-icons dependency version
refinedev/refine pull request #5934
Opened 2024-05-08 17:49 UTC by bombillazo

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Re-add locking of "@ant-design/icons" to known working behavior

## What is the new behavior?

fixes # (issue)

## Notes for reviewers

2024-05-23 07:03 UTC, BatuhanW commented
Hey @bombillazo can you do the changes for every occurence of this package? Also don't forget to do `pnpm install` after the changes, so `pnpm-lock.yaml` will also be updated. Also make sure to create patch changeset for affected packages.

2024-05-23 14:10 UTC, bombillazo commented
![image](https://github.com/refinedev/refine/assets/44002321/d8ad69ea-5c6f-4f1a-821e-a49a54af22d3)

This error pops up after trying to update the branch

2024-05-24 11:13 UTC, aliemir commented
> ![image](https://private-user-images.githubusercontent.com/44002321/333216507-d8ad69ea-5c6f-4f1a-821e-a49a54af22d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDk0MTMsIm5iZiI6MTcxNjU0OTExMywicGF0aCI6Ii80NDAwMjMyMS8zMzMyMTY1MDctZDhhZDY5ZWEtNWM2Zi00ZjFhLTgyMWUtYTQ5YTU0YWYyMmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDExMTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5N2Y0Y2QzMDE4OThhMDU3MDBhY2NmYjMxMDk0Yzg1OWM4NzE0MjdhZTg3NzIyMzA5ZGMwZTY3M2IyOTQyYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eU2W_sybSHb_cLaC1G4ROMfKIF2JlmtOapicOVrEkM4)
> 
> This error pops up after trying to update the branch

Hey @bombillazo, this is probably thrown because there are mismatching dependencies in examples etc. for `@ant-design/icons`. Can you try fixing the version for all occurrences and see if the issue persists? 🙏

2024-05-24 11:58 UTC, bombillazo commented
OK now its updated

2024-05-24 13:11 UTC, BatuhanW requested changes

2024-05-24 13:11 UTC, BatuhanW commented on .changeset/fast-bags-count.md
> +lock @ant-design/icons version
Why do we need these?

2024-05-28 10:21 UTC, BatuhanW approved these changes

2024-06-03 12:09 UTC, merged