feat: add `selectedOptionsOrder` in `useSelect`
refinedev/refine pull request #6071
Opened 2024-06-22 08:32 UTC by Dominic-Preap

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [x] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Cannot sort `selectedOptions` at the top of list when use `useSelect` with `defaultValue`.

## What is the new behavior?

feat: add `selectedOptionsOrder` in `useSelect`

fixes # (https://github.com/refinedev/refine/issues/6061)

## Notes for reviewers

2024-06-26 06:25 UTC, alicanerdurmaz approved these changes

2024-06-27 09:24 UTC, aliemir commented on documentation/docs/ui-integrations/mantine/hooks/use-select/index.md
> +### selectedOptionsOrder
Documentation of other `useSelect` hooks and extensions should also include this prop:

| Hook              | File |
| ------------- | ------------- |
| `@refinedev/antd#useSelect` | documentation/docs/ui-integrations/ant-design/hooks/use-select/index.md |
| `@refinedev/antd#useRadioGroup`  | documentation/docs/ui-integrations/ant-design/hooks/use-radio-group/index.md  |
| `@refinedev/antd#useCheckboxGroup` | documentation/docs/ui-integrations/ant-design/hooks/use-checkbox-group/index.md |
| `@refinedev/antd#useCheckboxGroup` | documentation/docs/ui-integrations/ant-design/hooks/use-checkbox-group/index.md |

2024-06-27 09:29 UTC, aliemir requested changes
Hey @Dominic-Preap, thank you for the contribution! 🚀 There was a small issue in the test case, I pushed a fix for it! Other than that, I left a comment about the documentation and some adjustments that might be needed for the extensions of the `useSelect` hook.

Let us know if you can work on these as well 🙏

2024-06-28 09:34 UTC, Dominic-Preap commented
Okay I'll update it tonight.

2024-06-28 15:43 UTC, Dominic-Preap commented on documentation/docs/ui-integrations/mantine/hooks/use-select/index.md
> +### selectedOptionsOrder
I have updated the related components & the docs. Let me know if I'm missing something.

2024-07-01 10:10 UTC, aliemir approved these changes
Thank you for the update @Dominic-Preap! I've sent a small update and added `@refinedev/antd` and `@refinedev/mui` to the changeset 🚀

2024-07-01 10:51 UTC, merged