fix(antd): useDrawerForm has unused props
refinedev/refine pull request #6074
Opened 2024-06-24 07:45 UTC by alicanerdurmaz

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

`useDrawerForm` has the following props but they are not functional.

- defaultFormValues?: Store | (() => Promise<Store> | Store);
- form?: any;
- submit?: (formValues: Store) => any;

## What is the new behavior?

unused props deleted.

fixes #5727

## Notes for reviewers

There are no problems in `UseModalForm`
https://github.com/refinedev/refine/blob/master/packages/antd/src/hooks/form/useModalForm/useModalForm.ts#L39

2024-06-26 07:20 UTC, omeraplak commented on .changeset/silver-carrots-sell.md
> +"@refinedev/antd": patch
```suggestion
"@refinedev/antd": minor
```
I think we can mark this change as minor, what do you think?

2024-06-26 07:20 UTC, omeraplak commented on .changeset/silver-carrots-sell.md
> +From now on, `useForm`, `useDrawerForm`, and `useModalForm` hooks accept the `defaultFormValues` prop to pre-populate the form with data that needs to be displayed.
```suggestion
From now on, `useForm`, `useDrawerForm`, `useStepsForm` and `useModalForm` hooks accept the `defaultFormValues` prop to pre-populate the form with data that needs to be displayed.
```
additionally useStepsForm?

2024-06-26 07:22 UTC, omeraplak requested changes

2024-06-26 07:22 UTC, omeraplak commented on documentation/docs/ui-integrations/ant-design/hooks/use-form/index.md
> +Default values for the form. Use this to pre-populate the form with data that needs to be displayed.
Can we clearly specify how it behaves in `edit` mode?

2024-06-26 07:31 UTC, omeraplak commented on packages/antd/src/hooks/form/useForm.spec.tsx
> +      { timeout: 200 },
```
  await act(async () => {
    jest.advanceTimersByTime(200);
  });

  expect(result.current.formLoading).toBe(true);
  expect(result.current.defaultFormValuesLoading).toBe(false);
```

Here, we can use act together with advanceTimersByTime instead of `waitFor`.

For more information, you can refer to the [Jest documentation on timer mocks](https://jestjs.io/docs/timer-mocks#advance-timers-by-time).

2024-06-26 15:17 UTC, alicanerdurmaz commented on .changeset/silver-carrots-sell.md
> +From now on, `useForm`, `useDrawerForm`, and `useModalForm` hooks accept the `defaultFormValues` prop to pre-populate the form with data that needs to be displayed.
`useStepsForm` was already working because it has its own form instance from "sunflower-antd". `useDrawerForm` and `useModalForm` use the instance from `useForm`.

In `useStepsForm`, we were sending `defaultValues` to "sunflower-antd", but we weren't sending them in `useForm`.

2024-07-01 12:48 UTC, omeraplak approved these changes

2024-07-01 12:49 UTC, merged