fix(docs): use refineCoreProps for useForm
refinedev/refine pull request #6126
Opened 2024-07-10 17:45 UTC by ritute

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

## What is the new behavior?

fixes (issue)

## Notes for reviewers

2024-07-11 07:50 UTC, BatuhanW requested changes
Hey @ritute thanks for the PR.

`refineCoreProps` is only needed for useForm hooks that aren't from core package. Only needed on antd, react-hook-form, mantine useForm hooks.

Also let's revert changes in `versioned_docs/version-3.xx.xx` folder.

2024-07-11 17:51 UTC, ritute commented
> Hey @ritute thanks for the PR.
> 
> `refineCoreProps` is only needed for useForm hooks that aren't from core package. Only needed on antd, react-hook-form, mantine useForm hooks.
> 
> Also let's revert changes in `versioned_docs/version-3.xx.xx` folder.

@BatuhanW undid the versioned files changes. Can update the other stuff, but was wondering when would someone use `useForm` from the core package versus from say `@refinedev/react-hook-form`? Didn't know it was part of the core package.

2024-07-12 13:41 UTC, BatuhanW approved these changes

2024-07-12 13:42 UTC, BatuhanW commented
Hey @ritute thanks for the follow-up! LGTM 👍🏼

2024-07-12 14:04 UTC, merged