feat(mui): add a loading spinner to <Show> component
refinedev/refine pull request #6131
Opened 2024-07-12 03:54 UTC by paoloLigsay

## PR Checklist

Please check if your PR fulfills the following requirements:
- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?
The `<Show>` component in the `@refinedev/mui package` currently does not display a loading spinner when data is being fetched or processed, leaving users without visual feedback during loading states.

## What is the new behavior?
The `<Show>` component now includes a loading spinner that appears when the `isLoading` prop is set to `true`. This provides users with a visual indication that data is being loaded during loading states. A test has been added to verify that the loading spinner renders when the `isLoading` prop is set to `true`.

fixes https://github.com/refinedev/refine/issues/5668

## Notes for reviewers
The loading spinner added to the `<Show>` component is based on the behavior and color of the spinner used in the `<List>` component. It utilizes the `<CircularProgress>` component with its color set to `theme.palette.primary.main`.

See testing when `isLoading` is set to `True`:

https://github.com/user-attachments/assets/1d25bac9-903d-4d19-b906-4dcdd74524d9

See testing of the actual behavior:

https://github.com/user-attachments/assets/6e598b7f-a808-494c-85d8-a05cd8c737fe

This is what the current loading spinner looks like in the `<List>` component:

https://github.com/user-attachments/assets/656bdb26-64c8-4549-91f9-2e850423e859

2024-07-12 08:32 UTC, alicanerdurmaz requested changes

2024-07-12 08:32 UTC, alicanerdurmaz commented on packages/mui/src/components/crud/show/index.tsx
> +import { CircularProgress } from "@mui/material";
should be imported like that because `@mui` has issues with tree-shaking.

```suggestion
import CircularProgress from "@mui/material/CircularProgress";
```

2024-07-12 08:36 UTC, alicanerdurmaz commented
thanks for the detailed explanation 🚀

2024-07-12 11:47 UTC, paoloLigsay commented on packages/mui/src/components/crud/show/index.tsx
> +import { CircularProgress } from "@mui/material";
Aaa I see, thanks @alicanerdurmaz! I updated the import as suggested.

2024-07-18 08:34 UTC, alicanerdurmaz commented
Hello again @paoloLigsay, the PR is great, thank you for your effort. However, after discussing with the core team, we decided to make some improvements regarding the design.

The loading should be an overlay, ensuring that the children of the `<Show />` component remain visible and not unmounted, similar to the [`<Show />`](https://refine.dev/docs/ui-integrations/ant-design/components/buttons/show-button/) component of Ant Design. We thought this way it would prevent flicker and look better. 

![image](https://github.com/user-attachments/assets/5657e2a8-7ab8-43b5-887f-ad75bcdf5ffa)
Implementing this design might require custom CSS, but it's worth it.

Also, we need to add the same features to the `<List />` and `<Edit />` components.

Do you want to continue to work on this?

2024-08-13 23:32 UTC, aliemir commented
Unfortunately this PR is left incomplete and we're closing this due to inactivity. If anyone is interested on working on this implementation, please let us know in the related issue 🙏

2024-08-13 23:32 UTC, closed without merging