feat(package/appwrite): update `appwrite` sdk to `14.0.1` #6090
refinedev/refine pull request #6138
Opened 2024-07-13 18:11 UTC by soranoo

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [x] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

## What is the new behavior?

fixes (issue)

## Notes for reviewers

2024-07-16 08:12 UTC, BatuhanW requested changes
Hey @soranoo thanks for the PR, added some comments for changes.

2024-07-16 08:12 UTC, BatuhanW commented on packages/appwrite/CHANGELOG.md
> +
Please revert these changes. You **only** need to add changeset, we'll take care of the rest.

2024-07-16 08:12 UTC, BatuhanW commented on packages/appwrite/package.json
> +  "version": "6.6.0",
This change is also redundant.

2024-07-16 08:12 UTC, BatuhanW commented on .changeset/silver-crabs-relax.md
> +"@refinedev/appwrite": major
```suggestion
"@refinedev/appwrite": patch
```

2024-07-16 10:36 UTC, soranoo commented
Done, plz take a look.

2024-07-17 00:34 UTC, soranoo commented
Should I update the root deps?

2024-07-17 09:27 UTC, BatuhanW commented
@soranoo you need to do pnpm install to update pnpm-lock.yaml. Also we'll provide new appwrite credentials, so we can record tests again. These tests doesn't ensure that it works correctly, just make assertions on already hardcoded mocks.

2024-07-23 06:08 UTC, aliemir reviewed
Hey @soranoo, is there any specific reason for you to stay in v14 instead of 15? 

There was some issues with our tests, I've updated them accordingly with fresh data. Also due to the changes in the SDK, updated one line in examples.

Also bumped Appwrite dependency to 15 🤔 Any reason behind the downgrade to 14? 

Thank you for your contribution! 🙏

2024-07-23 07:22 UTC, soranoo commented
The package works with Appwrite SDK 15.0.0 but the tests don't. 

Here's the problem I am facing
https://github.com/refinedev/refine/issues/6090#issuecomment-2227038565

But you just got everything on the right track.
Thank you ❤️

2024-07-30 08:11 UTC, alicanerdurmaz approved these changes

2024-07-30 13:34 UTC, merged