feat(react-hook-form): update version (#6139)
refinedev/refine pull request #6161
Opened 2024-07-19 18:18 UTC by ritute

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

## What is the new behavior?

fixes (issue)

## Notes for reviewers

2024-07-19 18:26 UTC, aliemir requested changes
Thank you for the quick PR @ritute! Can you also add changesets for the updated packages?

`@refinedev/live-previews` is not published so no changeset is needed. Check out our [Contributing Guide](https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset) to learn how to add changesets 🙏 Let me know if you encounter any issues 🚀

2024-07-19 18:29 UTC, ritute commented
@aliemir yup, was just doing that

2024-07-20 06:29 UTC, aliemir approved these changes
Thank you for the update! 🙏 This will be included in our next release 🤖

2024-07-20 16:58 UTC, ritute commented on .changeset/metal-eagles-notice.md
> +feat(react-hook-form): update version constraint from `^6.30.0` to `^6.43.5`
@aliemir typo on version, should be 7 major :)

2024-07-20 23:04 UTC, aliemir commented on .changeset/metal-eagles-notice.md
> +feat(react-hook-form): update version constraint from `^6.30.0` to `^6.43.5`
```suggestion
feat(react-hook-form): update version constraint from `^7.30.0` to `^7.43.5`
```

🤦🤦 Thank you @ritute! 😅

2024-07-22 06:18 UTC, alicanerdurmaz approved these changes

2024-07-26 07:37 UTC, merged