feat(cli): improve the resource add command to generate page files for Next.js
refinedev/refine pull request #6162
Opened 2024-07-20 03:37 UTC by noritsune

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?
The files generated by the CLI are all components. So we have to make pages by hand to use it.

## What is the new behavior?
When using the add resource command in a project using Next.js, a page will be generated to perform the selected actions for that resource.

These pages simply display generated components that perform actions on the resource. The placement of page files assumes operation with the App Router. If you prefer to use the Page Router instead, you'll need to move them manually.

fixes #6091

2024-07-20 07:29 UTC, aliemir reviewed
Hey @noritsune, happy to see your contribution! Thank you for the PR! 🚀 We'll review it soon 🙏

2024-07-20 08:52 UTC, noritsune commented
the test is failed... I'll check.

2024-07-20 08:56 UTC, noritsune commented
Of couase, it passes on my pc.

2024-07-20 09:11 UTC, noritsune commented
I changed the test code. It should passes.

2024-07-24 12:11 UTC, alicanerdurmaz requested changes

2024-07-24 12:11 UTC, alicanerdurmaz commented on packages/cli/templates/resource/components/create.tsx.hbs
if the project uses Next.js, the "use client" directive must be added.

2024-07-24 12:11 UTC, alicanerdurmaz commented on packages/cli/templates/resource/components/edit.tsx.hbs
if the project uses Next.js, the "use client" directive must be added.

2024-07-24 12:11 UTC, alicanerdurmaz commented on packages/cli/templates/resource/components/list.tsx.hbs
if the project uses Next.js, the "use client" directive must be added.

2024-07-24 12:11 UTC, alicanerdurmaz commented on packages/cli/templates/resource/components/show.tsx.hbs
if the project uses Next.js, the "use client" directive must be added.

2024-07-24 12:13 UTC, alicanerdurmaz commented
Hello @noritsune,

The PR looks great. I left a comment. If you could make that improvement too, it would be great. Thanks! 🙌

2024-07-24 13:04 UTC, noritsune commented
Hello @alicanerdurmaz,
Thanks for the comments. I forgot to add "use client".
Now, I added them. Could you please check those page templates again?

2024-07-25 06:17 UTC, alicanerdurmaz approved these changes

2024-07-25 06:17 UTC, alicanerdurmaz commented on packages/cli/templates/resource/pages/next/create/page.tsx.hbs
> +"use client";
'use client' should not be in page files, we should add it to component files(e.g., packages/cli/templates/resource/components/show.tsx.hbs)

Additionally, we should only add 'use client' only for Next.js projects

2024-07-25 06:18 UTC, alicanerdurmaz requested changes

2024-07-25 06:18 UTC, alicanerdurmaz commented on packages/cli/templates/resource/pages/next/create/page.tsx.hbs
> +"use client";
'use client' should not be in page files, we should add it to component files(e.g., packages/cli/templates/resource/components/show.tsx.hbs)

Additionally, we should only add 'use client' only for Next.js projects

2024-07-25 22:12 UTC, noritsune commented on packages/cli/templates/resource/pages/next/create/page.tsx.hbs
> +"use client";
I misunderstood.
Indeed, "use client" should be added to the component file, not the page file. And it should only be added if you are using Next.js.
I will make the correction.

2024-07-25 23:16 UTC, noritsune commented
@alicanerdurmaz I have modified the component template and added tests. Could you please review it again?

2024-07-26 10:08 UTC, alicanerdurmaz commented on packages/cli/templates/resource/pages/next/create/page.tsx.hbs
> +"use client";
@noritsune Thanks for everything! It looks great. I'll review by Monday at the latest. 🙌

2024-07-26 10:45 UTC, aliemir approved these changes

2024-07-26 13:20 UTC, noritsune commented
The job `Check TSDoc Links` is failed...
I don't think this has anything to do with my commits. Or is it?

2024-07-29 08:03 UTC, alicanerdurmaz approved these changes

2024-07-29 08:11 UTC, alicanerdurmaz commented
> The job `Check TSDoc Links` is failed... I don't think this has anything to do with my commits. Or is it?

it was probably not related to your commits, I updated the branch and now there is no problem 👍

2024-07-30 00:47 UTC, noritsune commented
@alicanerdurmaz Thank you for the approve! My work is done.

2024-07-30 15:51 UTC, merged