Fix/datefield undefined value
refinedev/refine pull request #6217
Opened 2024-07-31 13:12 UTC by webscriptmaster

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked: https://github.com/refinedev/refine/issues/6216
- [x] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?
The DateField shows current date if the value is null or undefined.

## What is the new behavior?
The DateField shows empty string if the value is null or undefined.

## Notes for reviewers

2024-07-31 13:15 UTC, aliemir requested changes
Hey @webscriptmaster thank you for your PR! 🚀  We also need to apply this change to other packages (`packages/mui`, `packages/mantine` and `packages/chakra-ui`), can you work on this?

Also check out our [Contributing Guide](https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset) to learn how to add a changeset for your changes 🙏

2024-07-31 13:28 UTC, webscriptmaster commented
Hello @aliemir
It's done.

2024-08-01 10:31 UTC, aliemir approved these changes

2024-08-01 10:33 UTC, alicanerdurmaz approved these changes

2024-08-01 12:24 UTC, aliemir approved these changes

2024-08-01 12:24 UTC, merged