Add Scripts for Remix SPA Mode
refinedev/refine pull request #6246
Opened 2024-08-11 05:44 UTC by YusukeSano

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Scripts for Remix SPA mode are not supported.

## What is the new behavior?

It is now possible to execute the Remix SPA Mode script by selecting it from the platform options.
resolves #6127

## Notes for reviewers

2024-08-12 06:05 UTC, alicanerdurmaz requested changes

2024-08-12 06:05 UTC, alicanerdurmaz commented on packages/cli/src/commands/runner/projectScripts.ts
> +  [ProjectTypes.REMIX_SPA]: {
CLI uses them in the `start` or `dev` [commands.](https://github.com/refinedev/refine/blob/e777c467f32c167d6a2ab13a9bb481f6abcbac2d/packages/cli/src/commands/runner/dev/index.ts#L43) But you didn't make any changes on [`getProjectType`](https://github.com/refinedev/refine/blob/e777c467f32c167d6a2ab13a9bb481f6abcbac2d/packages/cli/src/utils/project/index.ts#L4) function. Is this working according to your needs?

2024-08-12 06:37 UTC, alicanerdurmaz commented on packages/cli/src/commands/runner/projectScripts.ts
> +  [ProjectTypes.REMIX_SPA]: {
I guess it's working works when we specify the project like this `refine dev -p remix-spa`. It would be better if the CLI automatically detected that. What do you think @BatuhanW @aliemir ?

2024-08-12 17:31 UTC, YusukeSano commented on packages/cli/src/commands/runner/projectScripts.ts
> +  [ProjectTypes.REMIX_SPA]: {
Thank you for your feedback!

Do you have any suggestions for a good approach to resolving the `vite.config` file?
If automatic detection adds significant complexity, I would prefer to create a separate issue for that enhancement rather than including it in this PR.

Looking forward to your thoughts!

2024-08-13 08:17 UTC, aliemir requested changes
Hey @YusukeSano thank you for the PR! I think we can do couple of small changes;

- Let's have two new project types `REMIX_VITE` and `REMIX_SPA` (or `REMIX_VITE_SPA`). Probably only difference will be the `start` command and its executable. 

- In the `getProjectType` method, we can check for `vite` and `remix` dependencies. Like we do in rest of the types. No need for checking `vite.config.ts` etc.

- `REMIX_VITE` can use the configuration you added in the PR for the `dev` and `build` commands but Remix + Vite without SPA mode should use `remix-serve` for the `start` command. You can check the `getBin` and `getStart` properties of the current Remix type and see how we implemented before.

- `REMIX_VITE_SPA` should use `vite preview` command for the start command and therefore `getStart` and `getBin` should be updated in according to these. Your current changes for the `getStart` and `getBin` can work there.

- `getProjectType` method shouldn't check for the SPA mode and only check for `REMIX_VITE` based on the dependencies of the project.

- If a user is using Remix + Vite, we'll be able to successfully determine the `dev` and `build` commands. Only difference will be the `start` command between Remix + vite and spa mode. For SPA mode users, they can use `refine start -p remix-vite-spa` and explicitly pass the project type, then we'll use the `vite preview` for it.

Let me know if this is clear and if you can work on this, we'll be happy to review the changes 🙏

2024-08-13 08:18 UTC, aliemir commented on packages/cli/src/commands/runner/projectScripts.ts
> +  [ProjectTypes.REMIX_SPA]: {
Left a separate comment also clearing the issue of this conversation. Please check @alicanerdurmaz and @YusukeSano 🙏

2024-08-20 04:19 UTC, aliemir approved these changes
Hey @YusukeSano thank you for your contribution and patience. Great job 🚀 🚀 This will be included in our next release 🙏

2024-08-20 11:33 UTC, alicanerdurmaz approved these changes

2024-08-20 21:51 UTC, merged