chore(devtools-server): replace `preferred-pm` with `package-manager-detector`
refinedev/refine pull request #6250
Opened 2024-08-12 15:33 UTC by benmccann

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

preferred-pm pulls in 24 dependencies, which is unnecessary for what it does: https://npmgraph.js.org/?q=preferred-pm

## What is the new behavior?

ref https://github.com/refinedev/refine/issues/6242

package-manager-detector has no dependencies: https://npmgraph.js.org/?q=package-manager-detector

## Notes for reviewers

2024-08-13 12:44 UTC, aliemir requested changes
Hey @benmccann, thank you for the PR! 🚀  Looks like you've missed adding `package-manager-detector` to the dependencies of `@refinedev/devtools-server`. Can you add it? Also a similar change is also needed on the `@refinedev/cli` to completely remove `preferred-pm` from the Refine packages. 

Let us know if you can make the necessary updates 🙏

2024-08-13 15:04 UTC, benmccann commented
Oops. not sure how I missed adding the package. It's been updated now

If it's okay, could we keep this PR to just the `@refinedev/devtools-server` and do the CLI separately?

2024-08-13 15:08 UTC, aliemir approved these changes
Thank you for the update @benmccann, yeah we can keep this for devtools-server and handle cli in a separate one 🚀

2024-08-15 11:30 UTC, BatuhanW approved these changes

2024-08-15 11:30 UTC, merged