fix(docs): address feedbacks for documentation
refinedev/refine pull request #6268
Opened 2024-08-19 12:46 UTC by BatuhanW

Addressing user requests from documentation's inline feedback flow.

![Screenshot 2024-08-19 at 15 45 30](https://github.com/user-attachments/assets/bef90807-106d-4628-b0c3-94591dd168dd)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

## What is the new behavior?

fixes (issue)

## Notes for reviewers

2024-08-20 04:00 UTC, aliemir requested changes
Changes in the packages (except for CHANGELOG.md files) should be referenced in a changeset or removed

2024-08-20 14:49 UTC, omeraplak approved these changes
🥰

2024-08-23 09:19 UTC, BatuhanW commented
> Changes in the packages (except for CHANGELOG.md files) should be referenced in a changeset or removed

Removed changes in packages from this PR. Will create a separate one agains `releases/september`.

2024-08-23 09:25 UTC, aliemir approved these changes

2024-08-23 10:38 UTC, merged