Ferdiunal/refine shadcn
refinedev/refine pull request #6280
Opened 2024-08-24 19:24 UTC by ferdiunal

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [ ] Related issue(s) linked
- [x] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

## What is the new behavior?

## Notes for reviewers

2024-08-24 19:47 UTC, omeraplak commented
Hey @ferdiunal @refinedev/core @refinedev/marketing ,
Thank you so much for the amazing and remarkable contribution @ferdiunal ! I think it's really important to categorize the Refine Packages correctly when listing them. How about adding them to the 'Community Packages' category?

2024-08-24 22:40 UTC, ferdiunal commented
> Hey @ferdiunal @refinedev/core @refinedev/marketing , Thank you so much for the amazing and remarkable contribution @ferdiunal ! I think it's really important to categorize the Refine Packages correctly when listing them. How about adding them to the 'Community Packages' category?

@omeraplak I moved to community packages. Thank you for your support.

2024-08-26 07:26 UTC, BatuhanW approved these changes

2024-08-26 07:26 UTC, BatuhanW commented on documentation/docs/guides-concepts/ui-libraries/index.md
> +- [Shadcn UI with `@ferdiunal/refine-shadcn`](https://github.com/ferdiunal/refine-shadcn?tab=readme-ov-file#useage)
```suggestion
- [Shadcn UI with `@ferdiunal/refine-shadcn`](https://github.com/ferdiunal/refine-shadcn)
```

2024-08-26 07:28 UTC, BatuhanW requested changes
Should be in this page: https://refine.dev/docs/packages/list-of-packages/#%EF%B8%8F-community-packages

2024-08-27 10:29 UTC, BatuhanW approved these changes

2024-08-27 10:30 UTC, merged