feat(graphql): rewrite GraphQL data provider
refinedev/refine pull request #6357
Opened 2024-09-19 10:11 UTC by BatuhanW

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [x] Tests for the changes have been added
- [x] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

## What is the new behavior?

fixes #5942 #5943 

## Notes for reviewers

2024-09-19 14:30 UTC, omeraplak approved these changes

2024-09-19 22:11 UTC, aliemir commented on packages/graphql/src/dataProvider/options.ts
> +};
This type is also used in the `dataProvider` export and forces user to define both of the functions. It should allow partial assignments.

2024-09-19 23:00 UTC, aliemir requested changes
Left couple of comments for types, typos and conventions. Thank you 🙏

2024-10-07 06:39 UTC, aliemir requested changes

2024-10-07 06:39 UTC, aliemir commented on packages/graphql/src/dataProvider/newOptions.ts
Unwanted file here.

2024-10-07 06:39 UTC, aliemir commented on packages/graphql/src/utils/buildFilters.ts
> +import set from "lodash/set";
`lodash` dependency is missing from `package.json`

2024-10-10 12:32 UTC, BatuhanW commented on packages/graphql/src/dataProvider/options.ts
> +    },
It's handled here: https://github.com/refinedev/refine/blob/936e9fc80ab3b94cc4dfec0bda8e41442011f747/packages/graphql/src/dataProvider/index.ts#L138

2024-10-10 14:22 UTC, aliemir commented on packages/graphql/src/dataProvider/options.ts
> +    },
Not really. This returns a single item in an array. `updateMany` should return as many items in an array as the provided number of ids.

2024-10-10 14:53 UTC, BatuhanW commented on packages/graphql/src/dataProvider/options.ts
> +    },
We shouldn't force it. For example these are valid responses:

```
mutation UpdateManyBlogPosts($input: UpdateManyBlogPostsInput!) {
  updateManyBlogPosts(input: $input) {
    updatedCount
  }
}

mutation DeleteManyBlogPosts($input: DeleteManyBlogPostsInput!) {
  deleteManyBlogPosts(input: $input) {
    deletedCount
  }
}
```

2024-10-14 11:44 UTC, aliemir approved these changes

2024-10-14 12:19 UTC, merged