fix(core): wrap `setFiltersFn` with `useCallback`
refinedev/refine pull request #6386
Opened 2024-10-03 20:02 UTC by hugorezende

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Adding the `setFilters` as a dependency in the useEffect hook causes infinite loop since setFiltersFn are not wrapped in `useCallbacks`

## What is the new behavior?

No infinite loop

fixes #6385

2024-10-10 20:54 UTC, aliemir requested changes
Hey @hugorezende thank you for the PR! I've made a small change request in the changeset and left two comments for the dependency arrays, can you check them and apply the necessary changes? 🙏 

Then, we can include this in our next release 🚀 🚀

2024-10-10 20:54 UTC, aliemir commented on packages/core/src/hooks/useTable/index.ts
> +    [setFilters, unionFilters, preferredPermanentFilters],
`setFilters` is a SetStateAction and `unionFilters` is an imported util, they don't need to be included in the dependency arrays.

2024-10-10 20:54 UTC, aliemir commented on packages/core/src/hooks/useTable/index.ts
> +    [setFilters, unionFilters, preferredPermanentFilters],
Also can you make a similar update in the `setSortWithUnion` function as well? 🙏

2024-10-10 20:54 UTC, aliemir commented on .changeset/spotty-jokes-swim.md
> +fix: fix setFiltersFn #6385
```suggestion
fix(core): wrap `setFilters` and `setSorters` methods with `useCallback` to prevent looping re-renders
```

Having a bit more info in the first line will be great for the changelogs 😅

2024-10-11 14:24 UTC, hugorezende commented on packages/core/src/hooks/useTable/index.ts
> +    [setFilters, unionFilters, preferredPermanentFilters],
hey @aliemir, thanks for checking the PR. I'm just so used with the exhaustive rule i didn't realised it 😄  
Just fixed those and also added it on `setSortWithUnion` 
990f8e9

2024-10-14 06:55 UTC, alicanerdurmaz approved these changes

2024-10-14 12:28 UTC, merged