Fix/core/list url params
refinedev/refine pull request #6389
Opened 2024-10-06 21:16 UTC by arndom

- Update `useTable` hook to handle case where a user navigates to current page by clicking side-nav link intending to reset the filters and sorters.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?
In a table, apply some filters/sorters then click the menu item in the sidebar, the URL should reset filters and sorters to the default but it doesn't.

This can be previewed at https://example.admin.refine.dev/orders

## What is the new behavior?
The above has been resolved. It resets the query params for filters and sorters back to their defaults.

fixes #6300 

## Notes for reviewers

2024-10-07 06:48 UTC, BatuhanW requested changes
Hey @arndom thanks for the PR, please make sure to add tests for the behavior.

2024-10-07 06:48 UTC, BatuhanW commented on .changeset/spicy-flowers-allow.md
> +"@refinedev/core": major
```suggestion
"@refinedev/core": patch
```

2024-10-10 21:26 UTC, aliemir requested changes
Hey @arndom thank you for your effort! 🙏 I've left a comment in the issue (https://github.com/refinedev/refine/issues/6300#issuecomment-2406062566) about the implementation we're looking for. 

While your changes will work for the reported case, it won't cover other cases such as changing the query params without using the `useTable` hook. 

Let us know if you can work on the changes described in the comment 🙏

2024-10-12 12:35 UTC, arndom commented
@aliemir Sure, it's best to finish what I started properly...though I may need some guidance as I'm still fresh on the codebase

2024-10-28 09:23 UTC, BatuhanW commented
Hey @arndom are you gonna be able to continue on this PR? Please let us know if you need help with a specific issue. We'd be happy to guide you through.

2024-10-28 11:17 UTC, arndom commented
@BatuhanW I still plan to, I just haven't had the time recently due to my work schedule. Some help on the approach to solving this would be great.
 
My current thought process: Since `syncWithLocation` defined in refine context is used by multiple implementations for params syncing, a change in all those may provide a fix (possibly a shared function). I am unsure about its efficiency or if there are better solutions as I haven't spent that much time in the repo.

2024-12-01 17:01 UTC, arndom commented
@aliemir I believe the recent commits take into consideration the updating of filters and sorters; URL state -> internal state and vice versa.

2024-12-03 08:22 UTC, aliemir commented
Hey @arndom, I've tried on my local but looks like the effect is exceeding the max depth and even if I ignore it, it starts looping when I have a change in filters 🤔 I'll try to look again to see what went wrong and at least provide tips to get it back on track 🙏

2024-12-03 16:02 UTC, arndom commented
Sorry about that, seems I did not test properly, I'll go through it again and resolve the issues

2024-12-10 06:27 UTC, BatuhanW commented
Hey @arndom feel free to re-open it when your changes are complete.

2024-12-10 06:27 UTC, closed without merging