Patch for #6498
refinedev/refine pull request #6502
Opened 2024-11-18 18:09 UTC by aress31

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

See #6498.

## What is the new behavior?

fixes (issue)

## Notes for reviewers

I am not sure how to add the tests and where to add the doc, if you could walk me through the process for future contributions that would help.

2024-11-20 10:31 UTC, alicanerdurmaz requested changes

2024-11-20 10:31 UTC, alicanerdurmaz commented on packages/ui-types/src/types/layout.tsx
> +  childrenBoxProps?: BoxProps;
These types should be on [@refinedev/mui](https://github.com/refinedev/refine/blob/446f467ae2b7f9b65873e3cd78c8b5f99df1f903/packages/mui/src/components/themedLayoutV2/index.tsx#L10) package because `@refinedev/ui-types` packages used by other UI packages and these packages don't use these props.

2024-11-20 10:31 UTC, alicanerdurmaz commented on packages/mui/src/components/themedLayoutV2/index.tsx
> +            {...restChildrenProps}
These styles should not be removed; otherwise, backward compatibility will be broken.

2024-11-20 10:31 UTC, alicanerdurmaz commented on packages/mui/src/components/themedLayoutV2/index.tsx
> +          }}
These styles should not be removed; otherwise, backward compatibility will be broken.

2024-12-03 09:24 UTC, alicanerdurmaz commented
Hello again @aress31,

I just wanted to remind you that my change requests are still pending. We would greatly appreciate it if you could spare time and resolve this issue.

About the tests: Currently, there is no test for `<ThemedLayoutV2 />`. It would be great if you could create a file like `/mui/src/components/themedLayoutV2/index.spec.tsx` and write tests for it.

About the documentation: You can update this section:  
**Doc page:** [[Themed Layout Props Documentation](https://refine.dev/docs/ui-integrations/material-ui/components/themed-layout/#props)](https://refine.dev/docs/ui-integrations/material-ui/components/themed-layout/#props)  
**File:** [[Themed Layout Doc File](https://github.com/refinedev/refine/blob/main/documentation/docs/ui-integrations/material-ui/components/themed-layout/index.md)](https://github.com/refinedev/refine/blob/main/documentation/docs/ui-integrations/material-ui/components/themed-layout/index.md)

2024-12-05 12:12 UTC, aress31 commented
@alicanerdurmaz MUI-specific types and docs done. For the test I am not sure what type of test would be relevant so please feel free to implement them.

2024-12-09 09:26 UTC, alicanerdurmaz approved these changes

2024-12-09 09:49 UTC, merged