Patch for #6497
refinedev/refine pull request #6503
Opened 2024-11-18 18:22 UTC by aress31

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

Fix for #6497.

## What is the new behavior?

fixes (issue)

## Notes for reviewers

The following tasks have not been performed, kindly complete them to provide me with a how-to example:

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

2024-11-19 15:03 UTC, BatuhanW requested changes
Hey @aress31 thanks for taking time to create issues and the PR.

In your PR, please do not include any irrelevant changes. Only the changes related to your fix and specs. 

Imports like `import HomeOutlined from "@mui/icons-material/HomeOutlined";` are not coincidence. They are intentionally like that because of bundling issues with mui library.

2024-11-19 15:08 UTC, BatuhanW commented
@aress31 For tests, you can update the tests in `packages/mui/src/components/breadcrumb/index.spec.tsx` file. We have `routerInitialEntries: ["/posts/create"],` there, you can add new cases with `routerInitialEntries: ["/posts"],` and see if it renders. You can also stash your changes and run the test to see if new test correctly fails.

2024-11-19 15:22 UTC, aress31 commented
> Hey @aress31 thanks for taking time to create issues and the PR.
> 
> In your PR, please do not include any irrelevant changes. Only the changes related to your fix and specs.
> 
> Imports like `import HomeOutlined from "@mui/icons-material/HomeOutlined";` are not coincidence. They are intentionally like that because of bundling issues with mui library.

@BatuhanW besides reverting the imports, what else do you want me to change? I think refactoring the file as I did help with modularity and readability - killing two birds with one stone.

2024-11-19 23:15 UTC, aress31 commented
As requested, I focused solely on the fix. However, I recommend reviewing my previous commits with the refactoring. Some styles, such as default padding and `fontSize`, should, in my opinion, be removed to keep the component unstyled, allowing users to customize it via `breadcrumbProps`. Additionally, I suggest improving modularity by splitting the breadcrumb and home rendering logic.

2024-11-20 10:19 UTC, alicanerdurmaz requested changes
Hello @aress31, Thanks for improving Refine 🚀

I added comments to the issue [about](https://github.com/refinedev/refine/issues/6497#issuecomment-2488156514) implementation. Please feel free to ask questions if you have any concerns

2024-11-20 13:27 UTC, alicanerdurmaz requested changes

2024-11-20 13:27 UTC, alicanerdurmaz commented on packages/antd/src/components/breadcrumb/index.tsx
> +  if (breadcrumbs.length >= minItems) return null;
I believe it should be like this:

```suggestion
  if (breadcrumbs.length < minItems) return null;
```

2024-11-21 08:17 UTC, alicanerdurmaz requested changes

2024-11-21 08:17 UTC, alicanerdurmaz commented on packages/antd/src/components/breadcrumb/index.tsx
> +  if (breadcrumbs.length < minItems) return null;
- case 1: breadcrumbs.length = 0:  // both versions return null
- case 2: breadcrumbs.length = 1:  // old version returns null, new version shows
- case 3: breadcrumbs.length = 2:  // Both versions renders 

we have two options to fix case 2:
1. 
```suggestion
  if (breadcrumbs.length <= minItems) return null;
```
2. default should be set to 2 `minItems = 2`

I believe second option is better because it fits `minItems` name.

2024-11-21 12:01 UTC, aress31 commented on packages/antd/src/components/breadcrumb/index.tsx
> +  if (breadcrumbs.length < minItems) return null;
I agree with point 1 but why should the default be set to 2? What is the rational behind this? If there is a configured route, the breadcrumb should show it be default unless instructed otherwise? 2 also seems arbitrary, why not3? :)

2024-11-25 07:15 UTC, alicanerdurmaz commented on packages/antd/src/components/breadcrumb/index.tsx
> +  if (breadcrumbs.length < minItems) return null;
Because previously, the breadcrumb would render only if there were at least 2 items, but it wouldn’t render if there was only 1 item. So, `minItems` should be 2. If we break this logic, it would be a breaking change, and current users who update Refine would see a breadcrumb even in cases with just 1 item.

I'm with you. If the route is configured, it should render, but we shouldn't make breaking changes, even if the old implementation is wrong.

2024-11-25 07:22 UTC, aress31 commented on packages/antd/src/components/breadcrumb/index.tsx
> +  if (breadcrumbs.length < minItems) return null;
We should be good to merge then since I have the default for `minItems` to be `2`. Please let me know if there is another blocker.

Also for future major release might be a good idea to implement the breaking change of setting `minItems` to `1`.

2024-11-26 06:29 UTC, alicanerdurmaz commented on packages/antd/src/components/breadcrumb/index.tsx
> +  if (breadcrumbs.length < minItems) return null;
Everything is good, thanks but `should not render breadcrumb when the number of items is less than minItems` This test is not passing

2024-11-27 14:03 UTC, aress31 commented on packages/antd/src/components/breadcrumb/index.tsx
> +  if (breadcrumbs.length < minItems) return null;
@alicanerdurmaz should be fixed now, kindly review.

2024-12-03 13:38 UTC, merged