feat: add KY data provider to simple-rest package
refinedev/refine pull request #6544
Opened 2024-12-01 12:01 UTC by OmkarBansod02

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [ ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

The `@refinedev/simple-rest` package currently includes only an Axios-based data provider. Users do not have the option to use KY for handling HTTP requests.

## What is the new behavior?

The package now includes a KY-based data provider, providing users with an alternative lightweight HTTP client. The KY provider mirrors the Axios implementation's structure, ensuring consistency, type safety, and robust error handling.

fixes #6381

## Notes for reviewers

i’ve added the KY data provider to the `@refinedev/simple-rest` package, following the same structure as the Axios provider.  The key difference is KY’s simplicity and built-in query handling, which makes the implementation lighter and more efficient for 
certain use cases. You can find more about KY here: [KY Documentation](https://github.com/sindresorhus/ky).

Here is comparison :

Axios Example :  

![Screenshot 2024-12-01 171936](https://github.com/user-attachments/assets/aafe9bbe-1f14-4220-8fd0-934576d83a3a)

KY Example: 

![Screenshot 2024-12-01 172327](https://github.com/user-attachments/assets/3858d011-2062-4bbd-970a-ebb9ca8a7101)

KY is a lightweight and simpler alternative to Axios. It uses searchParams for query parameters and simplifies response handling with .json(). 

-  I haven’t included tests yet because i wanted to get an initial review to ensure the implementation is solid. If the code looks strong, I will proceed to add test cases in a follow-up. 

- i need your input on whether this change should be categorized as minor or major for the changesets.

Looking forward to your feedback and suggestions for improvement! 

Thanks!

2024-12-02 14:14 UTC, BatuhanW requested changes
Hey @OmkarBansod02 thanks for the PR!

Added some minor comments, generally it looks good. We'll know better when the tests are added. Make sure you use nock library to record *new* requests and create tests based on them.

Looking forward to your updates 🚀

2024-12-02 14:14 UTC, BatuhanW commented on packages/simple-rest/package.json
> +    "query-string": "^7.1.1",
Let's use `qs` package because it supports encoding query params with nested structures.

2024-12-02 14:14 UTC, BatuhanW commented on packages/simple-rest/package.json
> +    "axios": "^1.6.2",
```suggestion
```

We don't need this, it should be in dependencies already.

2024-12-02 14:14 UTC, BatuhanW commented on packages/simple-rest/src/ky/utils/ky.ts
> +};
Why do we need both?

2024-12-02 17:06 UTC, OmkarBansod02 commented on packages/simple-rest/src/ky/utils/ky.ts
> +};
` kyInstance`  is a default instance of ky with a pre-configured setup (e.g., error handling hooks). ` kyInstance ` is sufficient for  `refinedev`  usecase. 

I added `createKyInstance` to allow more flexibility, like using multiple APIs or customizing hooks if needed. If this flexibility isn’t useful for refine.dev right now, we can remove it to keep things simpler.

2024-12-04 10:44 UTC, BatuhanW commented on packages/simple-rest/src/ky/utils/ky.ts
> +};
Where do we use `createKyInstance`?

2024-12-05 14:58 UTC, BatuhanW commented
Hey @OmkarBansod02 thanks for the PR. I'll need to close it and update the issue with more details, since it wasn't explained well. I'll discuss with core team to decide for necessary changes.

2024-12-05 14:58 UTC, closed without merging