feat(core): update useNavigation to pass meta.query as URL params
refinedev/refine pull request #6558
Opened 2024-12-05 13:06 UTC by OmkarBansod02

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention

## Bugs / Features

- [x] Related issue(s) linked
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated
- [x] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset

## What is the current behavior?

`listUrl` , `createUrl` , `editUrl` , `showUrl` and `cloneUrl ` functions in `useNavigation` hook doesn't properly process query filters passed through the  `meta ` parameter, resulting in missing query parameters in the generated URL

## What is the new behavior?

The functions now correctly processes and includes query parameters from the  `meta`  object when generating URLs, enabling proper query filter support for any component that uses the `useNavigation ` hook
fixes #6528

## Notes for reviewers

I’ve created a new PR for the `releases/december-2024 branch` , reapplying the changes from the previous PR [#6530 ] that was merged into main by mistake. . Please review and let me know if adjustments are needed.

2024-12-05 15:02 UTC, BatuhanW requested changes
@OmkarBansod02 thanks for re-opening the PR. Could you add github issue url to the bottom line in the changeset as it was in the previous PR?

2024-12-05 16:57 UTC, OmkarBansod02 commented
> @OmkarBansod02 thanks for re-opening the PR. Could you add github issue url to the bottom line in the changeset as it was in the previous PR?

Done 👍

2024-12-05 22:07 UTC, youneshenniwrites commented on .changeset/dry-tomatoes-beg.md
> +This PR fixes an issue where the ListButton componet doesnt include query filter in the URL navigating.
```suggestion
This PR fixes an issue where the ListButton component doesn't include a query filter in the navigation URL.
```

2024-12-06 07:31 UTC, BatuhanW approved these changes
Thanks @OmkarBansod02 and @youneshenniwrites

2024-12-06 07:31 UTC, merged